- .github/workflows/npm-publish.yml
Create a new workflow to automatically publish to NPM on each release creation.
> Create NPM Workflow

- src/components/Blik/components/BlikInput.tsx
Fix the broken invalid code translation on the Blik component.
> Fix invalid Blik code translation string

- .github/workflows/coveralls.yml
Adds Coveralls integration on pull request
> Create coveralls workflow

- src/components/internal/PersonalDetails/PersonalDetails.tsx
Fix validation when a namePrefix is passed in the Personal Details component.
> Fix validation on Personal Details component

- .github/workflows/npm-publish.yml
- config/version.js
- config/webpack.prod.js
- src/core/core.ts
- Adds a unique build ID
- Allows downloading artifacts after publishing workflow
> CI Build improvements

- package.json
- yarn.lock
Enable cross-environment set up
When running the application install on a windows OS, the packages are installed properly.
When running the application, it starts without issues.  
Set up was crashing when setting up the application inside a win system.
> add cross-env package

- playground/QRCode/QRCode.js
- playground/config/commonConfig.js
Remove merchantAccount overrides from playground
> Remove merchantAccount overrides from playground

- package.json
* Fix state field validation in the Card component (#44)
* Await component calls onAdditionalDetails for refused responses (#40)
* Include storePaymentMethod in data output when unchecked (#37)
* Add cross-env package (#35, thanks @epereztg)
> Release v3.9.5

- src/components/ApplePay/ApplePay.test.ts
- src/components/ApplePay/ApplePay.tsx
- src/components/ApplePay/defaultProps.ts
- src/components/ApplePay/payment-request.test.ts
- src/components/ApplePay/payment-request.ts
- src/components/ApplePay/types.ts
- src/components/ApplePay/utils.test.ts
- src/components/ApplePay/utils.ts
- src/components/BaseElement.test.ts
- src/components/BaseElement.ts
- src/components/Blik/components/BlikInput.tsx
- src/components/Card/Card.tsx
- src/components/Dropin/Dropin.tsx
- src/components/Dropin/components/DropinComponent.tsx
- src/components/Dropin/types.ts
- src/components/MBWay/MBWay.tsx
- src/components/MBWay/components/MBWayInput/MBWayInput.tsx
- src/components/PayPal/Paypal.tsx
- src/components/PayPal/types.ts
- src/components/Sepa/Sepa.js
- src/components/UIElement.tsx
- src/components/internal/Await/Await.tsx
- src/core/RiskModule/RiskModule.tsx
- src/core/core.ts
- src/core/types.ts
- src/language/types.ts
- src/types/index.ts
- src/utils/getProp.ts
- tsconfig.json
This PR improves type-checking and it allows autocomplete of configuration properties on both Drop-in and Components.
> Improve types on elements

- src/components/PayPal/components/PaypalButtons.test.tsx
- src/components/PayPal/config.ts
- src/components/PayPal/defaultProps.ts
- src/components/PayPal/types.ts
- src/components/PayPal/utils.ts
- Update PayPal utils file to do a better validation of the locale before passing it to the PayPal SDK, to merge similar functions and to add comments.
- Update PayPal types and defaultProps files to add comments, links and supported locales.
- Add supported locales constant.
- Small update on tests.
> PayPal component improvements

- package.json
Change homepage URL to relevant documentation in package.json
> Change homepage URL to relevant documentation in package.json

- README.md
- Add installation instructions
- Replace Drop-in/Components text for documentation links
> Add Installation section to README.md

- config/webpack.dev.js
- config/webpack.prod.js
- package.json
- yarn.lock
- Remove unused webpack file-loader
> Remove unused file-loader

- README.md
Added Rationale & Warning sections to README
> Added Rationale & Warning to README

- package.json
- yarn.lock
> Remove unused dependency postcss-reporter

- .eslintrc.js
- package.json
- src/components/Giftcard/components/GiftcardResult.js
- src/components/internal/Await/Await.tsx
- src/components/internal/FormFields/Select/Select.js
- src/components/internal/Img/Img.js
- src/components/internal/QRLoader/QRLoader.js
- src/components/internal/Voucher/Voucher.tsx
- yarn.lock
- Fix missing alt attributes in image tags
- Add linting rule to enforce all images contain an alt attribute
- Fix incorrect aria-* attrinute on Select component
- Add more a11y linting rules
> Accessibility linting

- package.json
* Add callbackIntents support to Google Pay component (#52)
* i18n interpolation and plurals support (#83)
* Fix `dropin.submit()` function when used on the Google Pay component (#47)
* Fix Google Pay css styles to work with new styles (#49)
* Fix validation on stored cards when billingAddress was required (#84)
> Release 3.10.0

- package.json
- yarn.lock
Downgrade prettier version for compatibility
> Downgrade prettier version for compatibility

- src/components/internal/SecuredFields/lib/core/initCSF.ts
- Check for clientKey and fallback to originKey on CSF
- Card component works with clientKey and originKey
- Card component works with only clientKey
- Card component works with only originKey
> Check for clientKey and fallback to originKey on CSF

- package.json
- Check for clientKey and fallback to originKey on CSF (#95)
> Release 3.10.1

- src/components/BillDesk/BillDeskWallet.ts
- src/components/helpers/withIssuerList.tsx
- src/components/internal/IssuerList/IssuerList.tsx
- src/language/locales/en-US.json
- BillDeskWallet shows a more appropriate placeholder
> Add new placeholder to BillDeskWallet

- .eslintrc.js
- src/components/ApplePay/components/ApplePayButton.tsx
- src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
- src/components/internal/Button/Button.js
- src/components/internal/FormFields/Field/Field.js
Update the Button component to receive rel attribute for anchor tags and to remove a redundant role=presentation tag. Other minor improvements.
- Update the Button component to receive `rel` attribute for anchor tags and to remove a redundant `role=presentation` attribute.
- Add `type=button` on the Remove button.
- Replace Span with Div.
> Minor accessibility improvements

- src/components/Card/Bancontact.ts
- src/components/Card/Card.tsx
- src/components/Card/types.ts
- src/components/Dropin/types.ts
- src/core/Analytics/Analytics.ts
- src/core/Analytics/types.ts
- src/core/ProcessResponse/PaymentMethodsResponse/types.ts
- src/core/RiskModule/RiskModule.tsx
- src/core/core.ts
- src/core/types.ts
- src/types/index.ts
- Add more property types to Core options
- Extract Card types
> Improve types

- src/components/Card/Card.tsx
- src/components/internal/SecuredFields/SecuredFieldsProvider.test.tsx
Improvements to the unsupported card functionality as recommended by pablo
> Made tests more readable. Used TS optional chaining

- src/components/PayPal/config.ts
> Fix export on paypal config

- package.json
* Cards: Handling unsupported cards (#105)
* Add missing declaration TypeScript files on NPM Bundle (fixes issue #104)
* Apple Pay: Use merchantName as totalPriceLabel if totalPriceLabel is not defined (#111)
* Bancontact: Default Bancontact Card brand (#103)
> Release 3.11.0

- playground/pages/Dropin/Dropin.html
- playground/pages/Wallets/Wallets.html
- playground/pages/Wallets/Wallets.js
- src/components/GooglePay/GooglePayService.ts
- src/components/GooglePay/components/GooglePayButton.tsx
- src/components/GooglePay/config.ts
- src/utils/loadScript.ts
- Load GooglePay script automatically if not available
- Added a generic `loadScript` util
> Load GooglePay script automatically if not available

- .github/workflows/coveralls.yml
- Update coveralls checkout action to v2
> Fix Coveralls workflow

- src/components/Card/components/CardInput/CardInput.tsx
- src/components/Card/components/CardInput/components/CardFields.tsx
- src/components/internal/SecuredFields/lib/core/utils/iframes/setFocusOnFrame.ts
- Allow focus on optional security code fields
- Fix extra fields validation in Card component (Billing address, Koren authentication)
- Fix ExpirationDate valid state
> Card component fixes

- src/components/internal/Address/components/ReadOnlyAddress.js
- Fix small linting issue on ReadOnlyAddress
> Fix small linting issue on ReadOnlyAddress

- src/components/BcmcMobile/BcmcMobile.ts
- src/components/Swish/Swish.ts
- Fix Swish status check timeout
- Bump Swish status check timeout to 15 minutes (from 3 minutes)
- Fix Bancontact Mobile QR Code status check timeout
> Fix Swish status check timeout

- package.json
* Fixed components loading state (#143)
* Load GooglePay script automatically if not available (#138)
* QRLoader payments call onAdditionalDetails when they fail (#132)
* Enable telemetry call by default (#131)
* Fix Swish status check timeout (#153)
* Card component fixes (#142)
> Release 3.11.1

- src/components/helpers/IssuerListContainer.tsx
Fix type error in IssuerListProps
**Fixed issue**:  #158
> Add UIElementProps to IssuerListProps

- package.json
Add UIElementProps to IssuerListProps #159
> Release 3.11.2

- package.json
Handle different autoComplete formats #168
> Release 3.11.3

- playground/pages/Vouchers/Vouchers.html
- playground/pages/Vouchers/Vouchers.js
- src/components/Econtext/components/EcontextVoucherResult/EcontextVoucherResult.tsx
- src/components/Econtext/types.ts
- src/language/locales/en-US.json
- src/language/locales/ja-JP.json
Add collection institution number to EContext Voucher Result
- Added Econtext ATM result in the playground to display collection institution number
- Unit test passed
> Add collection institution number to EContext Voucher Result

- src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx
Fix incorrect data output of the Open Invoice payment methods by conditionally adding properties.
> Fix incorrect data output by conditionally adding properties.

- src/components/internal/Address/Address.test.tsx
- src/components/internal/Address/Address.tsx
- src/components/internal/Address/constants.ts
- src/components/internal/Address/utils.ts
Fix incorrect data output in the Address component by filtering empty properties
> Fix incorrect data output in the Address component by filtering empty properties

- playground/pages/OpenInvoices/OpenInvoices.html
- playground/pages/OpenInvoices/OpenInvoices.js
- src/components/Affirm/Affirm.test.tsx
- src/components/Affirm/Affirm.tsx
- src/components/Affirm/index.ts
- src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx
- src/components/index.ts
- src/components/internal/OpenInvoice/OpenInvoice.tsx
- src/components/internal/OpenInvoice/types.ts
> Include Affirm component as payment method

- package.json
- Fix incorrect data output by conditionally adding properties. #190
- Fix incorrect data output in the Address component by filtering empty properties #191
- Include Affirm component as payment method #192
- Add message to Swish to explain delay #196
> Release 3.12.0

- src/components/Giropay/Giropay.tsx
- Fix showPayButton property on GiroPay component
- `showPayButton: false` hides the pay button on the GiroPay component
> Fix showPayButton property on GiroPay component

- package.json
- Fix showPayButton property on GiroPay component #198
- Fix issue with the locale used to retrieve the datasets. #199
> Release 3.12.1

- src/components/BaseElement.test.ts
- src/components/BaseElement.ts
- src/components/PayPal/Paypal.test.ts
- Add `clientStateDataIndicator` flag
> Add clientDataIndicator flag

- src/components/ApplePay/utils.ts
- Resolve Apple Pay version only if ApplePaySession is available
> Add check for ApplePaySession availability

- package.json
- Add custom messages to component validations (#202)
- Pre-fill fields in SEPA Direct Debit Component (#211)
- Add clientDataIndicator flag (#206)
- Automatically select an ApplePay version (#204)
- Fix aria iframeTitle (#213)
- Pre-configuring aria config objects in Card component (#221)
- Add timeout to Dropin's isAvailable filter (#223)
- Fix PayPal unmount method (#224)
- Aria & a11y attributes improvements (#227)
- Fixed Card empty placeholders (#231)
> Release 3.13.0

- .github/workflows/ci-test.yml
- .github/workflows/compressed-size.yml
Add [compressed-size-action](https://github.com/marketplace/actions/compressed-size-action) to check size changes on PRs.
> Add compressed-size to our Github Actions

- package.json
- Fix personal details validation (#243)
- Fix Google Pay issues in Drop-in (#237)
> Release 3.13.1

- src/components/PayPal/types.ts
> Fix for TS2430 error

- packages/lib/config/webpack.dev.js
Fix process env variables from .env file on lib dev mode
> Fix process env variables from .env file on lib dev mode

- packages/lib/src/components/Card/triggerBinLookUp.ts
Added comment in `triggerBinLookup` clarifying what different elements in the response mean
> clarifying comment about binLookup response

- packages/playground/config/webpack.dev.js
- packages/playground/package.json
- yarn.lock
* Add adyen-web map files in playground
> Add adyen-web map files in playground

- packages/lib/src/components/ThreeDS2/components/Challenge/Do3DS2Challenge.tsx
Fix method in Do3DS2Challenge not being able to properly call this.setState
> Fix method in Do3DS2Challenge

- packages/lib/src/components/AfterPay/index.ts
- packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx
- Fix CompanyDetails validation for Afterpay B2b
- Fix import path
> Fix/Afterpay B2B validation

- packages/lib/src/components/Blik/components/BlikInput.tsx
- Add a placeholder to Blik component
> Add a placeholder to Blik component

- packages/lib/config/jest.config.js
- packages/lib/config/setupTests.ts
- packages/lib/tsconfig.json
- packages/playground/tsconfig.json
> Revert "Disable allowJs in tsconfig"

- packages/lib/package.json
- New Afterpay B2B component (#248)
- Fix for TS2430 error (#252)
- Improve README (#261)
- Fix onError callback (#297)
- Fix full width characters (#300)
- Fix props override in redirect action components (#301)
- Add a placeholder to Blik component (#306)
- Bump riskModule timeout (#314)
- Fix PayPal onCancel event not propagating the right component reference (#317)
> Release 3.14.0

- packages/playground/package.json
> Bump playground to 3.14.0

- packages/lib/package.json
- packages/playground/package.json
> Release 3.14.1

- packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx
- packages/lib/src/components/internal/OpenInvoice/types.ts
- packages/lib/src/components/internal/OpenInvoice/utils.ts
- Reduce duplicated code
- Add util function
- Improve readability
> Feature/Update OpenInvoice component to reduce duplicated code.

- packages/lib/src/components/Ach/Ach.tsx
- packages/lib/src/components/Ach/components/AchInput/AchInput.scss
- Add check on formatData method.
- Fix margin when no holdername is shown.
> Fix/ACH component formatData

- packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/PaymentMethodsResponse.ts
- packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/utils.test.ts
- packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/utils.ts
- Add util function to do more checks in the paymentMethodsResponse prop.
- Extract util functions to their own file.
- Add tests.
> Feature/Add checks for the paymentMethodsResponse

- .github/workflows/npm-publish.yml
- Copy README on publish workflow
> Copy README on publish workflow

- packages/lib/src/components/MBWay/MBWay.tsx
- packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.module.scss
- packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.tsx
- packages/lib/src/components/MBWay/components/MBWayInput/types.ts
- packages/lib/src/components/MBWay/components/MBWayInput/validate.ts
- Remove unneeded email field.
- Extract type definition to their own file.
- Align code style to other similar components.
- Delete unneeded CSS module file.
**Fixed issue**: COWEB-811
> Update MBWay component

- packages/lib/package.json
- packages/playground/package.json
- Fix Google Pay existingPaymentMethodRequired issues (#329)
- Japanese installments (#330)
- DropinComponent - add public method 'closeActivePaymentMethod' (#332)
- Update the personal details component (#333)
- Fix unsupported card error not clearing (#338)
- Update MBWay component (#339)
- Fix ACH component formatData (#340)
- Add checks for the paymentMethodsResponse (#349)
> Release 3.15.0

- packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.tsx
- packages/lib/src/components/MBWay/components/MBWayInput/types.ts
- packages/lib/src/components/MBWay/components/MBWayInput/validate.ts
- Fix MBWay validation rules to only show an error on blur
- Update interface
> Fix/MBWay validation rules and update interface.

- packages/lib/package.json
- packages/playground/package.json
- Fix MBWay validation rules and update interface (#357)
- Update translation files (#359)
- Call `validateCardInput` after `binLookup` detects a new brand (#361)
- Extend locale type definition to allow custom locales (#365)
> Release 3.15.1

- packages/lib/tsconfig.json
- Enable sourcemaps on tsconfig
> Improve sourcemaps

- packages/lib/package.json
- packages/playground/package.json
- Automatically create Apple Pay session #362
- Add extra `transactionInfo` fields to Google Pay payment request #378
- Add `commit` property to PayPal component #273 (thanks @dkatashev!)
- Add `vault` and the `showPayButton` properties to PayPal component. #392
- Improve sourcemaps #383
- Fix paymentMethodsResponse warning message #382
> Release 3.16.0

- packages/playground/config/webpack.config.js
- packages/playground/package.json
- yarn.lock
> Revert "Update Playground to Webpack 5"

- packages/lib/package.json
- packages/playground/package.json
- Fix revolving installments alignment #397
- Fix missing `name` prop for the RadioGroup component #401
- Fix empty address fieldsets being returned in the data object #403
> Release 3.16.1

- packages/lib/src/core/Context/CoreProvider.tsx
- packages/lib/src/language/Language.test.ts
- packages/lib/src/language/Language.ts
- packages/lib/src/language/utils.test.ts
- packages/lib/src/language/utils.ts
- Prepares the i18n module to load asynchronously, preparing it for future improvements like code splitting.
> Make i18n loading asynchronous

- packages/lib/src/components/Giftcard/Giftcard.tsx
- Switch Giftcard type from previous brand to the new generic type (API v65 required)
> Fix Giftcard component type

- packages/lib/package.json
- packages/playground/package.json
> Release 3.17.0

- packages/lib/src/components/GooglePay/GooglePay.test.ts
- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/GooglePay/types.ts
Old prop | New prop
-- | --
showButton | showPayButton
merchantIdentifier | merchantId
> Remove Google Pay legacy props

- packages/lib/package.json
- packages/playground/package.json
* Remove defaulting to generic 'card' type #428
* Fix Apple Pay configuration properties #445
* Fix Giropay not checking the showPayButton property #453
> Release 3.17.1

- packages/lib/src/components/ApplePay/ApplePay.tsx
- packages/lib/src/components/ApplePay/types.ts
- packages/lib/src/components/Sepa/Sepa.test.ts
- packages/lib/src/components/Sepa/Sepa.tsx
- packages/lib/src/components/Sepa/types.ts
- Update Sepa Direct Debit output payment method details
- Update Apple Pay output payment method details
> Update payment method details

- packages/lib/package.json
- packages/playground/package.json
* Fix adding and removing Korean authentication fields (#469)
* Update payment method details (#464)
* Handle errors in gift card flow (#463)
> Release 3.17.2

- packages/lib/package.json
- packages/playground/package.json
* Add new languages and update translation files #482
* Korean Cards fixes #484
* Update OpenInvoice to show the delivery address when prefilled #461
> Release 3.18.0

- packages/lib/package.json
- packages/playground/package.json
* Google pay onClick event (#489)
* Fix Google Pay amount property (#495)
> Release 3.18.1

- packages/lib/src/components/index.ts
Add primeiropay_boleto component.
> Add primeiropay_boleto component

- packages/lib/src/components/internal/FormFields/Select/Select.scss
- packages/lib/src/components/internal/FormFields/Select/Select.tsx
Support unavailable issuers on IssuerList components. Unavailable issuers will show greyed out and won't be selectable.
> Support unavailable issuers on IssuerList components

- packages/playground/tests/e2e/cards/KCP_iframes_noKCPAtStart.js
- packages/playground/tests/e2e/cards/KCP_iframes_withKCPAtStart.js
- packages/playground/tests/e2e/cards/cardUtils.js
- packages/playground/tests/e2e/cards/dualBranding.js
- packages/playground/tests/e2e/cards/kcpUtils.js
- packages/playground/tests/e2e/constants.js
Abstracting some of the kcpUtils into more general cardUtils
Test all still work
> Abstracting some of the kcpUtils into more general cardUtils

- packages/lib/src/components/QiwiWallet/QiwiWallet.tsx
- packages/lib/src/components/internal/PhoneInput/PhoneInput.scss
- packages/lib/src/components/internal/PhoneInput/PhoneInput.tsx
> CSS fixes and highlight border for invalid input

- packages/e2e/tests/cards/dualBranding/dualBranding.test.js
Testing that dual branding icons are at the correct alpha and correct disabled/active states
> Tests for brand icon alpha and disabled/active states

- packages/lib/src/components/internal/FormFields/Select/Select.tsx
- Update the disabled issuers property from `available` to `disabled`
> Update disabled issuers property

- packages/lib/package.json
- packages/lib/src/components/Card/components/CardInput/handlers.ts
- packages/lib/src/components/Card/components/CardInput/processBinLookup.ts
- packages/lib/src/components/Card/triggerBinLookUp.ts
- packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts
- packages/playground/package.json
- yarn.lock
Update master with the v3.18 branch
> Update master with v3.18

- packages/lib/src/components/Card/types.ts
- packages/lib/src/components/Dropin/types.ts
- packages/lib/src/core/Analytics/Analytics.ts
- packages/lib/src/core/Analytics/types.ts
- packages/lib/src/core/core.ts
- packages/lib/src/core/types.ts
- Add missing event types on the Card component
**Fixed issue**:  #396
> Improve card types

- packages/lib/src/components/BacsDD/components/BacsInput.tsx
Changed key used for translation on email field (to be more aligned with copy writing guidelines)
> Changed key used for translation on email field

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
Bacs Direct Debit component (#568)
Bank transfer component (#564)
primeiropay_boleto component #513
Improve Gift card error messages (#507)
Show a dropdown of countries if no country is passed in Open Invoices #571
Add onClick event to Apple Pay Component (#592)
Fix storedPaymentMethodId parameter on the onDisableStoredPaymentMethod Drop-in event (#504)
Fix issue with PayPal Credit button styles. (#545)
Fix null value issues on PaymentMethodsResponse (#505)
Autofill holderName only when holderName is enabled (#503)
Custom Card component: Set default (translated) placeholders for separate date fields (#519)
> Release 3.19.0

- packages/lib/src/components/Doku/Doku.tsx
- packages/lib/src/components/Doku/components/DokuInput/DokuInput.tsx
- packages/lib/src/components/Dragonpay/Dragonpay.tsx
- packages/lib/src/components/Econtext/Econtext.tsx
- packages/lib/src/components/Econtext/components/EcontextInput/EcontextInput.tsx
- packages/lib/src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx
- packages/lib/src/components/internal/CompanyDetails/CompanyDetails.tsx
- packages/lib/src/components/internal/CompanyDetails/utils.ts
- packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx
- packages/lib/src/components/internal/PersonalDetails/PersonalDetails.test.tsx
- packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx
- packages/lib/src/components/internal/PersonalDetails/utils.ts
- packages/lib/src/components/internal/Voucher/Voucher.scss
- packages/playground/src/pages/OpenInvoices/OpenInvoices.js
- packages/playground/src/pages/Vouchers/Vouchers.js
The personal details returns the output data in an outdated format, which is causing issues with Voucher components. This fixes this and aligns the functionality of the Company details component as well.
> Fix Personal details output format

- packages/lib/src/components/ApplePay/ApplePay.tsx
- packages/lib/src/components/ApplePay/utils.ts
- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/GooglePay/utils.ts
Implement apple pay and google pay brands for Pay By Link
To be included in upcoming commits
> Implement Apple Pay & Google Pay brands from payment methods response

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Amazon Pay component #417
* Card Component: new `onBinLookup` callback #653
* Apple Pay/Google Pay: brands from payment methods response #615
* Card component: New Bancontact bins #648
* Card component: `aria-label` iframe strings are now set in the translations files #613
* Fix personal details output in voucher components #632
> Release v3.20.0

- packages/e2e/tests/cards/binLookup/binLookup.clientScripts.js
- packages/e2e/tests/cards/binLookup/binLookup.test.js
- packages/e2e/tests/cards/utils/constants.js
- packages/e2e/tests/utils/commonUtils.js
- packages/lib/src/components/Card/Card.tsx
- packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx
- packages/lib/src/components/Card/components/CardInput/CardInput.tsx
- packages/lib/src/components/Card/components/CardInput/processBinLookup.ts
- packages/lib/src/components/Card/components/CardInput/types.ts
- packages/lib/src/components/Card/triggerBinLookUp.ts
- packages/lib/src/components/Card/types.ts
- packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.test.tsx
- packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts
- packages/lib/src/components/internal/SecuredFields/lib/core/AbstractCSF.ts
- packages/lib/src/components/internal/SecuredFields/lib/core/CSF.ts
- packages/lib/src/components/internal/SecuredFields/lib/core/utils/handleBrandFromBinLookup.ts
- packages/lib/src/components/internal/SecuredFields/lib/types.ts
- packages/playground/src/pages/Cards/Cards.js
Mostly e2e and unit tests for binLookup functionality - testing the response from the API and how it is handled
Some refactoring around types and parameter names
Old tests still pass.
New tests pass.
> Refactor and tests (unit & e2e) linked to binLookup functionality

- packages/lib/src/components/helpers/IssuerListContainer.tsx
Support fallback issuers from details on IssuerList components
> Support fallback issuers from details on IssuerList components

- packages/lib/src/components/internal/FormFields/Select/Select.scss
Applying Adyen/adyen-web#675 to master branch.
> Ensure issuer lists selected issuer icon has a height for IE11

- packages/e2e/app/config/webpack.config.js
- packages/e2e/app/src/pages/IssuerLists/IssuerLists.html
- packages/e2e/app/src/pages/IssuerLists/IssuerLists.js
- packages/e2e/tests/issuerLists/ideal/ideal.test.js
- packages/e2e/tests/pages.js
> Add iDeal e2e tests

- packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.test.tsx
- packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.tsx
- packages/lib/src/components/Card/components/CardInput/components/types.ts
- Make it possible to preselect a value.
- Show as read only when only one option is passed.
- Add tests.
- Preselect value.
- Show as read only when only one option is passed.
> Installments component improvements

- packages/e2e/tests/issuerLists/ideal/ideal.test.js
> Reenable all e2e tests

- packages/playground/src/pages/Wallets/Wallets.js
Fix Apple Pay playground demo, resolve by default
> Fix Apple Pay playground demo, resolve by default

- packages/lib/src/components/Card/types.ts
- packages/lib/src/components/UIElement.tsx
Move challengeWindowSize from UIElement to Card Element.
> Move challengeWindowSize from UIElement to Card Element

- packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx
- packages/lib/src/components/internal/OpenInvoice/utils.ts
Fix openinvoice circular dependency
> Fix openinvoice circular dependency

- packages/lib/src/components/Pix/Pix.ts
- packages/lib/src/components/Pix/index.ts
- packages/lib/src/components/index.ts
- packages/lib/src/components/internal/QRLoader/QRLoader.scss
- packages/lib/src/components/internal/QRLoader/QRLoader.tsx
- packages/lib/src/components/internal/QRLoader/types.ts
- packages/lib/src/language/locales/en-US.json
- packages/lib/src/language/locales/pt-BR.json
Add the new PIX Component for Brazil.
> PIX component

- packages/lib/.eslintrc.js
- packages/lib/config/postcss.config.js
- packages/lib/config/webpack.config.js
- packages/lib/package.json
- packages/lib/src/components/ThreeDS2/components/utils.ts
- packages/lib/src/core/core.ts
- yarn.lock
* Adds `eslint-loader` back on dev mode and build.
* Add stylelint alerts.
> Re-enable eslint-loader

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* PIX component (#669)
 
* Improvements on bin lookup functionality (#692, #707)
* Ensure issuer lists selected issuer icon has a height for IE11 (#677, #675)
* PayPal component: add the onShippingChange event (#710)
* Improvements on installments functionality (#686)
* Fix test script on Windows environments #696
Adyen Web v3.21.0 requires API v66 or later.
> Release 3.21.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Change default 3DS2 challenge iframe sizing (#620)
> Release 3.21.1

- package.json
Fix main workspace e2e test command
`yarn test:e2e` works in the main workspace.
> Fix main workspace e2e test command

- packages/e2e/tests/cards/dualBranding/dualBranding.clientScripts.js
- packages/e2e/tests/cards/dualBranding/dualBranding.dropin.test.js
- packages/lib/src/components/Card/triggerBinLookUp.ts
- packages/lib/src/components/Dropin/Dropin.tsx
- packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts
- packages/lib/src/components/ThreeDS2/components/utils.ts
- packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
Fixes so v2 binLookup and 3DS2 work on v4
Tests all run
> Fix/v4 binLookup & 3DS2

- packages/lib/config/rollup.config.js
- packages/lib/package.json
- packages/lib/src/core/utils.ts
- yarn.lock
Enable eslint in `rollup.config.js`
- Lints on build
- Lints on watch mode
> (v4) Enable eslint rollup

- packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Bumped sf version to 3.3.1
All tests, unit & e2e, pass
**Fixed issue**:  FOC-42352
> Bumping sf version to 3.3.1

- packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.tsx
- packages/lib/src/components/QiwiWallet/QiwiWallet.tsx
- packages/lib/src/components/internal/PhoneInput/PhoneInput.scss
- packages/lib/src/components/internal/PhoneInput/PhoneInput.tsx
Changes the phone field labels to "Mobile number" on the Qiwi Wallet and MBWay components.
> Fix phone input labels

- packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx
Fix Gift card pin field error outline
> Fix Gift card pin field error outline

- packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx
Fix select button references not being applied properly.
> Fix Select button references

- packages/lib/src/components/Boleto/components/BoletoInput/BoletoInput.tsx
Align validation errors on Boleto Bancario with OpenInvoice
The `onChange` `state.errors` parameter returns the correct structure.
> Align Boleto Bancario validation errors

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- The origin key is no longer supported. If you haven't already, [switch to using the client key](https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key) for client-side authentication.
- Drop-in now only accepts props related to itself.
- Configuration at the component level overrides all other configuration.
- We removed some deprecated props.
- You must now configure aria labels using translation fields.
- For NPM installations, we now also release ES and CJS format bundles. This is in addition to the UMD format bundle released with previous versions.
- You can now configure action components by action `type` inside `paymentMethodsConfiguration`.
- The `onChange` event now also returns error and validation information. The …
> Release 4.0.0

- packages/lib/src/utils/constants/currency-decimals.ts
Add IQD to the list of 3 decimal currencies.
> Fix IQD currency decimals

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* We added new Apple Pay button types. For a full list of supported Apple Pay button types, refer to Button configuration (#830)
* For Google Pay, you can now use the `buttonSizeMode` and `buttonLocale` configuration properties. For more information, refer to Button options (#823)
* Amazon APB flow (#839)
* The placeholder values for card fields are now only read from translation fields. Configuring placeholder values inside the Card Component is no longer supported. (#824)
* Stored cards can now be configured in the `paymentMethodsConfiguration` object (#829)
* Added a missing CSS file export in the npm package (#837)
* Fixed an issue where the promise dependency could be missing when using the ES format bundle (#825)
* When pasting a dual-branded card number over a previously entered …
> Release 4.1.0

- packages/e2e/tests/bacsDD/bacs.test.js
- packages/e2e/tests/cards/branding/branding.test.js
- packages/playground/src/pages/Vouchers/Vouchers.js
Changed credentials for BacsDD so /payments will succeed and e2e test passes
e2e test passes again
> Changed credentials for BacsDD so payments and tests work

- packages/lib/src/components/AmazonPay/AmazonPay.tsx
- packages/lib/src/components/AmazonPay/types.ts
- packages/lib/src/components/AmazonPay/utils.ts
- Add a `design` property.
- Add the publicKeyId when calling the `getCheckoutDetails` endpoint.
> Update Amazon Pay component

- packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx
> Enable CardInput tests

- packages/lib/src/components/internal/SecuredFields/lib/core/utils/processBrand.ts
> Removed imaginary property

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Add positionHolderNameOnTop for the Card component #891
* Update Amazon Pay component #880
* Add Brazilian social security number to Card Component #870 
* Add browserInfo to Google Pay component #847
* Brand (in PaymentMethod data) is reset after a failed binLookup #874 
* Apply sorting rules to brands returned by binLookup #873
* Fix IssuerList components data attribute when state is empty #850
* Upped SecuredFields version to `3.4.1`
> Release 4.2.0

- packages/playground/src/pages/SecuredFields/SecuredFields.js
Fixed SecuredFields playground example so it works with the new 3DS2 flow in v67
All four 3DS2 flows (redirect, frictionless, full, challenge-only) work
> SecuredFields playground - works with new 3DS2 (v67) flow

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Disable pay button while on loading state (#915)
* Fix Card holder name focus lost when typing on the field (#920)
> Release 4.2.1

- packages/lib/src/components/Dropin/components/status/Error.tsx
- packages/lib/src/components/Dropin/components/status/Success.tsx
- packages/lib/src/utils/get-image.test.ts
- packages/lib/src/utils/get-image.ts
- Replace status success/error images with animated versions.
- Remove unused special config for non-svg images.
> Animate Drop-in final status

- .github/workflows/ci-test.yml
- package.json
- packages/lib/src/components/Card/types.ts
- Fix a missing type import.
- Add `type-check` script to the parent package.json file.
- Add type-check Github action.
- Type check does not throw any errors.
**Fixed issue**:  #952
> Fix missing type import

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- Fix Boleto not showing the state field (#951)
- Fix missing type import (#954)
> Release 4.2.2

- packages/e2e/package.json
- packages/lib/package.json
- packages/lib/src/polyfills.ts
- packages/playground/config/polyfills.js
- packages/playground/package.json
- yarn.lock
- Fixes Promise polyfill on IE11
- Replaces the `promise` dependency with `core-js`
> Fix promise polyfill

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 4.2.3

- packages/lib/src/utils/useForm/reducer.ts
Fix initial validation on a `useForm` form.
Default data is properly validated.
> Fix defaultData validation on the useForm hook

- packages/lib/src/components/AmazonPay/components/AmazonPayComponent.tsx
- packages/lib/src/components/AmazonPay/components/OrderButton.tsx
- packages/lib/src/components/AmazonPay/types.ts
Update the Amazon Pay component to pass the `publicKeyId` in the Update Checkout Session call.
> Add publicKeyId to the Update Checkout Session request

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Minimum expiry date (#984)
* Animate Drop-in final status (#942)
* Fix prefill data validation (#971)
* BankTransfer showEmailAdress flag (#968)
* AmazonPay: Add publicKeyId to the Update Checkout Session request (#980)
* Address component optional fields validation (#982)
* Fix double onSubmit call on Google Pay when using a custom button (#985)
> Release 4.3.0

- packages/e2e/app/config/webpack.config.js
- packages/e2e/app/src/pages/Vouchers/Vouchers.html
- packages/e2e/app/src/pages/Vouchers/Vouchers.js
- packages/e2e/tests/pages.js
- packages/e2e/tests/vouchers/boleto/boleto.test.js
- Add Vouchers page for E2E tests.
- Add E2E for Boleto. 
Tested with and without entering an email address.
> Add E2E for Boleto component

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Added regex for rupay for initial, internal, brand recognition #999
* Upped SecuredFields version to 3.5.1 to incorporate fix for IE11 with `Number.isNaN` #999
> Release 4.3.1

- packages/lib/src/components/Ach/components/AchInput/components/AchSFInput.tsx
- packages/lib/src/components/Ach/components/AchInput/components/AchSecuredFields.tsx
- packages/lib/src/components/Blik/components/BlikInput.tsx
- packages/lib/src/components/Card/components/CardInput/CardInput.scss
- packages/lib/src/components/Card/components/CardInput/components/CVC.tsx
- packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx
- packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx
- packages/lib/src/components/Card/components/CardInput/components/KCPAuthentication.tsx
- packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.tsx
- packages/lib/src/components/Dropin/components/DropinComponent.module.scss
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss
- packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx
- packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.tsx
- packages/lib/src/components/Sepa/components/IbanInput/IbanInput.tsx
- packages/lib/src/components/internal/Button/Button.scss
- packages/lib/src/components/internal/FormFields/Checkbox/Checkbox.scss
- packages/lib/src/components/internal/FormFields/Field/Field.tsx
- packages/lib/src/components/internal/FormFields/Field/types.ts
- packages/lib/src/components/internal/FormFields/FormFields.scss
- packages/lib/src/components/internal/FormFields/Select/Select.module.scss
- packages/lib/src/components/internal/FormFields/Select/Select.scss
- packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx
- packages/lib/src/components/internal/PhoneInput/PhoneInput.scss
- packages/lib/src/components/internal/QRLoader/QRLoader.scss
- packages/lib/src/components/internal/Spinner/Spinner.scss
Improve RTL support across all components and Drop-in.
> Improve RTL support

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Improved RTL support (#933)
* Added Arabic (international) language support (#1006)
* Fix order-status call on partial payments flow (#1027)
* Fix onSubmit component reference on Google Pay component (#1028)
> Release 4.4.0

- packages/lib/src/components/Card/components/CardInput/CardInput.scss
Fix Amex cards showing two CVC hints.
Both Amex and not Amex cards.
> Fix Amex CVC hint showing both location indicators

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Allow custom icons and custom brand icons (#1039, #1058)
* Increase max gift card length from 22 to 32 digits (#1040)
* Fix Amex CVC hint showing both location indicators (#1038)
* Add adyen-web `package.json` to exports (#1056)
> Release 4.5.0

- packages/lib/config/rollup.config.js
Enable ES Module output sourcemaps on dev mode
> Enable ES Module output sourcemaps on dev mode

- packages/playground/src/pages/Dropin/Dropin.js
- packages/playground/src/pages/Wallets/Wallets.js
> Update Playground pages to handle 3DS2 actions when paying with Amazon Pay

- packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx
- packages/lib/src/components/internal/FormFields/Select/components/SelectListItem.tsx
Automatically hide any images that failed to load on the Select component.
- Issuers without an image don't show a broken image on the IssuerList component.
> Fix broken images on IssuerList component

- packages/lib/src/components/AmazonPay/components/AmazonPayComponent.tsx
- packages/lib/src/components/PayPal/Paypal.tsx
- packages/lib/src/components/PayPal/components/PaypalButtons.tsx
- packages/lib/src/components/PayPal/components/PaypalComponent.tsx
- packages/lib/src/components/PayPal/constants.ts
- packages/lib/src/components/PayPal/defaultProps.ts
- packages/lib/src/components/PayPal/types.ts
- packages/lib/src/utils/Script.ts
- Improve PayPal component error handling. Add constants file.
- Make it possible to block the PayPal Credit button.
- Update Script util to not add the same script multiple times.
- Make it possible to mount multiple PayPal components in the same page.
- Update how Amazon Pay loads its script to align with PayPal component.
> PayPal component updates

- packages/lib/src/components/Dropin/components/PaymentMethod/OrderPaymentMethods.tsx
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodIcon.tsx
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/UIElement.tsx
- Update Google Pay icon
- Remove outline around the Google Pay icon on Drop-in
**Fixed issue**:  #1091
> Update Google Pay icon

- packages/lib/src/components/ApplePay/ApplePay.tsx
Fix the double `onSubmit` call when using a custom pay button with Apple Pay on the Drop-in
- `onSubmit` is called once on all the following scenarios
- Drop-in
- Components
- Drop-in with a custom pay button
- Components with a custom pay button
Fixes: #734
> Fix double submit on Apple Pay when using a custom button

- packages/playground/package.json
- yarn.lock
- Update sass-loader dependency on `playground` package
> Update sass-loader dependency

- packages/lib/src/components/internal/Address/constants.ts
> Add Australian address to the list of specifications

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Automatically set loading status on submit #1128
* Add CarteBancaire support to Apple Pay component #1129
* Add Australian address to the list of specifications #1150
> Release 4.7.0

- packages/lib/src/components/SecuredFields/SecuredFields.tsx
- packages/lib/src/components/internal/SecuredFields/binLookup/extensions.ts
- packages/playground/src/pages/SecuredFields/securedFields.config.js
Cleanup types for customCard re. binLookup fny
> Cleanup types for customCard re. binLookup fny

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* Fixed card holder name validation - only reject digits (#1189)
* Improve accessibility on dropdown element (#1182)
* Remove unhandled promise on Google Pay (#1163)
* Stop adding classNameModifiers as attribute to inputs (#1186)
> Release 4.7.1

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 4.7.2

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* #1226
* #1232
* #1233
* #1234
> Release 4.7.3

- packages/lib/src/core/Analytics/Analytics.ts
- packages/lib/src/core/Analytics/types.ts
- packages/lib/src/core/Services/collect-id.ts
- packages/lib/src/core/Services/post-telemetry.ts
- Update path to use the v2.
- Send experiments array.
> Update Analytics module to use the v2 endpoint

- packages/lib/src/components/Klarna/KlarnaPayments.tsx
- packages/lib/src/components/index.ts
Fix klarna_account and klarna_paynow in combination with `useKlarnaWidget`
> Fix klarna_account and klarna_paynow

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
* #1250
* #1253
* #1256
* #1206
* #1261
> Release 4.7.4

- packages/lib/src/components/internal/FormFields/Select/Select.tsx
Fixes dropdown click when inside a web component.
* Selecting a iDeal issuer inside a web component version of Dropin
* Selecting a iDeal issuer on a normal test page
#906
> Fixes dropdown on Web Components

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 4.7.5

- .github/CODEOWNERS
> Adding Antonio to codeowners

- packages/lib/src/components/AmazonPay/AmazonPay.tsx
- packages/lib/src/components/AmazonPay/components/AmazonPayComponent.tsx
- packages/lib/src/components/AmazonPay/components/OrderButton.tsx
- packages/lib/src/components/AmazonPay/types.ts
Adding the region parameter to the requests we do to our internal endpoints.
> Add region parameter to Amazon Pay requests.

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 4.8.0

- .github/CODEOWNERS
> Added Guilherme to CODEOWNERS

- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss
Small fixes to button styles after a11y update
> Fixes button css after a11y fixes

- packages/lib/src/components/internal/FormFields/InputText.tsx
Adds aria required to text inputs that are required
Tested with holderNameRequired on and off
> Fixes aria-required on required text inputs

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1339 
- #1333 
- #1342 
- #1328
> Release v5.2.0

- packages/e2e/package.json
- packages/e2e/tests/_models/CardComponent.page.js
- packages/e2e/tests/_models/Dropin.page.js
- packages/e2e/tests/cards/Bancontact/bancontact.visa.test.js
- packages/e2e/tests/cards/kcp/startWithKCP/startWithKCP.test.js
- packages/e2e/tests/cards/kcp/startWithoutKCP/startWithoutKCP.test.js
- packages/playground/src/pages/SecuredFields/SecuredFields.html
- packages/playground/src/pages/SecuredFields/securedFields.config.js
- yarn.lock
- e2e DropinPage model created
- bancontact.visa.test converted to use this and failing test fixed
bancontact.visa.test passes again
> bancontact.visa.test fixed

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1353 
- Fixed bug when tabbing between card input fields in Firefox
Related issues:
#1347 
#1346 
#1227
> Release v5.2.1

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.2.2

- packages/lib/src/components/PayPal/Paypal.tsx
- packages/lib/src/components/PayPal/components/PaypalButtons.tsx
- packages/lib/src/components/PayPal/components/PaypalComponent.tsx
- packages/lib/src/components/PayPal/types.ts
Add support for the intent type `tokenize`.
> Add support for the PayPal intent tokenize

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1311 
- #1354 
- #1374 
- #1370 
- #1382
> Release 5.3.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1343 
- #1384  (thanks to @jonlambert)
- #1407
- #1378
- #1418
> Release 5.4.0

- packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Upped securedFields version to 3.7.3
All tests pass
> Upped sf version to 3.7.3

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.5.0

- packages/e2e/app/src/pages/Cards/Cards.js
- packages/e2e/app/src/pages/CustomCards/CustomCards.js
- packages/e2e/app/src/pages/Dropin/Dropin.js
Changed imports for AdyenCheckout & adyen.css in test pages to use the `es` bundle.
This allows the tests to work against the latest build files again
All e2e tests pass
> Changed imports for AdyenCheckout & adyen.css in test pages

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.6.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
-  IE11 fix: Polyfill for Array.fill for credit card securedFields ( #1443 )
> Release 5.6.1

- packages/e2e/app/src/pages/DropinSessions/DropinSessions.js
- packages/e2e/app/src/pages/GiftCards/GiftCards.js
- packages/e2e/app/src/pages/IssuerLists/IssuerLists.js
- packages/e2e/app/src/pages/OpenInvoices/OpenInvoices.js
- packages/e2e/app/src/pages/Vouchers/Vouchers.js
- packages/playground/src/pages/Cards/Cards.js
- packages/playground/src/pages/Components/Components.js
- packages/playground/src/pages/Dropin/manual.js
- packages/playground/src/pages/Dropin/session.js
- packages/playground/src/pages/GiftCards/GiftCards.js
- packages/playground/src/pages/Helpers/Helpers.js
- packages/playground/src/pages/IssuerLists/IssuerLists.js
- packages/playground/src/pages/OpenInvoices/OpenInvoices.js
- packages/playground/src/pages/QRCodes/QRCodes.js
- packages/playground/src/pages/Result/Result.js
- packages/playground/src/pages/SecuredFields/SecuredFields.js
- packages/playground/src/pages/Vouchers/Vouchers.js
- packages/playground/src/pages/Wallets/Wallets.js
> Fixes css imports for dev

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.6.2

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.7.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1475 
- #1441 
- #1487 
- #1448 
- #1367 (thanks to @d99iel)
- #1484
> Release 5.8.0

- packages/lib/src/components/internal/IssuerList/IssuerButtonGroup/IssuerButton.scss
- Fixing CSS on Safari for highlighted issuers
Tested across browsers
**Fixed issue**:  COWEB-1054
> CSS fix for highlighted issuers on Safari

- packages/lib/src/components/AmazonPay/components/AmazonPayComponent.tsx
- packages/lib/src/components/AmazonPay/components/OrderButton.tsx
- packages/lib/src/components/AmazonPay/types.ts
- packages/lib/src/components/AmazonPay/utils.ts
- packages/playground/src/config/commonConfig.js
- packages/playground/src/pages/Wallets/Wallets.js
This ticket adds support for recurring payments via AmazonPay. For this we add support for 2 new properties, `chargePermissionType` and `recurringMetadata`.
- A payment was made on TEST in `Recurring` mode
- A payment was made on TEST with `OneTime` mode
> AmazonPay Recurring Payments

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1466 
- #1507 
- #1506 
- #1502 
- #1501
- #1513 
- #1511 
- #1499 (thanks to @astiskala)
> Release 5.9.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1517
- #1526 
- #1522 
- #1521 
- #1520
> Release 5.10.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- https://github.com/Adyen/adyen-web/pull/1539
- https://github.com/Adyen/adyen-web/pull/1537
- https://github.com/Adyen/adyen-web/pull/1536
> Release 5.12.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.13.1

- packages/e2e/tests/bacsDD/bacs.test.js
Fixed e2e test that was failing because of secondary button styling changes
Test passes
> Fixed e2e test that was failing because of secondary button styling changes

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.14.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
-  #1593 
- #1581 
- #1596 
Related issues: #1592
> Release 5.15.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.16.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.16.1

- packages/lib/src/components/UIElement.tsx
Fixes issue where components would stay in the `loading` state, after a rejected action in `beforeSubmit` callback. 
- Tested `beforeSubmit` callback with and without rejection
> fixes state reset when beforeSubmit is rejected

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
-
- 
- #1619 
- #1625 
- #1620 
- #1618 
- #1609 (thanks to @diego9497)
-
> Release 5.16.2

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.17.0

- packages/lib/src/components/GooglePay/utils.ts
- packages/lib/src/core/Environment/Environment.ts
- packages/lib/src/core/types.ts
* Adds `live-in` to the list of supported environments
> Adds new live-in environment

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1631 
- #1649 
- #1644 
- #1648 
- #1642
> Release 5.18.0

- .github/workflows/npm-publish.yml
- Adding LICENSE file in the published package
**Fixed issue**:  #1636
> Adding LICENSE file in the published package

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.19.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1667 
- #1668 
- #1666 
- #1665
> Release 5.20.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1660
- #1669
- #1679
- #1676
- Fixes for issue #1634 whereby you could still enter a 4 digit cvc even when Amex is not a supported brand
- Upped SecuredFields version to 4.1.1
> Release 5.21.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1645
- #1681  (thanks to @Spea)
- #1684
> Release 5.22.0

- packages/lib/src/components/internal/Button/Button.tsx
- packages/lib/src/components/internal/PayButton/PayButton.test.tsx
- packages/lib/src/components/internal/PayButton/utils.ts
Added unit tests for the PayButton to check it is only rendering the secondaryAmount when it should
They pass
> Unit tests for the PayButton re. rendering the secondarAmount

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1701 
- #1700 
- #1704
- #1698 (thanks to @mvannes )
> Release 5.23.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1714 
- Bumped securedFields version to 4.2.0
- #1715
> Release 5.23.1

- .github/CODEOWNERS
> Adding Job to CODEOWNERS file

- packages/e2e/tests/cards/kcp/startWithKCP/startWithKCP.test.js
- packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts
- packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts
- packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
- packages/lib/src/components/internal/SecuredFields/lib/securedField/AbstractSecuredField.ts
- packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.ts
Bumping securedField version and adding check for if securedFields iframe loads new content
All tests pass
> Bumping securedField version

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1720 
- #1724 
- #1730 
- #1729
> Release 5.24.0

- .github/workflows/ci-test.yml
- .github/workflows/coveralls.yml
- .github/workflows/npm-publish.yml
- Updating workflows to use node 14
> Updating git workflows to use node 14

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
#1721
#1732 
Accessibility improvements:
#1744 
#1745
> Release 5.25.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1750 
- #1754 
- #1763 
- #1753
- #1759 
- #1752
> Release 5.26.0

- packages/lib/src/components/GooglePay/GooglePay.tsx
Fixes bug with Google Pay where errors during submit where throwing an exception instead of just triggering onError.
- Tested that errors where triggering properly
- Check if no code depended on the rejection
#1532
> fixes google pay submit() error handling

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
#1787 
#1782 
Upped SecuredFields version to 4.3.1
> Release 5.28.0

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.28.1

- packages/lib/src/components/index.ts
In an effort to add some order to an increasingly chaotic list of payment methods - they have been grouped alphabetically by type
> Group PMs in components.index.ts by type

- README.md
- Adding repository header image
> Adding Github header image

- packages/lib/src/components/Card/components/ClickToPay/services/sdks/config.ts
- Updating Visa 3rd party SDK URL
- Updating Visa configuration
> Click to Pay - Updating Visa SDK URL

- packages/lib/src/components/PayNow/PayNow.test.ts
- packages/lib/src/components/PayNow/PayNow.ts
- packages/lib/src/components/PayNow/config.ts
- packages/lib/src/components/PayNow/index.ts
- packages/lib/src/components/index.ts
- packages/playground/src/pages/QRCodes/QRCodes.html
- packages/playground/src/pages/QRCodes/QRCodes.js
- packages/server/api/payments.js
Added the QR code component for Paynow, couldn't test the full flow yet.
Tested that the QR code shows and fails when the countdown runs out.
> Added QR code component for Paynow

- packages/playground/src/pages/QRCodes/QRCodes.html
- packages/playground/src/pages/QRCodes/QRCodes.js
When merging Paynow and Promptpay I made a mistake resolving the merge-conflicts, this PR fixes that.
> Fixed Promptpay and Paynow post merge-conflict error

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1821 
- #1822 
- #1788 
- #1825
- #1831
> Release 5.29.0

- .github/dependabot.yml
Removing dependabot configuration
> Removing dependabot configuration

- packages/lib/src/components/Dropin/Dropin.tsx
- packages/lib/src/components/Dropin/types.ts
- packages/playground/src/pages/Dropin/manual.js
- packages/playground/src/pages/Dropin/session.js
- Added support for tx 'googlepay' as instant payment method
**Fixed issue**:  COWEB-1151
> Added support for tx 'googlepay' as instant payment method

- packages/lib/src/components/DuitNow/DuitNow.test.ts
- packages/lib/src/components/DuitNow/DuitNow.ts
- packages/lib/src/components/DuitNow/config.ts
- packages/lib/src/components/DuitNow/index.ts
- packages/lib/src/components/index.ts
- packages/playground/src/pages/QRCodes/QRCodes.html
- packages/playground/src/pages/QRCodes/QRCodes.js
> Added DuitNow QR Code loader

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.30.1

- renovate.json
Configuring Renovate:
- Max of concurrent PR's set to 5
- Stability days set to 21
- Add label 'dependencies' in the created PR's
> Configuring Renovate

- renovate.json
> Renovate - Fixing labels config

- packages/e2e/package.json
- packages/lib/package.json
- packages/lib/src/utils/get-process-message-handler.test.ts
- packages/playground/package.json
- #1923 
- #1925 
- #1918 
- #1919 
- #1920 
- #1921 
- #1924
- #1906 
- #1907 
- #1922
> Release 5.31.0

- .github/workflows/validate-remote-assets.yml
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1929  
- #1930 
- #1867 
- #1928
> Release 5.31.1

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.31.2

- renovate.json
- Fixing renovate to ignore certain paths
> Renovate: Fixing ignored paths

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.31.3

- packages/lib/src/components/OnlinebankingPL/index.ts
- Removed flag that was hiding issuer logos for online banking PL
> Enabling issuer logos for Online Banking PL

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.32.0

- packages/lib/src/components/PayPal/config.ts
Updating client ID used for the `sandbox` environment
> PayPal - Updating sandbox client ID

- packages/lib/src/components/internal/SecuredFields/lib/CSF/initCSF.test.tsx
- packages/lib/src/components/internal/SecuredFields/lib/CSF/initCSF.ts
- packages/lib/src/components/internal/SecuredFields/lib/utilities/logger.ts
Added unit tests for `initCSF`
Increases test coverage from 1 - 2% (depending on which metric you consider)
> Added unit tests for initCSF.ts

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #1975 
- #1980 
- #1974 
- #1968 
- #1979
> Release 5.33.0

- README.md
I was testing the project and noticed that the readme does not have the build step. I thought it was cool to add
> Adding build step

- packages/lib/src/core/Analytics/Analytics.test.ts
- packages/lib/src/core/Analytics/Analytics.ts
- packages/lib/src/core/Services/analytics/post-telemetry.ts
- Adding amount currency and value to telemetry logging
**Fixed issue**:  COWEB-1193
> Telemetry - Adding amount currency and value

- packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx
- packages/lib/src/components/Card/components/CardInput/CardInput.tsx
- packages/lib/src/components/Card/components/CardInput/types.ts
- packages/lib/src/components/Card/types.ts
- Removing installment options for Debit cards
- Added unit tests
**Fixed issue**:  COWEB-1178, #1882
> Removing installment options for Debit Cards

- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.35.0

- .github/workflows/npm-publish.yml
> Updating npm-publish token

- packages/e2e-playwright/app/src/pages/Cards/Cards.js
- packages/e2e-playwright/app/src/pages/IssuerLists/IssuerLists.js
- packages/e2e-playwright/package.json
- packages/e2e-playwright/tests/issuerList/issue-list.spec.ts
- yarn.lock
- The project was using wrong adyen-web library version
- The test page files are now loading from 'es' folder, which is the one that output new files after every change in the lib
> Playwright - Fixing adyen-web version

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #2027 
- #1993 
- #2030 
- #2028
- #2033
> Release 5.36.0

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #2053
- #2044 
- #2043 
- #1937
> Release 5.37.0

- packages/lib/src/components/ApplePay/utils.ts
We recently implemented ApplePay for eftpos, and we need to have this in merchant app for testing. Please reach out to walid.sewaify@adyen for any enquiries
> ApplePay - Adding support for txVariant eftpos_australia

- .github/workflows/e2e.yml
Enabled the artifact storing action after e2e tests
> Fix: Store e2e artifacts under any circumstance

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.39.1

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.40.0

- .github/workflows/coveralls.yml
- .github/workflows/e2e.yml
- .github/workflows/npm-publish.yml
- .github/workflows/unit-tests.yml
There's a bug in node 18.16 where it's throwing type error:
```
TypeError: Cannot redefine property: window
```
and
```
TypeError: Cannot redefine property: crypto
```
This seems to only happen on node 18.16 so we will pin this version until error is solved. We should retry in a couples of weeks. https://github.com/nodejs/node/issues/47563
Tests failing.
> fixes tests failing because of cannot redefine property

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.41.0

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #2136
- #2133
- #2131
- #2141
- #2137
> Release 5.42.0

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> Release 5.42.1

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #2138 
- #2163 
- #2157 
- #2162
> Release 5.43.0

- packages/lib/src/core/types.ts
Updates CoreOptions to also have onOrderCancel. Related to #1987 
- Run elslint and checked with existing typings
> fix: Add onOrderCancel to CoreOptions

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
- #2169 
- #1987
- #2180
- #2187 
- #2193
- #2166 
- #2188
> Release 5.43.1

- .github/CODEOWNERS
- .github/workflows/codeql-analysis.yml
- .github/workflows/coveralls.yml
- .github/workflows/unit-tests.yml
- .github/workflows/validate-remote-assets.yml
- README.md
After renaming the top level branch from `master` to `main`...
- update `workflows` files that referenced `master` (or '@master`) to point to `main` (or `@main`)
Also, remove Job Sturm from CODEOWNERS
> update workflows after renaming branch master to main

- packages/lib/src/components/BcmcMobile/BcmcMobile.test.ts
- packages/lib/src/components/DuitNow/DuitNow.test.ts
- packages/lib/src/components/PayNow/PayNow.test.ts
- packages/lib/src/components/PromptPay/PromptPay.test.ts
- packages/lib/src/components/WeChat/WeChat.test.ts
- packages/playground/src/pages/QRCodes/QRCodes.html
- packages/playground/src/pages/QRCodes/QRCodes.js
- packages/playground/src/pages/QRCodes/QRCodes.scss
- packages/playground/src/services.js
Fixed test descriptions for qrCode comps
Improved playground page mechanism for making /payment request.
**Relates to previous PR**:  #2207
> V6 fix/fixed test descriptions for qr codes

- packages/lib/config/rollup.base.config.js
- packages/lib/config/rollup.config.js
- packages/lib/config/rollup.dev.config.js
- packages/lib/package.json
> refactor: split rollup config

- .changeset/strange-clouds-appear.md
- packages/lib/src/components/internal/QRLoader/QRLoader.tsx
- packages/lib/src/utils/useAutoFocus.ts
- Turn on the screen reader, pay with the QR code, the `Scan QR code` text should be focused and announced by the screen reader.
**Internal Instance ID**: 2049207797
> refactor: autofocus on the qr code title

- package.json
- packages/lib/package.json
Workaround solution - Move "@adyen/adyen-web-server": "1.0.0", to the root package json
> fix: work around to fix changeset

- .changeset/polite-crabs-rest.md
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
We don't need this anymore and causes the screen reader to read this information twice. 
> Removes arialabelledby from PaymentMethodItem

- .changeset/swift-walls-sip.md
- packages/lib/src/components/Card/components/CardInput/components/CVCHint.tsx
- packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodName.tsx
- packages/lib/src/components/internal/FormFields/Field/Field.tsx
There was some missuse of markup, mainly divs inside buttons/spans. This fixes it.
This was tested using https://dequeuniversity.com/validator Bookmarklet on the Dropin page of the playground.
Fixes: 2047873780
> Fixes HTML markup on some divs and spans

- packages/lib/src/components/types.ts
Fixes missing result code typings. Mainly 'Refused'.
#2235
> Fixes missing results codes

- packages/lib/storybook/stories/Container.tsx
- packages/lib/storybook/stories/wallets/ApplePay.stories.tsx
- packages/lib/storybook/stories/wallets/ApplePayExpress.stories.tsx
- Adding ApplePay examples to Storybook
> ApplePay Express - Adding examples to Storybook

- .changeset/fifty-days-lie.md
Add changeset for ResultCode typings fix (#2284) 
> Add changeset for ResultCode typings fix

- .changeset/proud-berries-smile.md
Added missing changeset file for #2292
> Added missing changeset for #2292

- .changeset/polite-camels-remember.md
Adds changeset for #2233. Also covers the changes in #2291. 
> Add changeset for remove renderFormField #2233

- .changeset/long-taxis-drop.md
- packages/lib/src/components/internal/StoreDetails/StoreDetails.test.tsx
- packages/lib/src/components/internal/StoreDetails/StoreDetails.tsx
The objective of this change is to revert the default value of StoreDetails.
#2304
> Fix stored details default value

- .changeset/wicked-flowers-prove.md
- packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx
Fix personalDetails classNameModifiers for dateOfBirth.
All tests passed.
> fix(personalDetails): classNameModifiers for dateOfBirth

- packages/lib/storybook/stories/wallets/ApplePayExpress.stories.tsx
- packages/lib/storybook/stories/wallets/GooglePayExpress.stories.tsx
- yarn.lock
Returning Promise based result instead of static data, in order to align with our documentation
> Storybook - Adjusted GooglePay/ApplePay express stories

- packages/lib/src/components/Giftcard/Giftcard.test.tsx
- packages/lib/src/components/MealVoucherFR/MealVoucherFR.test.tsx
Some test coverage is added to MealVoucher and GiftCard component.
Result of Coverage report:
```     
src/components/Giftcard                                           |   81.81 |    64.28 |   88.88 |      84 |                   
Giftcard.tsx                                                     |   81.81 |    64.28 |   88.88 |      84 | 56-57,67-68,73-80 
```
```
components/MealVoucherFR                                 |     100 |      100 |     100 |     100 |                            
MealVoucherFR.tsx                                       |     100 |      100 |     100 |     100 |                            
components/MealVoucherFR/components                      |   85.71 |       50 |   66.66 |   85.71 |      
``` 
See tests.
> Feat: adds test coverage to Gift Cards and MealVoucher

- packages/lib/storybook/stories/dropin/Dropin.stories.tsx
- packages/lib/storybook/stories/dropin/customization.scss
Add a small example to restyle the drop-in component
> refactor: add dropin style customization story

- packages/lib/src/components/ApplePay/ApplePay.tsx
- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/UIElement.tsx
- packages/lib/src/components/helpers/IssuerListContainer.tsx
- packages/lib/src/components/internal/Address/components/AddressSearch.tsx
- packages/lib/src/components/internal/Address/types.ts
- packages/lib/src/components/internal/Address/utils.ts
- packages/lib/src/components/internal/FormFields/Select/Select.tsx
- packages/lib/src/components/internal/FormFields/Select/types.ts
- packages/lib/src/components/internal/IssuerList/IssuerButtonGroup/IssuerButtonGroup.tsx
- packages/lib/src/components/internal/IssuerList/IssuerList.test.tsx
- packages/lib/src/components/internal/IssuerList/IssuerList.tsx
- packages/lib/src/components/internal/IssuerList/types.ts
- packages/lib/src/core/Analytics/Analytics.test.ts
- packages/lib/src/core/Analytics/Analytics.ts
- packages/lib/src/core/Analytics/analyticsPreProcessor.ts
- packages/lib/src/core/Analytics/constants.ts
- packages/lib/src/core/Analytics/types.ts
- packages/lib/src/core/Analytics/utils.ts
- packages/lib/src/utils/debounce.ts
Adding the analytics events for iDeal (defined as the MVP)
| Data point | Component | Status |
| --- | --- | --- |
| iDeal featured issuer tile selected | iDeal | ✅  | 
|List opened | iDeal |  ✅  |
|List item selected | iDeal |  ✅  |
|Search usage (dropdown or list) | iDeal | ✅ |
------
**Relates to issue:** #2521
> Feature/using checkoutanalytics mvp iDeal

- packages/lib/storybook/config/paymentsConfig.ts
- packages/lib/storybook/helpers/checkout-handlers.ts
- packages/lib/storybook/stories/helpers/RedirectResultContainer.tsx
Fix the storybook showing result after redirection
> Fix the storybook showing result after redirection

- .github/workflows/codeql-analysis.yml
- .github/workflows/npm-publish.yml
Update GitHub action for v6 and prerelease
> Update GitHub action for v6 and prerelease

- packages/lib/src/components/internal/BaseElement/BaseElement.ts
- packages/lib/src/components/internal/BaseElement/types.ts
> v6 - Removing BaseElement remount() property

- .changeset/tender-points-knock.md
- packages/lib/package.json
- packages/lib/src/components/ApplePay/payment-request.ts
- packages/lib/src/components/ApplePay/types.ts
- packages/lib/src/core/types.ts
- yarn.lock
- Updating applepay types to give proper Typescript inference
- Added missing challengeWindowSize param
**Fixed issue**:  #2537 , #2530
> Updated @types/applepayjs and fix missing challengeWindowSize param

- packages/lib/src/components/internal/SegmentedControl/SegmentedControl.scss
- packages/lib/src/components/internal/SegmentedControl/SegmentedControl.tsx
- packages/lib/src/style/design-tokens.scss
- packages/lib/storybook/stories/internals/SegmentedControl.stories.tsx
Restyle SegmentedControl with Bento styles
Check storybook: https://localhost:3020/?path=/story/internals-segmentedcontrol--default
> v6 SegmentedControl component restyle

- README.md
- packages/lib/src/style/design-tokens.scss
Add the token list to readme for v6
> Improve README.md

- packages/lib/src/components/Riverty/Riverty.tsx
- packages/lib/src/components/components-map.ts
- packages/lib/src/components/components-name-map.ts
- packages/lib/src/components/internal/Address/components/CountryField.tsx
- packages/lib/src/components/tx-variants.ts
- packages/playground/src/pages/Dropin/session.js
- Remove the country flag
- Add Riverty to the tx variant list
All tests passed
**Fixed issue**: COWEB-1346
> V6: remove country flag & add Riverty to the tx variant list

- .changeset/swift-dots-taste.md
- packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx
- packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx
- packages/lib/src/utils/validator-utils.ts
Allow forward slashes in address fields
(Unrelated - also added some clarifying comments about 3DS2 `onComplete` calls)
Manually tested adding forward slashes to address fields
**Fixed issue**: #2563
> Allow forward slashes in address fields

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> v6 - alpha4 release

- .github/workflows/npm-publish.yml
- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/config/rollup.plugins.js
- packages/lib/package.json
- packages/playground/package.json
- Removed UMD from the tarball file, so we can check if it improves the bundlephobia analysis
- Adjusted generated artifact to contain only  translations and UMD files
- Bumped the lib version so we can make a release to test it
> v6 - Removing UMD from npm package and adjusting artifact to contain translations

- packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.scss
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodName.scss
- Show all brands when it wraps
- Text align start for the brand name
> [v6] Style: show all brands and text align start for the brand name

- packages/lib/src/components/BacsDD/components/BacsInput.tsx
- packages/lib/src/components/Blik/components/BlikInput.tsx
- packages/lib/src/components/Card/components/CardInput/CardInput.tsx
- packages/lib/src/components/CashAppPay/CashAppPay.tsx
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.scss
- packages/lib/src/components/internal/Alert/Alert.scss
- packages/lib/src/components/internal/ClickToPay/components/CtPCards/CtPCards.tsx
- packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPResendOtpLink.tsx
- packages/lib/src/components/internal/FormFields/Field/Field.scss
- packages/lib/src/components/internal/FormFields/Field/Field.tsx
- packages/lib/src/components/internal/FormFields/Fieldset/Fieldset.scss
- packages/lib/src/components/internal/FormFields/Select/components/SelectListItem.tsx
- packages/lib/src/components/internal/FormInstruction/FormInstruction.scss
- packages/lib/src/components/internal/Icon/constants.ts
- packages/lib/src/components/internal/QRLoader/QRLoader.tsx
- packages/lib/src/components/internal/Voucher/Voucher.tsx
- packages/lib/src/style/design-tokens.scss
- change some icons to use bento ones
- update token small to 0.9em
- payment method name weight 500
- alert size xs
- form instruction size xs
- form label weight 400 size s
- field set title weight 500
> [v6] Finalize bento styles

- packages/e2e-playwright/package.json
- packages/e2e/app/src/pages/Address/Address.js
- packages/e2e/package.json
- packages/lib/.size-limit.cjs
- packages/lib/package.json
- packages/lib/src/core/core.registry.ts
- packages/playground/package.json
- yarn.lock
- Bumping to alpha7
- Removing auto files from `sideEffect` array
- Removed PURE tag from core.registry (it seems to not be needed)
> v6 - Removing 'auto' from 'sideEffects' config

- .changeset/dry-tomatoes-allow.md
- packages/lib/src/components/ANCV/ANCV.tsx
(cherry picked from commit cfc8d2922e14434097da6731549fbe9269391ddd)
> [v6] [cherry-pick] Fix: ANCV ignoring existing orders & not working as intended via custom pay button

- packages/lib/src/core/Services/http.ts
- packages/lib/src/core/Services/sessions/setup-session.ts
- packages/playground/src/pages/Dropin/session.js
Cherry-pick https://github.com/Adyen/adyen-web/pull/2706
> [v6][Cherry-pick] Sessions - Replacing "Invalid ClientKey" error message with more meaningful error 

- packages/lib/src/components/Dropin/elements/createElements.ts
- packages/lib/src/components/Dropin/elements/createInstantPaymentElements.ts
- packages/lib/src/components/Dropin/elements/createStoredElements.ts
- packages/lib/src/components/Dropin/elements/filters.ts
- packages/lib/src/components/internal/UIElement/UIElement.tsx
- packages/lib/src/components/internal/UIElement/types.ts
- packages/lib/src/core/AdyenCheckout.ts
- packages/lib/src/core/CheckoutSession/CheckoutSession.ts
- packages/lib/src/core/ProcessResponse/PaymentAction/PaymentAction.ts
- packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
- packages/lib/src/core/core.registry.ts
- packages/lib/src/core/core.ts
- packages/lib/src/core/types.ts
- packages/lib/src/types.ts
- packages/lib/src/types/global-types.ts
- Exposing the types of `AdyenCheckoutError` , `UIElement` 
- Simplified the types for certain callbacks (`onSubmit`, `onAdditionalDetails`, onChange`)
- Fixed module types in `core`
> v6 - Improving some typescript types

- packages/lib/src/components/Klarna/KlarnaPayments.tsx
- packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.test.tsx
- packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx
- packages/lib/src/components/components-map.ts
- packages/lib/src/components/components-name-map.ts
- packages/lib/src/components/tx-variants.ts
- packages/playground/src/pages/Dropin/manual.js
- packages/playground/src/pages/Dropin/session.js
- Remove `token` for the makeAdditionalDetailsCall
- Add the `klarna_b2b` back
All tests passed and we are able to submit payments successfully.
> [v6] Fix(klarna): remove token for the makeAdditionalDetailsCall

- README.md
- packages/lib/src/components/internal/Alert/Alert.scss
- packages/lib/src/components/internal/FormFields/Checkbox/Checkbox.scss
- packages/lib/src/components/internal/FormFields/Field/Field.scss
- packages/lib/src/components/internal/FormFields/RadioGroup/RadioGroup.scss
- packages/lib/src/components/internal/FormFields/Select/Select.scss
- update the `README.md` file see the [preview](https://github.com/Adyen/adyen-web/blob/cdc33d231150d5f22828a07c2bd1a5d87c1428ee/README.md#styling)
- update some styles to use more semantic ones (the value is the same, but the name is more appropriate)
All tests passed
> V6 readme on styles

- packages/lib/config/rollup.dev.js
- packages/lib/src/components/Giftcard/Giftcard.test.tsx
- packages/lib/src/components/Giftcard/Giftcard.tsx
- packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx
- packages/lib/src/components/Giftcard/types.ts
- packages/lib/src/components/internal/UIElement/UIElement.test.ts
- packages/lib/src/components/internal/UIElement/UIElement.tsx
- packages/playground/src/pages/GiftCards/GiftCards.html
- packages/playground/src/pages/GiftCards/GiftCards.js
> [V6] Giftcard new flow

- .changeset/good-needles-rescue.md
- packages/lib/package.json
- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/GooglePay/components/GooglePayButton.tsx
- packages/lib/src/components/GooglePay/types.ts
- packages/playground/src/pages/Dropin/session.js
- packages/playground/src/pages/Wallets/Wallets.js
- yarn.lock
- Adding support for the `borderRadius` property
**Fixed issue**:  #2669
> GooglePay - Adding borderRadius support

- packages/e2e-playwright/package.json
- packages/e2e/package.json
- packages/lib/package.json
- packages/playground/package.json
> v6 - Beta 1

- packages/lib/src/components/ANCV/ANCV.tsx
Fixes a bug in V6 where order was not being sent in payments.
> [V6] Fix ANCV order not being sent in payments

- packages/lib/src/components/GooglePay/GooglePay.tsx
- packages/lib/src/components/GooglePay/components/GooglePayButton.tsx
- packages/lib/src/components/GooglePay/types.ts
- packages/playground/src/pages/Dropin/session.js
- packages/playground/src/pages/Wallets/Wallets.js
- yarn.lock
- Cherry pick https://github.com/Adyen/adyen-web/pull/2736
> v6 - Cherry pick GooglePay borderRadius change

- packages/playground/src/services.js
Updates balanceCheck "backend call" to also contain the amount, as required in V70+. This is done for demo purposes and should be done on the backend in a production env.
> Update services balanceCheck for v70

- .github/workflows/stale-issues-bot.yml
- Attempt to configure/test github stale bot
> Adding yml for stalebot

- .changeset/rare-flies-brake.md
- packages/lib/src/components/UPI/UPI.tsx
- fix the ts error for upi `formatProps`
**Fixed issue**:  #2774
> fix(ts): upi formatProps ts error

- packages/server/translations/bg-BG.json
- packages/server/translations/ca-ES.json
- packages/server/translations/et-EE.json
- packages/server/translations/is-IS.json
- packages/server/translations/lt-LT.json
- packages/server/translations/lv-LV.json
> adds missing Riverty translations

- packages/lib/src/core/Analytics/utils.ts
Minor fix to optionally convert array data to string.
No need to add changeset as it was a patch for #2794
> fix(analytic-util): convert to string when exists

- packages/lib/.storybook/main.ts
- Optionally pass the SSL certificates to the Vite configuration to enable HTTPS
> fix(storybook): configuration

- packages/e2e-playwright/tests/issuerList/issuer-list.spec.ts
This PR removes a flaky test. It seems to all be working correctly at to be a race condition when reading `dotpay.data`, commenting the code instead of removing to help remind this test is probably worth moving to `testing-library` instead of `playwright`.
> Removes flaky test

- .changeset/sour-forks-care.md
- packages/lib/src/components/Dropin/components/PaymentMethod/OrderPaymentMethods.tsx
- packages/lib/src/types/index.ts
> [V5] Show ANCV  id order

- .changeset/healthy-drinks-smell.md
- packages/lib/config/setupTests.ts
- packages/lib/config/testMocks/srPanelMock.ts
- packages/lib/src/components/Card/Card.test.tsx
- packages/lib/src/components/Card/Card.tsx
- packages/lib/src/components/Card/components/CardInput/types.ts
- packages/lib/src/components/Card/types.ts
Cherry-pick from #2800, some adjustments to tests were made. 
> Cherry-pick fix stored card holder name #2800 c580d1e

- .github/workflows/validate-remote-assets.yml
ci: update trigger for validate-remote-assets.yml
> [v5] ci: update trigger for validate-remote-assets.yml

- .changeset/yellow-crabs-do.md
- packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.tsx
- packages/lib/src/components/internal/Button/Button.scss
- packages/lib/src/components/internal/Button/Button.tsx
- packages/lib/src/core/Errors/SRPanel.scss
- packages/lib/src/styles/mixins.scss
> Improves accessibility by removing region on payment method item and button loading state

- packages/lib/src/components/Ach/types.ts
- packages/lib/storybook/stories/components/ACH.stories.tsx
> Added ACH story

- packages/lib/storybook/stories/cards/Card.stories.tsx
- packages/lib/storybook/stories/cards/cardStoryHelpers/storedCard.style.scss
> adding storedCard story

- .changeset/nervous-chicken-travel.md
- packages/e2e-playwright/tests/issuerList/issuer-list.spec.ts
- packages/lib/src/components/BaseElement.ts
- packages/lib/src/components/PayPal/Paypal.test.ts
- packages/lib/src/components/Pix/Pix.test.ts
- packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
- packages/lib/src/core/Analytics/Analytics.test.ts
- packages/lib/src/core/Analytics/Analytics.ts
- packages/lib/src/core/Analytics/constants.ts
- packages/lib/src/core/Analytics/utils.ts
Cherry pick of #2838
unit tests adjusted
Relates to issue: COWEB-1412, #2792
> v5 cherrypick Always make call to analytics setup endpoint

- .changeset/few-kings-juggle.md
- packages/lib/src/components/Dropin/elements/createElements.ts
- packages/lib/src/components/Dropin/elements/filters.ts
> v5 - Dropin - Filtering out unsupported payment methods before creating the payment method components

- .changeset/polite-timers-sniff.md
- packages/lib/src/core/CheckoutSession/CheckoutSession.ts
- packages/lib/src/core/Services/sessions/setup-session.ts
- packages/lib/src/types/index.ts
Cherry pick from #2847
COWEB-1391
> Send browser info on setup (#2847)

- .changeset/ctp.md
- packages/lib/src/components/internal/ClickToPay/errors/TimeoutError.test.ts
- packages/lib/src/components/internal/ClickToPay/errors/TimeoutError.ts
- packages/lib/src/components/internal/ClickToPay/services/ClickToPayService.test.ts
- packages/lib/src/components/internal/ClickToPay/services/ClickToPayService.ts
- packages/lib/src/components/internal/ClickToPay/services/execute-with-timeout.test.ts
- packages/lib/src/components/internal/ClickToPay/services/execute-with-timeout.ts
- packages/lib/src/types/custom.d.ts
Cherry-pick https://github.com/Adyen/adyen-web/pull/2797
> v6 cherry-pick - Click to Pay: Adding Visa timeout logging

- .changeset/rotten-camels-think.md
- packages/lib/src/utils/get-process-message-handler.ts
Added optional chaining operator to postMessage handler function
**Fixed issue**:  #2824
> Added optional chaining operator

- packages/e2e-playwright/package.json
Bump playwright to fix e2e pipeline.
> Attempt to fix e2e pipeline on ubuntu

- .changeset/swift-rules-beam.md
- packages/lib/src/types.ts
Export `CustomTranslations` type
**Fixed issue**:  #2893
> Export CustomTranslations type

- .changeset/shaggy-poets-eat.md
- packages/lib/src/components/BcmcMobile/BcmcMobile.ts
- Adjusted QR code expiration text
- Removed unused 'Generate QR code' button label
> Payconic labels fix

- packages/e2e-playwright/fixtures/URL_MAP.ts
- packages/e2e-playwright/models/address.ts
- packages/e2e-playwright/models/boleto.ts
- packages/e2e-playwright/models/personal-details.ts
- packages/e2e-playwright/tests/e2e/vouchers/boleto/boleto.spec.ts
- packages/lib/config/jest.config.cjs
- packages/lib/package.json
- packages/lib/src/components/Boleto/Boleto.test.ts
- packages/lib/storybook/stories/vouchers/Boleto.stories.tsx
- yarn.lock
- Added unit tests for Boleto and e2e tests
- Added msw library so we can easily mock API requests for non-e2e tests
> Boleto tests

- packages/lib/src/components/internal/SecuredFields/lib/constants.ts
- Changed JWE encryption alg (enc) to A256GCM. 
- Define globals on window object as immutable (origin, key, genTime etc)
- Bumped some internal dependencies
All tests pass
> Update SF version to 5.4.0

- .changeset/silver-toys-invent.md
- packages/lib/src/components/Boleto/Boleto.tsx
- packages/lib/src/components/Boleto/types.ts
- packages/lib/storybook/stories/vouchers/Boleto.stories.tsx
- Added missing types to Boleto configuration
Fixes:  #3116
> Boleto - Fixing its typescript definition

- .changeset/afraid-trains-occur.md
- packages/lib/package.json
Move `@adyen/bento-design-tokens` into devDependencies
**Fixed issue**:  COWEB-1482
> chore: move `@adyen/bento-design-tokens` into devDependencies.

- .changeset/hip-bobcats-stare.md
- packages/lib/src/components/GooglePay/types.ts
- Adding 'challengeWindowSize'  type to google pay configuration
Fixes: #3111
> GooglePay - Adding challengeWindowSize type to its interface

- .changeset/funny-tables-film.md
- packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.regular.spec.ts
- packages/lib/src/components/internal/SecuredFields/lib/constants.ts
> Revert "Allow typing to continue in cardNumber field after panLength result"

- package.json
Add new test command (`start:storybook:e2e`) to top level `package.json`
Missing piece to make #3195 work
> add new test command (start:storybook:e2e) to top level package.json

- packages/e2e-playwright/package.json
- yarn.lock
- Updating version to use the most recent one available within our nexus repo
> Playwright version bump

- .changeset/shaky-sheep-cross.md
- packages/lib/src/components/GooglePay/GooglePay.tsx
- Adjusted it for consistency with ApplePay / PayPal components
> GooglePay -  Adjusted isValid value to be always true

- .changeset/proud-bananas-shop.md
- packages/lib/CHANGELOG.md
- packages/lib/package.json
- packages/playground/package.json
-   Fixed issue where clipboard copy-paste functionality wasn't working for mobile Safari 18.4 browsers ([#3314](https://github.com/Adyen/adyen-web/pull/3314))
> [ci] Release main

- packages/lib/CHANGELOG.md
Took me a while to figure out what "migration guide" refers to. Hopefully this helps others too.
> Add link to migration guide in CHANGELOG

- .changeset/salty-beers-relax.md
- packages/lib/src/index.umd.ts
- Exposing Fastlane for UMD bundle
> Fastlane - Exposing it on UMD bundle

- .changeset/many-eagles-wait.md
> chore: changeset

- packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-amex.spec.ts
- packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-bancontact.spec.ts
- packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-maestro.spec.ts
- packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-mc.spec.ts
- packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-visa.spec.ts
- packages/e2e-playwright/tests/utils/cards.ts
- packages/e2e-playwright/tests/utils/constants.ts
- Fix broken stored card bancontact test
- Use stored card numbers from card constants file
> Fix broken stored card bancontact test
