src/components/MBWay/MBWay.tsx, src/components/MBWay/components/MBWayInput/MBWayInput.tsx
The shopper data that can be sent into the MBWay component should have the same fields as the data that is returned by the component i.e. `shopperEmail` & `telephoneNumber`.
Currently we are expecting the _internal_ names: `email` & `phoneNumber` from the data object used to configure the component
=> MBWay shopper data - expect it to be inputted the same way it is outputted

src/components/Card/Card.test.ts, src/components/Card/Card.tsx
If the "store payment method" checkbox is present, include the `storePaymentMethod` property in the component output (even if `false`). Only exclude it if the checkbox is not shown.
- `enableStoreDetails` is on, and checkbox is on
- `enableStoreDetails` is on, and checkbox is off
- `enableStoreDetails` is off, and checkbox is on
- `enableStoreDetails` is off, and checkbox is off
=> Include storePaymentMethod in data output when unchecked

src/components/internal/Await/Await.tsx, src/core/ProcessResponse/PaymentAction/actionTypes.ts
The Await comp will now always call `onAdditionalDetails` when it receives an `error` (which covers the `error` & `refused` responses from the `/status` endpoint)
error (refused), success (authorised), timeout error
=> Await comp, by default, calls onAdditionalDetails for error/refused responses

src/components/Card/components/CardInput/components/Installments/Installments.test.tsx, src/components/Card/components/CardInput/components/Installments/Installments.tsx, src/components/Card/components/CardInput/components/Installments/index.ts
The Installments component was migrated to TypeScript and interfaces as well as unit tests were added.
- It's rendered.
- It doesn't show any option if the passed amount is set to `0`.
- It doesn't show any option if the default option `card` is not passed.
- It renders the right amount of options for each passed brand.
=> Migrate to Installments component to TypeScript and add tests.

src/components/Card/components/CardInput/CardInput.tsx
Countries with state datasets now get correctly validated when the state field value changes.
* Regular card payments.
* Countries with state datasets.
* Countries with no state datasets.
* Countries with state datasets with prefilled country.
* Countries with no state datasets with prefilled country.
=> Fix state field validation in the Card component

src/components/GooglePay/GooglePay.tsx
Fix `dropin.submit()` function when used on the Google Pay component.
- Call `dropin.submit()` when Google Pay is active.
=> Fix dropin.submit() function when used on the Google Pay component

src/components/GooglePay/components/GooglePayButton.scss
Make the Google Pay styles more generic so they work with dynamic buttons.
=> Fix Google Pay css selectors to work with all styles

src/components/GooglePay/GooglePay.test.ts, src/components/GooglePay/GooglePay.tsx, src/components/GooglePay/GooglePayService.ts, src/components/GooglePay/defaultProps.ts, src/components/GooglePay/requests.test.ts, src/components/GooglePay/requests.ts, src/components/GooglePay/types.ts
- Add types to Google Pay props
- Add support for callbackIntents/PaymentDataCallbacks and dynamic price updates
- Update price dynamically on shipping method change
- Update price dynamically on shipping address change
=> Add prop types to Google Pay, add callbackIntents support

src/components/internal/SecuredFields/lib/configuration/constants.ts
Bumped SF version to 3.2.4 to fix bugs when null is passed as a placeholder value and for autofill in Chrome on iOS
SecuredFields still load and work
=> Bumped SF version

src/components/GooglePay/components/GooglePayButton.scss
- Fix Google Pay button padding on dynamic buttons
- Button styles work on a default button
- Button styles work on a dynamic button
=> Fix Google Pay button padding on non-default scenarios

src/components/Card/Card.test.ts, src/components/Card/Card.tsx
- Fix validation on stored cards when billingAddress was required
- Set `billingAddressRequired` on a stored card, click pay.
=> Fix validation on stored cards when billingAddress was required

src/components/Card/components/CardInput/components/Installments/Installments.tsx, src/language/Language.ts, src/language/locales/en-US.json, src/language/utils.test.ts, src/language/utils.ts
- i18n module supports string interpolation
```js
// myTranslation: 'Hello %{name}',
i18n.get('myTranslation', { values: { name: 'world' } }); // Hello world
```
- i18n module supports plurals
```js
// myTranslation__plural: 'Hello worlds',
i18n.get('myTranslation', { count: 10 }); // Hello worlds
```
- i18n module supports multiple plural forms
```js
// myTranslation__plural: 'Many apples',
// myTranslation__2: 'Two apples',
i18n.get('myTranslation', { count: 10 }); // Many apples
i18n.get('myTranslation', { count: 2 }); // Two apples
```
- Installments options use the new i18n module features.
**Fixed issue**: #39
=> i18n interpolation and plurals support

src/components/Card/Bancontact.ts
- Default Bancontact Card brand to `bcmc`
- Create a `bcmc` component without props
=> Default Bancontact Card brand

src/components/ApplePay/ApplePay.test.ts, src/components/ApplePay/ApplePay.tsx, src/components/ApplePay/defaultProps.ts
Apple Pay will use the `configuration.merchantName` property as a label for the total line item by default.
This prevents issues with the biometric handoff where if the label is empty (the old default) the process would fail.
- Paying from a Mac without touchbar and authorising the payment on a linked iOS device works
- If the `totalPriceLabel` property exists, it will take precedence.
=> Use merchantName as totalPriceLabel if totalPriceLabel is not defined

src/components/Card/components/CardInput/CardInput.test.tsx
Added test to ensure `issuingCountryCode` is set on `CardInput` state as lowerCase
=> Add test to ensure issuingCountryCode is set on state as lowerCase

src/core/Analytics/Analytics.test.ts, src/core/Analytics/Analytics.ts
- Enable telemetry call by default.
=> Enable telemetry call by default

src/components/internal/QRLoader/QRLoader.js
QRLoader type comps call `onAdditionalDetails` when they receive an error-type response - this covers getting a "refused" response.
Works the same way as for the `Await` type comps
- Set `onAdditionalDetails` and forced an "error" and saw that `onAdditionalDetails` was called
- Further testing is required to check that in PBL this triggers the retry button re. DEV-28283
=> QRLoader payments call onAdditionalDetails when they fail

src/core/Analytics/Analytics.ts, src/core/Services/collect-id.ts, src/core/Services/post-telemetry.ts
- Disable telemetry calls when no access key is available
- Telemetry is sent when either `originKey` or `clientKey` are provided.
- Telemetry is ignored when no access key is available
=> Disable telemetry calls when no access key is available

src/components/internal/SecuredFields/lib/core/utils/processAutoComplete.ts
Previously we have expected the date that needs to be auto-completed to come through as a forward-slash separated string e.g. "10/2020". 
But on some browsers it can come through separated by a full stop e.g. "10.2020"
To handle this we now replace all non-numerical characters in the date string with a forward slash so our date processing code will always be able to run
Tested dates strings separated with ".", "-" and"/"
=> Handle different autoComplete formats

src/components/internal/SecuredFields/lib/configuration/handleConfig.ts
Now we can use the clientKey, which allows wildcards in a merchant's allowed origins, this means that the url for securedFields doesn't necessarily change as the merchant moves between domains e.g. as the shopper switches country.
This results in the securedFields html getting cached, which means it contains the wrong value for the origin, and this prevents the securedFields from initialising after the domain switch.
The fix is to add a base64 encoded hash of the `window.location.origin` to the securedField's url which will ensure that each url is different based on the domain that makes the request
Added hash to the sf url and tested that all 3 kinds of securedFields still load.
Confirmed hashes are different for 2 domains that differ only in the language component of the url
**Fixed …
=> Hash origin into url for SF iframes

package.json
Hash origin into url for SF iframes (#184)
Tested all types of SecuredFields still load.
Confirmed different hashes are generated for different domains (even when they only differ by the country component of the url)
**Fixed issue**:  FOC-33270
=> Release 3.11.4

src/components/ApplePay/ApplePay.test.ts, src/components/ApplePay/ApplePay.tsx, src/components/ApplePay/defaultProps.ts, src/components/ApplePay/utils.ts
- The Apple Pay component will default to the highest version supported by the shopper's device as long as no version is specified when creating the component ([Apple Pay on the Web Version History
](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_on_the_web_version_history))
=> Automatically select an ApplePay version 

playground/pages/SecuredFields/securedFields.config.js, src/components/internal/SecuredFields/lib/core/SecuredField.ts
The aria configurable property `iframeTitle` was not getting picked up due to a change to the name of the iframe specific config object (was `pmConfig` now is `iframeUIConfig`)
iframe now gets title attribute set if it is specified
=> aria iframeTitle was not being read after name change on main config object

src/components/Sepa/components/IbanInput/IbanInput.js, src/components/Sepa/components/IbanInput/IbanInput.test.js
Populate the IBAN based on the **paymentMethodsConfiguration** **ownerName** and **ibanNumber** from **sepadirectdebit** property.
[✔️] Fill the ownerName and ibanNumber
[✔️] Fill the ownerName 
[✔️] Fill the ibanNumber
[✔️] Leave it blank.
=> FEAT_iban: populate field from properties

src/components/Dropin/elements/filters.ts
Fixes an issue that could prevent the Drop-in from loading if one of it's components failed to resolve/reject the `isAvailable` functionality in some browsers.
=> Add timeout to Dropin's isAvailable filter

src/components/internal/SecuredFields/lib/configuration/constants.ts
Increased securedFields version to 3.2.5 which now marks-up inputs with `type="text"` & `inputmode="numeric"`
Tested securedFields still load
Tested can still input into fields in Chrome, Firefox, Safari, IE11, Safari on iOS (12.x & 13.x), Chrome on Android
**Fixed issue**:  Relates to issue FOC-33752(point _2b_)
=> Increased securedFields version to 3.2.5

src/components/Dropin/components/PaymentMethod/PaymentMethodIcon.tsx, src/components/internal/FormFields/Field/Field.js
…usable" attr to payment method icons
Added aria attribute `aria-live="polite"` to error spans. 
Added `aria-hidden="true"` to span that holds payment method icon in Dropin.
Added IE related `focusable="false"` attr to <img> in payment method icon
Tested with Mac VoiceOver utility
**Fixed issue**:  Addresses issues in FOC-33752 (namely points _2i_ & _2j_)
=> Added aria & a11y attributes

src/components/internal/SecuredFields/lib/core/utils/init/processPlaceholders.ts
The recent change to always set a default, translated, placeholder if one wasn't defined by the merchant no longer allowed the merchant to set `null` or `''` as a means to clear the placeholder
Default placeholders are applied unless the merchant has set them.
If the merchant has set `''` or `null` then no placeholder is set
=> Fixed bug where it was no longer possible to set empty placeholders

src/components/internal/SecuredFields/lib/core/SecuredField.test.ts
Added tests for when merchant deliberately clears a placeholder with an empty string or null
=> Added tests for when merchant clears a placeholder 

src/components/Dropin/Dropin.tsx, src/components/GooglePay/GooglePayService.ts, src/utils/wait.ts
- Fixes an issue where Google Pay could trigger the submit flow twice on the Drop-in.
- Fixes an issue where Safari could not resolve the initial `isReadyToPay` promise on Drop-in when automatically loading the Google Pay API JavaScript library.
=> Fix Google Pay issues in Drop-in

src/components/internal/PersonalDetails/PersonalDetails.tsx
Fix personal details validation showing `true` when no error message is passed.
- Test telephone number field with Open Invoices payment methods, which don't show an error message.
- Test telephone number field with EContext, which has a custom error message.
=> Fix personal details validation

packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
- When prefilling global data on the main instance, POST redirect actions were getting the wrong data object when redirecting.
- POST redirect works when prefilling `data` on the main instance.
=> Fix props override in redirect action components

packages/lib/src/components/internal/FormFields/InputBase.tsx, packages/lib/src/components/internal/FormFields/utils.test.ts, packages/lib/src/components/internal/FormFields/utils.ts
Full width characters and numbers are not being correctly validated.
- Add util function to convert full width characters to half width characters.
- Apply this util function to all inputs. 
- Add tests.
- Remove unused functionality. 
- Convert full width numbers and letters.
- Do not convert other characters.
**Fixed issue**:  FOC-33772
=> Fix/FOC-33772 Full width characters

packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/UIElement.tsx
Components create as a result of `handleAction` were losing their reference to the merchant defined `onError` callback unless it was defined at _checkout configuration_ level.
So if it was defined as a _component config option_, or, with the Dropin, as a _payment method config option_ `onError` was not propagating to the actual component
With MBWay in Dropin - tested `onError` is called no matter at what level it is defined (3 possible levels)
With MBWay in Components - tested `onError` is called no matter at what level it is defined (2 possible levels)
=> Components maintain refs to onError callback

packages/playground/tsconfig.json
Since all lib code has been migrated to TypeScript, we can `allowJs`.
=> Disable allowJs in tsconfig

packages/lib/src/core/RiskModule/constants.ts
In response to a merchant issue that the riskModule was showing an error in the console about "timing-out" - give the riskModule longer to load
=> Bump riskModule timeout

packages/lib/src/components/Card/components/CardInput/handlers.ts
Recent refactor had missed adding a ref to "current" when accessing SFP functionality
Functionality now works
=> accessor "current" was missing form this.sfp reference

packages/lib/src/components/Dropin/Dropin.tsx
Fix `elementRef` not being propagated to the `DropinComponent`.
Because of this, the PayPal component was not sending the right reference in the `onCancel` and the `onError`.
=> Fix PayPal onCancel event not propagating the right component reference

packages/lib/src/components/Dropin/elements/filters.ts, packages/lib/src/components/GooglePay/GooglePayService.ts, packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/requests.test.ts, packages/lib/src/components/GooglePay/requests.ts
- Default `existingPaymentMethodRequired` to false on Google Pay component.
- Disable timeouts when loading the Google Pay Web SDK file automatically.
- Increment Drop-in timeout for payment methods that use the `isAvailable()` function.
=> Fix Google Pay existingPaymentMethodRequired issues

packages/playground/config/webpack.dev.js
- Disable most logs on Playground's webpack dev server
- Watch changes only on adyen-web's dist/ folder
=> Disable webpack logs on Playground

packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/Dropin/components/DropinComponent.tsx
DropIn component has a few methods and props to control and handle selection, like `openFirstPaymentMethod` or `onSelect()`.
But in some cases I need to reset the selected payment method in an already mounted component.
At the moment there's no public API for that.
So, this PR adds `closeActivePaymentMethod ` to reset selected payment method.
=> DropinComponent - add public method 'closeActivePaymentMethod'

packages/lib/src/components/Card/components/CardInput/processBinLookup.ts
The `brand`, detected by `/binLookup`, and set in the `paymentMethod` data for the Card component could end up with the wrong value if the shopper first entered one card and then _pasted another full, valid, number_ without doing any further actions to cause the Card component to validate it's input
Scenarios described in issue (see below)
**Fixed issue**:  FOC-35674
=> Call validateCardInput after binLookup detects a new brand

packages/lib/src/core/types.ts
Extend locale type definition to allow custom locales while still make it possible to autocomplete our supported locales.
**Fixed issue**:  Adyen/adyen-web#364
=> Fix/Extend locale type definition to allow custom locales.

packages/lib/src/components/GooglePay/requests.test.ts, packages/lib/src/components/GooglePay/requests.ts
- Add extra [transactionInfo](https://developers.google.com/pay/api/web/reference/request-objects#TransactionInfo) fields to Google Pay payment request 
```js
const googlepay = checkout.create("paywithgoogle", {
// ...
transactionInfo: {
// ...
}
});
```
=> Add extra transactionInfo fields to Google Pay payment request

packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/utils.ts
- Fix a `paymentMethodsResponse` warning message that would trigger even when no `paymentMethodsResponse` was provided.
=> Fix paymentMethodsResponse warning message

packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/PayPal/defaultProps.ts, packages/lib/src/components/PayPal/types.ts, packages/lib/src/components/PayPal/utils.ts
Update PayPal component to accept the vault and the `showPayButton` props.
When `showPayButton` is set to `false`, the PayPal buttons won't render.
Keep in mind the payment flow cannot be triggered programatically so it would require to mount the PayPal component somewhere else on the page.
**Fixed issue**:  #341
=> Feature/Update PayPal component to accept the vault and the showPayButton props.

packages/lib/src/components/Card/components/CardInput/CardInput.scss
Fixed possibility that the installments dropdown could overlap the text by removing fixed position and adding margin-left
As the label text changes (due to translations) - the dropdown stays the required distance to the right
=> revolving installments alignment issue

packages/lib/src/components/internal/FormFields/RadioGroup/RadioGroup.tsx, packages/lib/src/components/internal/FormFields/RadioGroup/types.ts
Add missing `name` prop to the RadioGroup component.
This fixes an issue with the Gender radio button not being able to be selected on open invoice components (AfterPay, Oney and RatePay).
=> Fix missing prop to the RadioGroup component

packages/lib/src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx
The open invoice is currently returning `undefined` when the delivery or the billing addresses are set as `hidden`.
Tested in both shown and hidden fieldsets.
=> Fix empty address fieldsets being returned in the data object

packages/lib/src/components/internal/SecuredFields/lib/core/utils/handleBrandFromBinLookup.ts
For `/binLookup` we were still defaulting to the generic 'card' type when we received an 'exotic' brand that we had no internal reference to i.e. it didn't exist in `cardType.ts`
This meant that the card logo wasn't being displayed
New brand "alelo" is sent from binLookup, the logo is displayed and remains in place
=> Remove defaulting to generic 'card' type

packages/lib/src/components/Ach/components/AchInput/defaultProps.ts, packages/lib/src/components/Blik/Blik.tsx, packages/lib/src/components/Card/components/CardInput/defaultProps.ts, packages/lib/src/components/Dropin/components/utils.ts, packages/lib/src/components/MBWay/MBWay.tsx, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/Await/types.ts, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/components/internal/QRLoader/types.ts, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/defaultProps.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/handleConfig.ts, packages/lib/src/components/internal/SecuredFields/lib/core/initCSF.ts, packages/lib/src/components/internal/SecuredFields/lib/types.ts, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/RiskModule/components/DeviceFingerprint/DeviceFingerprint.tsx, packages/lib/src/core/Services/collect-id.ts, packages/lib/src/core/Services/post-telemetry.ts, packages/lib/src/core/types.ts, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Components/Components.js, packages/playground/src/pages/GiftCards/GiftCards.js, packages/playground/src/pages/IssuerLists/IssuerLists.js, packages/playground/src/pages/OpenInvoices/OpenInvoices.js, packages/playground/src/pages/QRCodes/QRCodes.js, packages/playground/src/pages/SecuredFields/SecuredFields.js, packages/playground/src/pages/Vouchers/Vouchers.js, packages/playground/src/pages/Wallets/Wallets.js
- Remove originKey references, accepting only clientKey. (https://docs.adyen.com/development-resources/client-side-authentication/migrate-from-origin-key-to-client-key#availability-compatibility)
=> Deprecate origin key

packages/lib/src/components/Dragonpay/Dragonpay.tsx, packages/lib/src/components/Dragonpay/types.ts, packages/lib/src/components/Dropin/elements/createElements.ts, packages/lib/src/components/helpers/IssuerListContainer.tsx, packages/lib/src/core/core.ts
- Remove `/paymentMethods` response `details` property dependencies
- IssuerList components (iDEAL, DotPay, EPS...) use the new `issuers` property
- We assume every payment method not listed in the `componentsMap` follows a redirect flow.
=> Remove `details` dependency

packages/lib/src/components/helpers/IssuerListContainer.tsx
- Fix `formatProps` type issue on classes inheriting from `IssuerListContainer`.
=> Fix IssuerListContainer type issue

packages/lib/src/components/ApplePay/ApplePay.test.ts, packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/defaultProps.ts, packages/lib/src/components/ApplePay/types.ts
The configuration object for Apple Pay included in the `/paymentMethods` response contains the property `merchantDisplayName` while the component expects `merchantName`.
=> Fix Apple Pay configuration property

packages/lib/src/components/Giropay/Giropay.tsx
Giropay is currently checking the `showButton` instead of the `showPayButton` property.
It now checks both the `showButton` and the `showPayButton` properties.
=> Fix Giropay not checking the showPayButton property.

packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/components/ApplePayButton.tsx, packages/lib/src/language/Language.ts
- Apple Pay element changed from a `<div>` element to a `<button>` element
- Language parameter added (See [Localizing Apple Pay Buttons](https://developer.apple.com/documentation/apple_pay_on_the_web/localizing_apple_pay_buttons))
=> Change Apple Pay DOM element to button, add lang parameter

packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx, packages/lib/src/components/internal/Alert/Alert.scss, packages/lib/src/components/internal/Alert/Alert.tsx, packages/lib/src/components/internal/Alert/index.ts, packages/lib/src/style/colors.scss
- Display an error message when a balance check can't be completed successfully (not enough balance, different currency, incorrect giftcard number)
- Correctly call `submit()` from the `GiftcardResult` component
=> Handle errors in gift card flow

packages/lib/src/components/internal/FormFields/Checkbox/Checkbox.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.test.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/OpenInvoice/types.ts, packages/lib/src/components/internal/OpenInvoice/utils.test.ts, packages/lib/src/components/internal/OpenInvoice/utils.ts
Payment methods such as AfterPay have a Checkout component that can query for separate billing and delivery address. These fields can be pre-populated upon loading the Checkout script.
Upon initial loading the component is collapsed and only shows the billing address fields. Even if shipping address has been pre-populated in the script. The `state.data` object also will duplicate the billing address into the shipping address object. Only if ticked the "Specify a separate delivery address" box the delivery address fields will appear and will be used for state.data.
This changes this behaviour to expand the component with the billing address fields visible upon initial component loading, in case this data has been pre-populated. Also, if the delivery address is pre-populated and read-only, …
=> Update OpenInvoice to show the delivery address when prefilled

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/types.ts, packages/playground/src/pages/Wallets/Wallets.js
Add an `onClick` event to the Google Pay component. It will be triggered when the button is clicked, and gives the merchant an opportunity to perform a validation.
```
onClick: (resolve, reject) => {
// validate some external form
resolve(); // or reject();
}
=> Google pay onClick event

packages/lib/src/components/GooglePay/requests.test.ts, packages/lib/src/components/GooglePay/requests.ts, packages/lib/src/components/GooglePay/types.ts, packages/playground/src/pages/Wallets/Wallets.js
Fix Google Pay's `amount` property, amount will be displayed correctly again on the payment sheet.
=> Fix Google Pay amount property

packages/lib/src/components/Card/components/CardInput/handlers.ts
When holderName is disabled, it could still get populated by the autofill functionality of secured fields and set on `state.data`.
`paymentMethod` object no longer has `holderName` value after autoFill if `hasHolderName` is set to false
`paymentMethod` object does have `holderName` value after autoFill if `hasHolderName` is set to true
**Fixed issue**:  COWEB-752
=> Autofill holderName only when holderName is enabled

packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/PaymentMethodsResponse.ts, packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/utils.ts
Fixes an issue where initialization could fail if a `paymentMethodsResponse` value would contain `null` values.
- `paymentMethodsResponse.paymentMethods = null` defaults to an empty array
- `paymentMethodsResponse.storedPaymentMethods = null` defaults to an empty array
=> Fix null value issues on PaymentMethodsResponse

packages/lib/src/components/Dropin/components/DropinComponent.tsx
The Drop-in `onDisableStoredPaymentMethod` event now passes the correct `storedPaymentMethodId` parameter.
```js
onDisableStoredPaymentMethod: (storedPaymentMethodId, resolve, reject) => {
}
```
=> Fix storedPaymentMethodId parameter on the onDisableStoredPaymentMethod Drop-in event

packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
For the frictionless flow (fingerprint only) in 3DS2 -  Dropin was overwriting the specially defined `onComplete` function with its own default version of `onComplete`
Frictionless flow is working again in Dropin. (And still working in standalone Card component)
=> Frictionless flow in 3DS2 Dropin bug

packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx, packages/lib/src/components/internal/Alert/Alert.scss, packages/lib/src/components/internal/Alert/Alert.tsx, packages/lib/src/components/internal/Icon/Icon.tsx, packages/lib/src/language/locales/en-US.json, packages/lib/src/style/spacings.scss
Handle more error types on the balance check step in the new Gift card flow.
- An error is shown when a gift card has no balance
- An error is shown when a gift card has balance in a different currency
- An error is shown when a gift card number can't be found
=> Improve Gift card error messages

packages/lib/src/components/Card/triggerBinLookUp.ts
`/binLookup` was failing to recognise any card brands if a `brands` array was not specified in the config object. 
This is because it relies on this array to provide the `supportedBrands` used by the service.
Now we use the default brands array if none has been specified
If no brands array specified then the default is used and the `/binLookup` can recognise the card brand as being supported
=> Use default brands for binLookup if none have been defined

packages/lib/src/components/Card/components/CardInput/processBinLookup.ts
For compatibility with the latest fixes for KCP [#469](https://github.com/Adyen/adyen-web/pull/469) - when binLookup detects dual branded cards it also needs to pass `issuingCountryCode` into `SecuredFieldsProvider`
Detection of dual branded cards works without throwing an error in SecuredFieldsProvider
=> Incompatibility with dual branded cards (and latest KCP fixes)

packages/lib/src/components/internal/SecuredFields/utils.ts, packages/playground/src/pages/SecuredFields/securedFields.config.js
The separate date fields, if used in the custom card component, weren't getting default, translated, placeholders (used when the merchant didn't specify their own placeholders)
If no placeholders for these fields are specified then default ones are set from the translation files
=> Set default, translated, placeholders for separate date fields

packages/playground/src/config/commonConfig.js
In our playground it is possible to set the amount as a URL search parameter like this `?amount=123` to make quick tests, but setting it to `0` doesn't work. This fixes that issue.
- No amount
- Amount set as `0`
- Amount set as `100`
=> Fix amount value not being able to be set as 0 in the playground.

packages/lib/src/components/Card/components/CardInput/handlers.ts, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts
In addition to the fix in [#514](https://github.com/Adyen/adyen-web/pull/514) we also need to pass the `issuingCountryCode` in the object sent when a shopper clicks on one of the dual branding icons
Clicking on one of the dual branding icons doesn't cause an error.
e2e tests now exist for dualBranding scenarios.
=> Pass issuingCountryCode when selecting a dual brand

packages/lib/package.json, packages/playground/package.json
* Use default brands for binLookup if none have been defined (#512)
* Incompatibility with dual branded cards (and latest KCP fixes) (#514)
=> Release 3.18.2

packages/lib/src/components/Affirm/Affirm.tsx, packages/lib/src/components/Affirm/config.ts, packages/lib/src/components/AfterPay/AfterPay.tsx, packages/lib/src/components/AfterPay/AfterPayB2B.tsx, packages/lib/src/components/AfterPay/config.ts, packages/lib/src/components/FacilyPay/FacilyPay10x.ts, packages/lib/src/components/FacilyPay/FacilyPay12x.ts, packages/lib/src/components/FacilyPay/FacilyPay3x.ts, packages/lib/src/components/FacilyPay/FacilyPay4x.ts, packages/lib/src/components/FacilyPay/FacilyPay6x.ts, packages/lib/src/components/FacilyPay/config.ts, packages/lib/src/components/RatePay/RatePay.ts, packages/lib/src/components/RatePay/config.ts, packages/lib/src/components/internal/OpenInvoice/types.ts
Currently the `countryCode` is required as we always show the country dropdown as read only.
Now we're aligning with Affirm and we show a dropdown if no `countryCode` is passed.
=> Show a dropdown of countries if no country is passed in Open Invoices

packages/lib/src/components/ThreeDS2/ThreeDS2.scss
Our current implementation focuses only on the `05` challenge window size, which we hard code.
With the imminent arrival of the ability for the merchant once again to set their own challenge window size in the config (re. the new 3DS2 flow) this PR makes sure the relevant sizing and positioning styles are applied to the container and iframe for all possible challenge window sizes
**Fixed issue**:  relates to COWEB-867
=> Apply 3DS2 styling equally to all challenge sizes

packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/defaultProps.ts, packages/lib/src/components/ApplePay/types.ts, packages/playground/src/pages/Dropin/Dropin.js
Adds compatibility to the `onClick` event to the Apple Pay component.
```js
checkout.create('applepay', {
// ...
onClick: (resolve, reject) => {
resolve();
}
});
```
> Be aware that depending on what actions are performed in this event, an error could occur when creating the Apple Pay Session (`Must create a new ApplePaySession from a user gesture handler`, see [Creating an Apple Pay Session](https://developer.apple.com/documentation/apple_pay_on_the_web/apple_pay_js_api/creating_an_apple_pay_session)). This means, for example, starting the session after an asynchronous call will fail in most cases. Refer to the Apple Pay documentation for more information on this.
**Fixed issue**:  #589
=> Add onClick event to Apple Pay Component

packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.test.tsx, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProviderHandlers.ts, packages/lib/src/core/Errors/utils.ts
Previously, if the new securedFields error keys (example: `error.va.sf-cc-num.01`) weren't in the translation files
then we would fallback to using the old error keys (example: `creditCard.numberField.invalid`).
Now however these keys are included in all the translation files - so the "fallback" functionality can be removed
All test still work
**Fixed issue**:  COWEB-884
=> Remove fallback to old error keys

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
Add a class to the top level card containers indicating the `fundingSource` (`"credit"`/`"debit"`) for those card payment methods.
For Dropin especially this will make it easy to identify and, if required, hide via css, a particular set of cards
Tested separating card PMs based on fundingSource - both standalone card components and Dropin card components add an extra class to their top level container
**Fixed issue**:  COWEB-885
=> Add class to card containers showing their funding source

packages/e2e/tests/cards/branding/branding.clientScripts.js, packages/e2e/tests/cards/branding/branding.test.js, packages/lib/src/components/Card/components/CardInput/components/CardNumber.test.tsx, packages/lib/src/components/Card/types.ts
Added e2e tests for card brand detection
Tests especially focus on the state of the CVC field as brands are entered that see this field as optional or not required
=> e2e tests for brand detection

packages/e2e/tests/cards/branding/branding.test.js, packages/e2e/tests/cards/utils/constants.js, packages/e2e/tests/giftcards/enoughBalance/enoughBalance.test.js
Adding to e2e branding tests. 
Fixing warning about empty clientScripts file (giftcards > enoughBalance test)
Updated constant for expiry date
All tests run and pass
=> Adding to e2e branding tests

packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/lib/src/core/Errors/constants.ts, packages/lib/src/language/locales/en-US.json
Upped SF version to 3.2.8 - where, inbuilt check for wrong number in single-branded card, is removed.
This check was failing to recognise new BCMC bins and throwing an error which then prevented `/binLookup` from working.
So in the case of single-branded card components i.e. a card component hard typed to only accept a single brand e.g. 'bcmc' - securedFields now no longer try to detect what brand the shopper is _actually_ typing to see if it is correct or not; instead relying on binLookup to do this
All test still pass.
sf v3.2.8 is available on Test & Live
New bcmc bins are recognised
Typin a non-bcmc card into a bcmc card component gives the expected "unsupported card" error
**Fixed issue**:  COWEB-869
=> Fix for new bcmc bins

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/handlers.ts, packages/lib/src/components/Card/components/CardInput/processBinLookup.ts, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/internal/SecuredFields/lib/utilities/cardType.ts
Removed `displayName` from `CardType` objects - it was never put into use.
Also removed `switcherType` param from dual-branding functionality - again it was never put into use.
All tests, including e2e ones (which include specific dual-branding testing) still pass
=> Removing displayName from CardType objects

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/triggerBinLookUp.ts, packages/lib/src/components/Card/types.ts, packages/lib/src/components/internal/SecuredFields/lib/types.ts
A merchant wants to know when a shopper is entering their merchant-branded card into in a card component that is not configured for it - and specifically what brands are supported and what type of card is being entered.
This boils down to exposing the `supportedBrands` and `detectedBrands` from the `/binLookup` API.
So there is now a possibility for the merchant to add a new callback `onBinLookup` which will receive an object that looks like this:
```
{
type: 'card', // could be specific brand if component is dedicated to a single brand e.g. 'bcmc'
detectedBrands: ["mc"],
supportedBrands: ["visa", "amex", ]
}
```
`onBinLookup` is called if defined by the merchant. If not defined there is a default set which catches the callback and prevents an error being thrown …
=> onBinLookup callback

packages/lib/src/components/internal/FormFields/Select/Select.scss
Enforcing a height and width of auto on this icon causes the icon to not have a body on IE11. Setting the fixed height ensures the icon is always visible.
It solves the iDeal selected bank icon not appearing on IE11.
- Tested in IE11.
- Tested in a modern browser.
**Fixed issue**:  #674
=> Ensure iDeal selected bank icon has a height for IE11

packages/lib/package.json
Trying to run our tests on a Windows environment returns the error `'BABEL_ENV' is not recognized as an internal or external command`. Using `cross-env` should fix it.
Image as reference by @emidev98:
=> Fix test script not running on Windows environments

packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/PayPal/Paypal.tsx
As triggering the PayPal buttons programatically is not possible (as discussed in paypal/paypal-checkout-components#1264 and in paypal/paypal-checkout-components#522), we should show a console error if the `submit` method is called.
=> Prevent calling the submit method for PayPal

packages/lib/src/components/PayPal/components/PaypalButtons.tsx, packages/lib/src/components/PayPal/defaultProps.ts, packages/lib/src/components/PayPal/types.ts
Update PayPal component to add the `onShippingChange` event. This lets merchants listen to shipping changes and accept or reject the selected address.
More information on PayPal's [docs](https://developer.paypal.com/docs/checkout/integration-features/shipping-callback/) and (JavaScript SDK references](https://developer.paypal.com/docs/business/javascript-sdk/javascript-sdk-reference/#onshippingchange).
```js
const paypalComponent = checkout.create('paypal', {
// ...
onShippingChange: (data, actions) => {
if (data.shipping_address.country_code !== 'US') {
return actions.reject();
}
return actions.resolve();
}
}
```
Keep in mind that updating the order is not supported in our implementation, so it's not possible to patch the amount according to the selected address. …
=> Update PayPal component to add the onShippingChange event.

packages/lib/src/components/Dropin/elements/createElements.ts, packages/lib/src/components/Dropin/elements/filters.test.ts, packages/lib/src/components/Dropin/elements/filters.ts
We need to filter payment methods which are not supported in the Drop-in wether we support them as components or not.
See tests.
=> Filter unsupported payment methods

packages/lib/config/rollup.config.js, packages/lib/package.json, packages/playground/src/pages/Dropin/Dropin.js
In order for some bundlers to default to the `module` version, we need to remove the `browser` field. Also adding new standard [`exports` field](https://nodejs.org/api/packages.html#packages_package_entry_points).
=> Remove browser field, add exports

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
Filter payment methods which are not supported in the Drop-in (#722). 
In preparation for a future release, we've made some updates to the 3D Secure flow. This should not have any effect on your integration (#729)
Adyen Web v3.22.0 requires API v66 or later.
=> Release 3.22.0

packages/lib/src/core/Services/fetch.ts, packages/lib/src/core/Services/http.ts, packages/lib/src/polyfills.ts
Move the fetch polyfill to the services/ folder to prevent it from polluting the global namespace.
=> Prevent fetch polyfill from polluting the global namespace

packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/Dropin/types.ts, packages/lib/src/components/UIElement.test.ts, packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts, packages/lib/src/core/core.test.ts, packages/lib/src/core/core.ts, packages/lib/src/core/types.ts, packages/lib/src/types/index.ts
Allow passing props directly to action components through the `paymentMethodsConfiguration` property.
Example:
```js
const checkout = new AdyenCheckout({
// ...
threeDS2: {
challengeWindowSize: '05'
}
}
// ...
});
```
=> Support action props through paymentMethodsConfiguration

packages/e2e/tests/cards/branding/branding.exotic.clientScripts.js, packages/e2e/tests/cards/branding/branding.exotic.test.js, packages/lib/src/components/Dropin/elements/createElements.ts, packages/lib/src/components/ThreeDS2/components/utils.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/lib/src/core/core.ts
- Added test for card comp dedicated to single "exotic" txVariant that we don't recognise internally in our regExs - shopper should still be able to enter card details and have the card become valid
- Relies on new version of securedFields: `3.3.1`
- Dropped support for `size` config prop for 3DS2
- Fixed some typos and comments
All e2e tests run and pass
**Fixed issue**:  FOC-42352
=> e2e test for "exotic" brand in card comp dedicated to single txVariant

packages/lib/src/components/helpers/QRLoaderContainer.tsx
Fix loading status on QRCode components
QRCode components correctly react to `dropin.setStatus('loading')`
=> Fix loading status on QRCode components

packages/lib/src/components/RatePay/config.ts
Add `NL` to the list of supported countries for RatePay.
=> Update RatePay to support NL.

packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/PayPal/Paypal.tsx
Updated the PayPal component to prevent the `submit` method to be called when used in the component.
The `onError` will be triggered when trying to call the `submit` method in both the Drop-in and the component.
Tested in the Drop-in and in the standalone component.
=> Prevent the PayPal submit method to be called programatically in the Drop-in

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
- Fix loading status on QRCode components #753
- Prevent the PayPal submit method being called programmatically in the Drop-in #754
- Update RatePay to support NL. #755
Upped SecuredFields version to 3.3.1
Adyen Web v3.22.1 requires API v66 or later.
=> Release 3.22.1

packages/e2e/tests/cards/threeDS2/threeDS2.newFlow.redirect.test.js, packages/e2e/tests/cards/threeDS2/threeDS2.newFlow.test.js, packages/e2e/tests/cards/threeDS2/threeDS2.oldFlow.redirect.test.js, packages/e2e/tests/cards/threeDS2/threeDS2.oldFlow.test.js, packages/e2e/tests/index.js, packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/components/utils.ts, packages/lib/src/components/internal/SecuredFields/lib/utilities/createIframe.ts, packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
Ensure that 3DS2 flows remain separate:
- if the initial `/payments` response returns a `threeDS2Fingerprint` action then we will stay in the "old" flow of making a `/details` call after the fingerprinting (which in the "full flow" scenario will lead to a `threeDS2Challenge` action and a second `/details` call)
- if the initial `/payments` response returns a `threeDS2` action then we will move into the new flow of making a `/submitThreeDS2Fingerprint ` call after the fingerprinting (which in the "full flow" scenario will lead to another `threeDS2` action culminating in a single `/details` call)
Both scenarios work.
All unit tests pass.
All e2e tests for both scenarios pass.
The relevant 3DS2 e2e tests will run based on the API version
=> Fix/keep 3DS2 flows separate

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
The 3DS2 flows are kept separate #762
(This fixes the backwards compatibility issues with existing 3D Secure 2.0 integrations - see "Warning" on last 2 releases, `3.22.1` & `3.22.0`)
The phone input field labels have been improved for the Qiwi Wallet and MBWay components #756
Adyen Web v3.22.2 requires API v66 or later
=> Release 3.22.2

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
* Amazon Pay now supports the `cancelUrl` configuration property and the `submit()` method (#778)
* Improved support for Gift cards with a transaction limit (#561)
Adyen Web 3.23.0 requires API v66 or later.
=> Release 3.23.0

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/types.ts, packages/lib/src/components/index.ts
Accept the new Google Pay payment method type (`googlepay`) while maintaining compatibility with the current one (`paywithgoogle`).
=> Accept new Google Pay payment method type

packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Services/collect-id.ts
Delays fetching the `conversionId` on the Analytics module until the first telemetry call.
- Creating a new `AdyenCheckout` instance does not call the `conversionId` endpoint
- Mounting a component prompts a `conversionId` call.
- If called multiple times, conversionId is only fetched once.
=> Delay conversion id creation

packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.tsx, packages/lib/src/components/internal/FormFields/Select/Select.module.scss, packages/lib/src/components/internal/FormFields/Select/Select.scss, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectList.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectListItem.tsx, packages/lib/src/components/internal/FormFields/Select/constants.ts, packages/lib/src/components/internal/FormFields/Select/types.ts, packages/lib/src/components/internal/PhoneInput/PhoneInput.tsx, packages/lib/src/language/locales/en-US.json
- Make it possible to filter options in the Select component
- Update component to use hooks.
- Filterable lists will be the new default behaviour.
- Added strings:
```
"select.noOptionsFound": "No options found"
"select.filter.placeholder": "Search..."
```
Both filterable and non filterable lists.
**Fixed issue**:  Adyen/adyen-web#725
=> Select component updates

packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/PayPal/Paypal.tsx, packages/playground/src/pages/Dropin/Dropin.js
Remove duplicated configurations objects. This applies to Apple Pay, Google Pay and Paypal.
=> Align configuration objects

packages/lib/src/components/PayPal/Paypal.tsx
- Fix translations on the Paypal component by adding the missing `CoreContext` wrapper.
Processing state works correctly in other languages.
=> Fix paypal i18n

packages/e2e/tests/cards/binLookup/ui/mocks/binLookup.cvc.hidden.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/binLookup.cvc.optional.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/plcc.expiryDate.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/plcc.luhn.test.js, packages/e2e/tests/cards/utils/constants.js
The tests that used `RequestMock` started to fail - so added a predicate function on the `onRequestTo` method
All tests pass
=> fixed failing e2e tests that used RequestMock

packages/lib/src/components/BaseElement.ts, packages/lib/src/components/SecuredFields/SecuredFields.tsx
Card component and custom card component now use a different static `type` property.
This will allow any analytics to differentiate between the two.
Checked with relevant people in the analytics team that this will not affect existing dashboards and made sure they are aware of this change.
Reply:
> "There’s currently no logic taking this value explicitly into account, so it would just show up as another group by value in any of the dashboards"
=> Differentiate card from custom-card

packages/lib/src/components/internal/SecuredFields/lib/core/createSecuredFields.ts
…t recognised by our regEx
Remove "unrecognised card" warning (`console.warn`) when brands array contains type not recognised by our regEx.
In the light of `/binLookup` this warning is no longer relevant
=> Remove "unrecognised card" warning 

packages/e2e/tests/cards/binLookup/ui/mocks/binLookup.cvc.hidden.test.js, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/components/CVC.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFields.tsx, packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.tsx, packages/lib/src/components/Card/components/CardInput/components/types.ts, packages/lib/src/components/Card/components/CardInput/handlers.ts, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProviderHandlers.ts
In keeping with the changes to `/binLookup` and `SecuredFields` that see all options for the CVC field described under a single `cvcPolicy` property - propagate this change further up the chain to the `CardInput` component and unify its separate `cvcRequired` and `hideCVCForBrand` under a property of the same name, `cvcPolicy`, that is passed down into it's child components 
=> Unify cvcRequired & hideCVCForBrand props under a single cvcPolicy prop

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/components/GooglePayButton.scss, packages/lib/src/components/GooglePay/components/GooglePayButton.tsx, packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/types.ts, packages/lib/src/components/GooglePay/utils.ts
- Adds the `buttonSizeMode` configuration property
- Adds the `buttonLocale` configuration property
See https://developers.google.com/pay/api/web/reference/request-objects#ButtonOptions for more information on these properties.
- `buttonSizeMode` defaults to `fill` on the Drop-in
- `buttonLocale` defaults to the current locale set on the AdyenCheckout instance
=> Add buttonSizeMode and buttonLocale to Google Pay component

packages/lib/package.json
Move promise dependency from devDependencies to dependencies
- Should fix an issue where the `promise` dependency could be missing when using the ES bundle.
**Fixed issue**:  #807
=> Move promise dependency from devDependencies to dependencies

packages/lib/src/components/ApplePay/components/ApplePayButton.module.scss, packages/lib/src/components/ApplePay/components/ApplePayButton.tsx, packages/lib/src/components/ApplePay/types.ts, packages/playground/src/pages/Wallets/Wallets.js
Add new Apple Pay button types. The full list of supported types can be seen at `ApplePayButtonType`.
=> Add new Apple Pay button types

packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx
Allow threeDS2InMDFlow to send paymentData as empty string to the ThreeDS2Fingerprint.
This keeps it aligned with how threeDS2InMDFlow works with the ThreeDS2Challenge
=> Allow threeDS2InMDFlow to send paymentData as empty string

packages/lib/package.json
Add missing CSS file export in `package.json`.
Webpack 5 can correctly load the CSS assets.
**Fixed issue**:  #832
=> Add CSS file exports in package.json

packages/lib/config/rollup.config.js, packages/lib/config/terser.config.js
Mark all dependencies as `external` on the Rollup config, avoiding bundling dependencies into the final bundle for ES/CJS bundles.
=> Exclude external dependencies from ES/CJS bundle

packages/lib/src/components/AmazonPay/AmazonPay.tsx, packages/lib/src/components/AmazonPay/components/AmazonPayButton.tsx, packages/lib/src/components/AmazonPay/defaultProps.ts, packages/lib/src/components/AmazonPay/types.ts, packages/lib/src/components/AmazonPay/utils.ts, packages/lib/src/components/Dropin/elements/filters.ts, packages/playground/src/config/paymentsConfig.js, packages/playground/src/pages/Dropin/Dropin.js, packages/playground/src/pages/Wallets/Wallets.js
- Add support to the Additional Payment Button flow.
- Make Amazon Pay available in the Drop-in.
- Update Wallets and Drop-in playground pages to support this supported.
=> Amazon APB flow

packages/lib/src/components/GooglePay/GooglePay.tsx
- Include `browserInfo` in Google Pay component (necessary for 3ds flows)
=> Add browserInfo to Google Pay component

.github/workflows/codeql-analysis.yml
Fix the following warning on the CodeQL workflow:
```
Warning: 1 issue was detected with this workflow: git checkout HEAD^2 is no longer necessary. Please remove this step as Code Scanning recommends analyzing the merge commit for best results.
Error: The repo on which this action is running is not opted-in to CodeQL code scanning.
```
=> Fix 'git checkout HEAD^2 is no longer necessary' warning on CodeQL workflow

packages/lib/src/components/helpers/IssuerListContainer.tsx
- Fix an issue where the `data` attribute could fail if called too early on Issuer List components (iDeal, Dotpay, etc...)
- Calling `component.data` on init does not fail anymore.
=> Fix IssuerList components data attribute when state is empty

packages/lib/src/components/Card/Bancontact.ts, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/types.ts
Currently the Card component's property `hasCVC` is only set to `false` for stored (recurring) BCMC cards _not_ for a regular BCMC/Bancontact card.
It is this property that is supposed to decide whether to even render a CVC field.
The fact that the CVC field is being hidden for a regular, single-branded BCMC/Bancontact card is currently based on the fact that for a single-branded card the SecuredFields fires off a _single_ brand callback. This single callback call was designed for the Custom Card component as a way to provide extra brand information e.g. URL at which to find the logo; and it is entirely coincidental that it happens to cause the CVC field to be hidden for the regular BCMC/Bancontact card.
This PR fixes that.
=> Ensure the Card prop hasCVC is set to false for all Bcmc/Bancontact instance

packages/lib/src/components/internal/SecuredFields/SecuredFieldsProviderHandlers.ts, packages/lib/src/components/internal/SecuredFields/defaultProps.ts, packages/lib/src/components/internal/SecuredFields/lib/core/SecuredField.ts, packages/lib/src/components/internal/SecuredFields/lib/core/utils/iframes/postMessageValidation.ts
Since changes in `v3.21.0` to how we validate the `CardInput` - the edge case in `SecuredFieldsProviderHandlers.handleOnBrand` is no longer necessary. This ensured that for one click cards with an optional CVC field the Card component was marked as valid (and 'ready').
However recent changes means this now happens through the `handleOnAllValid` handler & this edge case code is redundant.
=> Remove "edge case" code

.github/workflows/ci-test.yml, package.json, packages/lib/config/rollup.config.js, packages/lib/package.json, yarn.lock
- Adds an **experimental** dev server which will transform TypeScript using ESBuild instead of Rollup's `rollup-plugin-typescript2`.
=> Add EXPERIMENTAL_DEVBUILD start:fast command

packages/e2e/tests/cards/Bancontact/bancontact.clientScripts.js, packages/e2e/tests/cards/Bancontact/bancontact.test.js, packages/lib/src/components/Card/Bancontact.ts, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/types.ts, packages/lib/src/components/internal/SecuredFields/defaultProps.ts, packages/lib/src/components/internal/SecuredFields/lib/core/createSecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/core/handleValidation.ts, packages/lib/src/components/internal/SecuredFields/lib/core/utils/handleBrandFromBinLookup.ts, packages/lib/src/components/internal/SecuredFields/lib/core/utils/processBrand.ts
Now that the Bancontact (BCMC) Card component can accept a number dual branded with Visa (which requires a CVC) it has to be handled differently at creation time (no automatic removing of the CVC securedField).
At the same time we can't treat it as a regular 'card' component - because it needs to hide the CVC field at at startup,
as well as show the BCMC logo in the number field and ignore any of the internal, regEx driven, brand detection.
Tested manually and also added e2e test for the expected scenarios/UI changes
**Fixed issue**:  Continuation of issue COWEB-869
=> Bancontact card component acts correctly when dual branded with Visa

packages/e2e/tests/cards/Bancontact/bancontact.dualbranding.reset.test.js, packages/e2e/tests/cards/Bancontact/bancontact.visa.reset.test.js, packages/e2e/tests/cards/Bancontact/bancontact.visa.test.js, packages/e2e/tests/cards/dualBranding/binLookup.branding.reset.clientScripts.js, packages/e2e/tests/cards/dualBranding/binLookup.branding.reset.test.js, packages/e2e/tests/cards/utils/constants.js, packages/lib/src/components/Card/Bancontact.ts, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/components/DualBrandingIcon/DualBrandingIcon.scss, packages/lib/src/components/Card/components/CardInput/processBinLookup.ts, packages/lib/src/components/Card/triggerBinLookUp.ts, packages/lib/src/components/internal/SecuredFields/SecuredFieldsProvider.ts
When card information is entered, and recognised by `/binLookup`, a `brand` property is set which will ultimately end up in the `paymentMethod` data submitted to the `/payments` endpoint.
However if the shopper then _pastes_ a second card number directly into the field - the `paymentMethod.brand` will remain set to the previous card brand.
This PR ensures that if `/binLookup` fails to recognize the BIN for a second card then this `brand` property is reset.
Various e2e tests included to test the above scenario.
Also testing:
- that for the Bancontact card component - a "reset" for an unrecognised card means the BCMC logo is once again displayed
- for the generic Card component this "reset" ensures that the internal regex brand detection takes place on the card number …
=> Brand (in PaymentMethod data) is reset after a failed binLookup

packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/Card/triggerBinLookUp.ts
Added a frontend layer to sort the array of `brands` objects from the /binLookup response.
This is necessary because there are some inconsistencies in the /binLookup response: 
e.g. card brands not always returned in the same order
and the fact that some components force new rules:
e.g. standalone Bancontact/BCMC card component with a dual branded bcmc/maestro card should show the maestro brand with a hidden cvc field 
To correct these things we now apply some rules via a frontend sorting procedure.
In the future it may be that the /binLookup will be able to sort the returned brands array according to these criteria.
Tested the rules are applied and the brands are sorted accordingly.
=> Apply sorting rules to brands returned by binLookup

packages/playground/config/webpack.config.js, packages/playground/src/pages/Dropin/Dropin.js
Load the `module` entry on the `package.json` for dependencies (skipping the default `browser`) on the Playground. See https://webpack.js.org/configuration/resolve/#resolvemainfields.
=> Default playground to module dependencies entry

packages/lib/src/components/Card/components/CardInput/CardInput.scss, packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/defaultProps.ts, packages/lib/src/components/Card/components/CardInput/types.ts, packages/playground/src/pages/Cards/Cards.js
Add option to position the holder name field on top of the Card component.
Users have been recurrently asking for the possibility of placing the holder name field at the top of the Card component. After discussing it with the some of the Frontend team and with some of our designers, we've decided to allow this.
Therefore we're adding a `positionHolderNameOnTop` option which accepts a boolean and it's `false` by default.
Added test to check if the positioning is working
**Fixed issue**:  Adyen/adyen-web#882
=> Add positionHolderNameOnTop for the Card component

packages/lib/src/components/internal/Button/Button.scss, packages/lib/src/components/internal/PayButton/PayButton.tsx
This fixes an issue where the default Pay button could still be submitted through the keyboard while on `loading` state. With this, we should prevent any accidental double submission of the payment form.
- Pay button can't be focused while on `loading` state.
=> Disable pay button while on loading state

packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/internal/SecuredFields/lib/core/handleEncryption.ts, packages/lib/src/components/internal/SecuredFields/lib/core/handleValidation.ts, packages/lib/src/components/internal/SecuredFields/lib/core/utils/callbackUtils.ts, packages/lib/src/components/internal/SecuredFields/lib/core/utils/processBrand.ts
Cleanup:
- pass an object to destructure, rather than separate arguments, when handling securedFields encryption & validation.
- removed unnecessary spread operator in ProcessBrand
- added comment
All tests pass
=> Cleanup - pass an object to destructure rather than separate arguments

packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx
Fixes an issue where the card holder name field would lose focus when typing on the field.
- Card holder name field does not lose focus
**Fixed issue**:  #917
=> Fix Card holder name focus lost when typing on the field

packages/lib/src/components/Boleto/components/BoletoInput/BoletoInput.tsx
- Fix Boleto not showing the state field
- Align UI with other compoents by showing the country field as read only.
=> Fix Boleto not showing the state field

packages/lib/src/components/BankTransfer/BankTransfer.tsx
We have noticed that you have implemented the feature to send a copy to the email when there is a payment with Bank Transfer. Which is a very good feature but in our case we do not need it and we noticed that the **showEmailAddress** flag was not working.
=> fix(BankTransfer): showEmailAdress flag

packages/lib/src/components/GooglePay/GooglePay.tsx
When making a Google Pay payment on the Drop-in with a custom button, a double `onSubmit` event was triggered.
- Calling `dropin.submit()` with Google Pay selected fires `onSubmit` once
**Fixed issue**:  #972
=> Fix double onSubmit call on Google Pay when using a custom button

packages/e2e/tests/cards/general/general.test.js
=> remove 'only' from e2e test

packages/lib/src/core/Services/order-status.ts
Fix order-status call on partial payments flow.
On a partial payments flow, the order status call works as expected.
The order status call uses a POST method.
=> Fix order-status call on partial payments flow

packages/lib/src/components/GooglePay/GooglePay.tsx
Fix the `component` reference on the second parameter of the `onSubmit` event to correctly point to the right instance (component or drop-in).
=> Fix onSubmit component reference on Google Pay component

packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx
Increase the maximum allowed gift card length from 22 to 32 digits.
=> Increase max gift card length from 22 to 32 digits

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/types.ts, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/components/UIElement.tsx
- Allow customizing icons of each payment method.
- Allow customizing brand icons on the card component.
All components accept an `icon` prop. In the Drop-in this will be displayed next to the name, in Components, this will be returned by `component.icon`.
```js
checkout.create('paywithgoogle', {
someConfig: {},
icon: 'htttps://...`
});
```
The Card component brand icons can also be customized through the `brandsConfiguration` property.
```js
{
card: {
brandsConfiguration: { 
visa: {
icon: 'https://...'
}
}
}
}
```
=> Allow custom icons and custom brand icons

packages/lib/package.json
It's not an uncommon pattern for bundlers/tools to do `require.resolve(path.join('@adyen/adyen-web', 'package.json'))` in order to find the location of a package's `package.json` file. However, for packages that have adopted the `exports` field in their `package.json`, this pattern won't work unless `package.json` itself is listed as an 'exported'/accessible file for the module. Here are some related discussions around this pattern: https://github.com/nodejs/node/issues/33460 and https://github.com/nodejs/modules/issues/516
A similar issue arose and was fixed by #837 for the CSS bundle in `adyen-web`.
This change allows the above pattern using `require.resolve` to work for `@adyen/adyen-web`.
@marcperez since you fixed the exports issue for the CSS bundle previously.
=> Add adyen-web package.json to exports

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/components/BrandIcon.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFields.tsx, packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx, packages/lib/src/components/Card/components/CardInput/components/DualBrandingIcon/DualBrandingIcon.tsx, packages/lib/src/components/Card/components/CardInput/components/types.ts, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Giftcard/Giftcard.tsx
Relates to #1039.
* The icon shown in the Card number field will also display the custom logo when a Card brand has a customized logo.
* Gift card brands can be customized through `brandsConfiguration` as well.
- Custom Card brand icons are used everywhere
=> Allow customizing the CardNumber field icon on the Card Component

packages/lib/config/rollup.config.js
The path to the PostCSS config file was not set correctly, which means the plugins were not running. For this reason the CSS files in our releases were not minified and auto-prefixed.
Built the project and checked the generated CSS file.
=> Fix path to the PostCSS config file

packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/utils.ts
- Add `girocard` support to ApplePay
- Bump maximum supported ApplePay version to `11`
=> Add support for Girocard to ApplePay component

packages/e2e/app/src/handlers.js, packages/e2e/tests/cards/threeDS2/threeDS2.default.size.test.js, packages/e2e/tests/cards/threeDS2/threeDS2.handleAction.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.handleAction.test.js, packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts, packages/lib/src/components/ThreeDS2/components/utils.ts, packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts
If an options object is passed with a (3DS2) call to handleAction
e.g. `component.handleAction(action, {challengeWindowSize: '01'});`
Ensure the `challengeWindowSize` prop is passed through to the actual 3DSChallenge component
Tested both `handleAction` & `createFromAction` in Card component & Dropin
Added e2e tests for Dropin
**Fixed issue**:  COWEB-985
=> handleAction accepts & propagates challengeWindowSize option

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
* ApplePay component supports Girocard #1076
* Updated the Google Pay icon to better align with [Google Pay's brand guidelines](https://developers.google.com/pay/api/web/guides/brand-guidelines) #1102
* PayPal Credit can be turned off #1075 
* Multiple PayPal components can be mounted in the same page #1075 
* Fixed a double submit call on the Apple Pay component when using a custom button #1085
* Fixed broken issuer images on the IssuerList component #1092
=> Release Adyen Web 4.6.0

packages/lib/src/components/ApplePay/utils.ts
Add support for Carte Bancaire to Apple Pay component's map of supported networks.
=> Add CarteBancaire support to Apple Pay component

packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/UIElement.tsx, packages/lib/src/core/config.ts, packages/playground/src/pages/Dropin/Dropin.js
When the submit functionality is triggered, the active component or Drop-in instance will set its status to `loading` automatically. (equivalent of `component.setStatus('loading')`.
This automatic behavior can be turned off by setting the `setStatusAutomatically` prop to `false`.
=> Automatically set loading status on submit

packages/lib/src/components/GooglePay/GooglePay.tsx
Fix an unhandled rejected promise that was logging a console error when a shopper would cancel a Google Pay payment.
=> Remove unhandled promise on Google Pay

packages/lib/src/components/internal/FormFields/InputBase.tsx
When `classNameModifiers` was being passed as a prop to `renderFormField` (and on to `inputBase`), as well as performing the required role of adding to the classes for a field, it was also being written as an attribute to the `input` element
`input` elements no longer end up with a `classNameModifiers` attribute
=> Stop adding classNameModifiers as attribute to inputs

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/validate.ts
Fixed card holder name formatting and validation - now we accept everything _except_ digits
Use can type in punctuation marks and letters from other languages like ö
=> Fixed card holder name validation - only reject digits

packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/constants.ts
Improve a11y on Select element following the guidelines at https://w3c.github.io/aria-practices/examples/disclosure/disclosure-navigation.html 
- implemented guidelines on the role of the `Escape` key (close menu and leave focus on Select element)
- implemented guidelines on the field losing focus (close menu)
=> Improve a11y on Select element

packages/lib/src/components/Card/components/CardInput/validate.ts
This PR removes any special formatting for the card holder name field. Previously digits were not allowed, but some company names and test codes might contain those.
**Fixed issue**:  #1211
=> Allow any character on card holder name field

packages/lib/config/postcss.config.js
Fixes #1225. I think this is a bug in cssnano but I feel it's correct to disable colormin whilst it is causing a bug in this package
Built on MacOS
**Fixed issue**:  #1225
=> Disable colormin in postcss config

packages/lib/src/components/Card/components/CardInput/CardInput.tsx
Optional holderName field was validating and showing an error when empty and the Pay button is pressed.
Yet it was still possible to complete the other fields and make a payment.
Optional holder name stays untouched when empty and the Pay button is pressed. 
Completing the other fields, and leaving holder name blank, the payment can still be made
=> Optional holderName field was validating and showing an error

packages/lib/src/components/AmazonPay/components/AmazonPayButton.tsx, packages/lib/src/components/AmazonPay/config.ts, packages/lib/src/components/AmazonPay/types.ts, packages/lib/src/components/AmazonPay/utils.test.ts, packages/lib/src/components/AmazonPay/utils.ts
- Add support for Amazon Pay multi-currency solution
- Update type definitions.
- Fix onError being called without checking its existence.
Added unit tests
=> Add support for Amazon Pay multi-currency solution

packages/lib/src/utils/browserInfo.ts
Add a default value for the browserInfo language field in case we fail to retrieve the browser's language.
=> Default language value for the browserInfo

packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/components/internal/Address/components/CountryField.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.test.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.tsx, packages/lib/src/components/internal/Address/components/StateField.tsx, packages/lib/src/components/internal/Address/types.ts, packages/lib/src/components/internal/Address/validate.ts, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/Field/types.ts, packages/lib/src/components/internal/FormFields/Select/Select.scss, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx, packages/lib/src/components/internal/FormFields/Select/types.ts
Aligning how validations are done in the `Address component` with how they are done elsewhere:
- validation on blur
- (translated) error message shown
- green underline & tick icon when valid
This same has also been applied to the 'Select` component elements (Country & State dropdown) including adding the green tick icon when valid (although with an option to hide this)
How fields in the `Address` component behave when in error or valid is inline with the behaviour of other fields in other components
=> Aligning validations in the Address comp

packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/requests.test.ts, packages/lib/src/components/GooglePay/requests.ts, packages/lib/src/components/GooglePay/types.ts
Adds new field `merchantOrigin` to Google Pay configuration.
* Google Pay Element gets the configuration
* Google Pay receives said configuration
=> Adds merchantOrigin for Google Pay

packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.scss, packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx
Klarna `sdk` actions (in Drop-in) are handled in the same page (Drop-in stays on the page). If a merchant calls `dropin.setStatus('loading')`, that would block the interaction with the Klarna widget. 
This PR makes sure that interaction is still possible.
=> Fix Klarna pointer events on a loading state on Dropin

packages/lib/src/components/BaseElement.ts, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/EventsQueue.ts, packages/lib/src/core/Analytics/types.ts
We're currently using the v2 of our analytics endpoint, which expects an `checkoutAttemptId` instead of `conversionId`.
=> Rename conversionId to checkoutAttemptId

packages/lib/src/core/core.ts
- Fetch the right properties from the paymentMethods response on components with multiple txVariants
- `klarna_paynow` properties are set correctly, not defaulting to the base `klarna` ones.
=> Fetch the right properties from the paymentMethods response 

packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx, packages/lib/src/components/Klarna/constants.ts, packages/lib/src/components/Klarna/types.ts
- On Klarna Widget, use the new `payment_method_category` from the `/payments` response. This fixes issues with the previous mapping on some countries.
=> Use new payment_method_category field from Klarna payments response

packages/lib/src/components/UIElement.tsx
When using the Checkout Session flow, but implementing only the `onAdditionalDetails` event, the session automatic details call still gets triggered. This behavior is not desired, as only one should be called.
This PR ensures the `onAdditionalDetails` event gets called exclusively if present.
- If `onAdditionalDetails` is present, it will be called and the internal session details call won't.
- If no `onAdditionalDetails` is present and a `session` is, the internal session details call is correctly triggered.
=> Prevent session submitDetails call when onAdditionalDetails event is present

packages/lib/src/components/Dragonpay/components/DragonpayVoucherResult/DragonpayVoucherResult.test.tsx, packages/lib/src/components/Dragonpay/components/DragonpayVoucherResult/DragonpayVoucherResult.tsx, packages/lib/src/components/internal/Voucher/Voucher.test.tsx
- Hiding issuer logo image for `dragonpay_otc_philippines` tx variant
- Create `dragonpay_otc_philippines` using `createFromAction` on our `Vouchers` page in the playground, and check that issuer image does not show
=> Dragonpay - Hiding issuer image for otc_philippines tx variant

packages/lib/src/components/Dropin/components/PaymentMethod/OrderPaymentMethods.scss, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss
Focus state border was right against the text and icon of the payment method button. This improves it by adding some padding and remove some padding from its container.
- Tested focus on payment methods
- Tested partial payments / order payments for side effects
=> Fixes padding for payment method focus state

packages/e2e/tests/_models/CardComponent.page.js, packages/e2e/tests/cards/general/general.test.js, packages/e2e/tests/cards/utils/threeDS2Utils.js, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/playground/src/pages/Dropin/manual.js
- Bumped securedFields version to `3.7.3`
This fixes:
- Removing `aria-live="polite"` attr from containing `<div>` in iframe (re.COWEB-1032, point 2)
- `aria-invalid` attr on iframe `<input>` is set to `"false"` at start (re. COWEB-1040, point 3 & COWEB-1032, point 5)
- if wrong number of digits are in CVC field as the PAN is entered it immediately shows an error (re. [issue 1341](https://github.com/Adyen/adyen-web/issues/1341))
- Fixed 3DS2 e2e tests which were failing due to new markup in the 3DS2 simulator
- Moved card's `general.test.js` to use the page model and added tests
- Fixed typo in playground's `manual.js`
All e2e tests pass
**Fixed issues**:  see above
=> Bumping securedFields version to 3.7.3

packages/e2e/package.json, packages/lib/package.json, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/playground/package.json
- Reverting Secured fields version to `3.7.2`, as `3.7.3` isn't available live yet
=> Release 5.3.1

packages/lib/src/components/internal/FormFields/InputBase.tsx
Our text field wasn't handling fullwidth characters gracefully, due to the fact that we were not using `composition` events in order to accept text inputed by an IME.
When typing Japanese for example, the IME is activated and the user combine letters and the IME suggest words. This interaction wasn't working before.
- Unit tests , e2e-tests
- Used iOS Simulator to simulate iPhone using Japanese keyboard
- Tested on Windows 10 with Japanese keyboard
COWEB-1049
=> Adjusting text field to handle fullwidth characters

.github/workflows/validate-remote-assets.yml
- Adding Github Action which validates that secured fields assets are available live when creating a release branch
- As outcome, the script writes in the PR if the assets are live or not;
- The developer can still merge the PR even if the secured fields aren't live. This script aims to warn the developers in case that the assets are not there
- Tested using invalid secured fields url and check if github bot wrote in the PR
- Tested using valid secured fields url and check if github bot wrote in the PR
=> Validating remote assets before merging to master

packages/lib/src/components/PayPal/defaultProps.ts
PayPal default prop `onAdditionalDetails` was affecting the session flow, since if `onAdditionalDetails` is defined we call it instead of doing the sessions `submitDetails` way
- Tested doing payment with session and manual flow on the playground
**Fixed issue**: FOC-55587
=> Fixing PayPal sessions flow

packages/lib/src/components/PayPal/components/PaypalButtons.test.tsx, packages/lib/src/components/PayPal/components/PaypalButtons.tsx, packages/lib/src/components/PayPal/defaultProps.ts, packages/lib/src/components/PayPal/types.ts
- Added Paypal PAYLATER button 
- Added component property to force the UI to block the button, if the merchant wants to opt out
- Checked that UI renders Pay Later button
- Tested doing payment through Pay Later, getting the successful message
**Fixed issue**: COWEB-1050
=> Paypal PayLater button

packages/lib/src/components/Card/components/CardInput/CardInput.scss, packages/lib/src/components/Card/types.ts
Fixed holderName position when it is with an ErrorPanel - if holderName field was positioned on top it wasn't getting it's bottom-margin since it was no longer the first child of it's parent
HolderName field is positioned correctly whether it is above or below the credit card fields
=> Fixed holderName position when it is with an ErrorPanel

packages/lib/src/components/internal/FormFields/InputBase.tsx
Remove composition handling & full width char conversion from `InputBase`.
The best results in typing both regular and full width chars seems to come from not attempting to handle the composition events or convert full width chars to half width in the text fields based on `InputBase`.
Tested on Desktop, on simulated devices in Browserstack & on actual Android and iPhone devices with both regular and Japanese keyboards
**Relates to issues**:  #1407 & #1439
=> Remove composition handling & full width char conversion

packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Increase securedFields version to 3.7.5
(The necessary sf files go Live today: 10/01/22)
This bumps the sf version to one that contains the polyfill for `Array.fill`
All e2e test pass with this version bump
=> Increase securedFields version to 3.7.5

packages/lib/src/components/UIElement.tsx
`UIElement # handleError ()` method was setting the status using `this.setStatus` function, which sets the status of the `componentRef`. That means that it was setting the status only of the active payment method.
If the Drop-in is used, its status is kept as 'loading'  and the active payment method Component is set to 'ready', which let the whole Drop-in unusable since its status is 'loading'. (although the active payment method seems usable, but does not work).
The following change is setting the status using `this.elementRef.setStatus`, which makes Drop-in handle the whole `setStatus` logic in case it is being used; otherwise it will fallback to how the Component handles it.
=> Fix/setting status using elementRef on handleError

packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts, packages/lib/src/components/ThreeDS2/types.ts, packages/lib/src/core/Services/http.ts, packages/lib/src/core/Services/sessions/setup-session.ts
While using sessions, the misconfigured client key error is showing as generic `NETWORK_ERROR`, which makes hard for merchants to find out what is the problem. Besides that, errors for `submitThreeDS2Fingerprint` weren't reported properly.  
This PR has the following changes:
- Passing error message about misconfigured ClientKey to the http request code
- Added `errorLevel: fatal` to `submitThreeDS2Fingerprint` call, so we throw proper error in the console
- Added handler which parses error response from the backend and uses its message property if available
- e2e tests . Got failures on the following tests: `expiryDatePolicies.optional.separate.test.js , expiryDatePolicies.hidden.separate.test.js,  expiryDatePolicies.hidden.regular.test.js, threeDS2.default.size.test.js` , which does not …
=> Improving error message for ClientKey, 3DS2Fingerprint and generic Error responses

packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts
`callSubmit3DS2Fingerprint` wasn't handling exceptions throw by the http service, leading to an endless spinner.
With the following change, it will propagate the exception to the `UIElement#handleError` which will set the status of the component to 'ready'.
- When error happens on `callSubmit3DS2Fingerprint`, the status of the Drop-in is set to 'ready', making it usable again
**Fixed issue**:  COWEB-995
=> Error handling for 3DS fingerprint submit request

packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/UIElement.tsx
The signature of `Dropin.handleAction` and `UIElement.handleAction` do not match causing an error when integrating with Angular (i.e. [Adyen Angular Sample App](https://github.com/adyen-examples/adyen-angular-online-payments)).
**Note**: this didn't raise any problem when integrating Adyen-Web with a Node implementation.
@ribeiroguilherme As discussed I have updated both signatures to match 
Here is the error stack:
```
Error: node_modules/@adyen/adyen-web/dist/types/components/Dropin/Dropin.d.ts:94:5 - error TS2416: Property 'handleAction' in type 'DropinElement' is not assignable to the same property in base type 'UIElement<DropinElementProps>'.
Type '(action: PaymentAction, props?: {} | undefined) => this | null' is not assignable to type '(action: PaymentAction, props?: {} | …
```
=> Dropin component: match method signatures

packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.test.tsx, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProviderHandlers.ts, packages/lib/src/components/internal/SecuredFields/SFP/types.ts
The change with how we handle errors in v5 meant that a prop, `detectedBrands` was no longer being propagated when `/binLookup` failed.
In keeping with previous solutions to this problem we now store that prop so it can be added to the stored error object and so can be accessed when required.
This is of particular importance for the Custom card component.
All test pass.
`detectedBrands` can be accessed (in the `onChange` callback) and passed into other merchant defined handlers e.g. `onError` handlers for the Custom card component.
=> Restoring missing detectedBrands prop to error object

packages/e2e/tests/_models/CardComponent.page.js, packages/e2e/tests/_models/Installments.component.js, packages/e2e/tests/address/address.mocks.js, packages/e2e/tests/cards/installments/cards.installments.clientScripts.js, packages/e2e/tests/cards/installments/cards.installments.mocks.js, packages/e2e/tests/cards/installments/cards.installments.test.js, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/CardInput/utils.ts
In case the installments is configured for Card, and shopper selects 'One time payment' or  'Installment: 1x', we shouldn't  add the `installments` property to the payload. 
Added e2e tests
**Fixed issue**: COWEB-1070
=> Card: removing 'installments' property if shopper selects one time payment

packages/e2e/tests/_common/cardMocks.js, packages/e2e/tests/cards/Bancontact/bancontact.visa.reset.test.js, packages/e2e/tests/cards/Bancontact/bancontact.visa.test.js, packages/e2e/tests/cards/binLookup/responseAndCallbacks/binLookup.v2.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/binLookup.cvc.hidden.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/binLookup.cvc.optional.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/plcc.expiryDate.test.js, packages/e2e/tests/cards/binLookup/ui/mocks/plcc.luhn.test.js, packages/e2e/tests/cards/socialSecurityNumber/autoMode/autoMode.test.js, packages/e2e/tests/cards/utils/constants.js
Added constant for easy switching between versions of binLookup
Also removed mocks from Dropin/Bancontact tests now we have appropriate test card in the database
e2e tests pass both with v2 & v3 binLookup
=> Add constant for easy switching between versions of binLookup

packages/lib/src/core/Services/analytics/post-telemetry.ts
Replacing `plataform: web` parameter by `channel: Web` for telemetry events.
**Fixed issue**:  COWEB-1060
=> Updating telemetry event payload 

packages/lib/src/components/GooglePay/utils.ts
The Google Pay `environment` must be populated to be either **TEST** or **PRODUCTION**. There is a `resolveEnvironment` function in `utils.ts` that is used to determine this value based on the Adyen environment.
Currently, this function does not consider the **live-au** and **live-us** environment as **PRODUCTION**, resulting on Google Pay payments failing unless this is explicitly set in the Component configuration.
=> live-au and live-us environments do not resolve to Google Pay PRODUCTION

packages/e2e/tests/cards/binLookup/ui/panLength/panLength.focus.regular.test.js, packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/UIElement.tsx, packages/lib/src/core/core.ts
I get the impression that quite a lot of 3DS2 errors come from calling `handleAction` or `createFromAction` by passing it the full response object rather than the `response.action` object.
So I have made more explicit errors in these functions, detecting this scenario & explaining what the merchant has done wrong
(Also removed a `.only` from an e2e test)
In both `Dropin` & `Card`, with both `handleAction` & `createFromAction` passing in the whole response object triggers a new error.
Whilst in above scenarios correctly passing in `response.action` works correctly
=> More descriptive errors when whole response object passed to handleAction

packages/lib/src/components/ApplePay/types.ts
Function interface does not match with what is being returned. [Docs](https://docs.adyen.com/payment-methods/apple-pay/web-drop-in#drop-in-configuration) also mention that what is returned is an URL.
**Fixed issue**: #1498
=> ApplePay - Fixing type of onvalidatemerchant callback

packages/lib/src/core/core.ts
Currently the access modifier for `paymentMethodResponse` is private, which does not allow devs that are using Angular/Typescript to do what is described [here on our docs](https://docs.adyen.com/payment-methods/cards/web-component?tab=_code_sessions_code__1#step-2). As workaround, merchants need to use `@ts-ignore` to make it work.
**Fixed issue**: COWEB-1061
=> Updating paymentMethodResponse access modifier 

packages/lib/src/components/Dropin/elements/createInstantPaymentElements.ts
Forcing instant payment method button to show up if `showPayButton` is set to `false`. By default, it should always show up.
**Fixed issue**: COWEB-1075
=> Showing Instant Payment Method if showPayButton is set to false

packages/e2e/tests/cards/binLookup/ui/panLength/panLength.focus.regular.test.js, packages/lib/src/components/BacsDD/components/BacsInput.tsx, packages/lib/src/components/BankTransfer/components/BankTransferInput/BankTransferInput.tsx, packages/lib/src/components/Blik/components/BlikInput.tsx, packages/lib/src/components/Boleto/components/BoletoInput/BoletoInput.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/components/CardHolderName.tsx, packages/lib/src/components/Card/components/CardInput/components/KCPAuthentication.tsx, packages/lib/src/components/Card/components/CardInput/components/types.ts, packages/lib/src/components/Dragonpay/components/DragonpayInput/DragonpayInput.tsx, packages/lib/src/components/MBWay/components/MBWayInput/MBWayInput.tsx, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.tsx, packages/lib/src/components/internal/Address/types.ts, packages/lib/src/components/internal/CompanyDetails/CompanyDetails.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/InputBase.tsx, packages/lib/src/components/internal/FormFields/index.tsx, packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx, packages/lib/src/components/internal/PhoneInput/PhoneInput.tsx, packages/lib/src/components/internal/SendCopyToEmail/SendCopyToEmail.tsx, packages/lib/src/components/internal/SocialSecurityNumberBrazil/BrazilPersonalDetail.tsx, packages/lib/src/components/internal/SocialSecurityNumberBrazil/SocialSecurityNumberBrazil.tsx
To avoid confusion with misplaced/misdirected onChange handlers - `InputBase` only accepts `onInput, onBlur & onFocus` handlers.
The first 2 being the means by which we expect `useForm`--`handleChangeFor` validation functionality to be applied.
1). InputBase currently contains code which was added to fix a bug in useForm which was described so:
> Fixes useForm 'bug'
-Scenario:
1: An input is in an error state when it loses focus > the onChange handler runs > if this triggers a validation routine then the input shows an error. Correct!
2: The input is then interacted with but is left with exactly the same value in it when it loses focus > the onChange handler doesn't run > input can't be validated to show an error. Wrong!
-Logic:
This happens because we are relying on the 'onchange' event. …
=> Clarifying InputBase handlers

packages/e2e/app/src/pages/CustomCards/CustomCards.js, packages/lib/src/components/SecuredFields/SecuredFields.tsx
There was an issue (with brand recognition) triggered by the merchant not setting a `type` prop (with value `'card'`) when instantiating the Custom card component.
This prop was marked as optional in our Docs - but apparently was not!
It now is - if no `type` prop is set it is now forced to `'card'`
All test pass
**Fixed issue**:  DEV-53178
=> Map 'securedfields' to 'card' if 'type' prop not set in custom card config object

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx
Clarifying wording of 3DS2 challenge error.
For the original flow the error fires when `paymentData` not being present; in the new `/submit3DS2Fingerprint` flow it fires when `authorisationData` is not present.
=> Clarifying 3DS2 challenge error

packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleEncryption.ts, packages/lib/src/components/internal/SecuredFields/lib/types.ts
From 1st April 2022 the PCI rules change and we are allowed to expose the 8 digit bin value on cards whose PAN is >=16 digits.
The `issuerBin` prop will be added to the object sent to the `onFieldValid` callback
Relies on securedFields `v3.9.0` which is already Live
Tested via unit tests in securedFields
**Fixed issue**:  FOC-57768
=> Add Eight digit issuer bin prop

package.json, yarn.lock
We got a report from PayByLink that they where experiencing CSP errors. This was being caused by https://github.com/facebook/regenerator/issues/450
This PR solves this issue by setting the `regenerator-runtime` to version `^0.13.9` across all packages. For this a `resolutions` is set on the global `package.json` because of a bug in yarn. When https://github.com/yarnpkg/yarn/issues/5039 is fixed we can move this resolution inside `lib` workspace.
PayByLink tested this in their local setup
=> Fixes CSP error caused by regenerator-runtime

packages/lib/src/components/Swish/Swish.ts
Swish documentation states that the QR code times out after 3 minutes, yet it was displayed for 15 minutes previously. If the QR is scanned after 3 minutes, the payment is no longer valid and Swish app displays an error.
N/A
**Fixed issue**:  FOC-48755
=> [FOC-48755] Modify Swish QR code countdown time to 3 mins

packages/e2e/tests/cards/Bancontact/bancontact.visa.test.js, packages/e2e/tests/cards/availableBrands/component/availableBrands.clientScripts.js, packages/e2e/tests/cards/availableBrands/component/availableBrands.disabled.clientScripts.js, packages/e2e/tests/cards/availableBrands/component/availableBrands.test.js, packages/e2e/tests/cards/availableBrands/dropin/availableBrands.clientScripts.js, packages/e2e/tests/cards/availableBrands/dropin/availableBrands.compactView.test.js, packages/e2e/tests/cards/availableBrands/dropin/availableBrands.defaultView.test.js, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.scss, packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.tsx, packages/lib/src/components/Card/components/CardInput/defaultProps.ts, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodBrands/PaymentMethodBrands.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodBrands/PaymentMethodBrands.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss, packages/playground/src/pages/Dropin/session.js, yarn.lock
- `showBrandsUnderCardNumber` now has `true` as default value, which means it will be enabled by default for merchants, and they have to opt out for this new UI change.
- Styles were fixed - They weren't working as expected when merchant had many available brands. 
- Adjusted e2e and unit tests
=> Card - Updating position of available brands

packages/lib/src/components/PayPal/types.ts, packages/lib/src/components/PayPal/utils.ts
- Added `enable-funding=paylater` to PayPal SDK URL, so `PayLater` button can show up as expected for the available countries.
- Tested setting the country to FR / US / AU and confirming that `PayLater` button shows up
**Fixed issue**:  COWEB-1082
=> Enable Funding option for Paypal SDK

packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/Field/types.ts, packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx
When specifying a Field component you can now use the `useLabelElement` prop to specify whether the `Field` should wrap its content in a `<label>` element (usual, default, behaviour) or not.
The reason for this is that `RadioGroup` elements are exceptions to the usual fields in that they provide their own `<label>` elements. Without this change we end up with labels inside labels - which is not allowed according to the [spec](https://html.spec.whatwg.org/multipage/forms.html#the-label-element) ("no descendant label elements").
This change could be timely considering the prospect of upcoming accessibility audits.
It also aligns `Field.tsx` with how it works in KYC (with an eye on the sharedComponents scenario)
`PersonalDetails` comp, which uses the `RadioGroup`, no longer leads to a …
=> useLabelElement=false can be used on Field to wrap everything in a div

packages/lib/src/components/Donation/components/DonationComponent.tsx, packages/lib/src/components/internal/Button/Button.scss, packages/lib/src/components/internal/Button/Button.test.tsx, packages/lib/src/components/internal/Button/Button.tsx, packages/lib/src/components/internal/Button/types.ts, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/components/internal/Voucher/Voucher.tsx
- Added prop 'variant' to `Button` which is used to set the variant of the button instead of setting the variants by  using true/false (Example:`<Button  secondary={true} action={true}  ghost={true} ... />`
- Updated secondary variant CSS to match according to our designs
- The 'old' secondary variant now is called 'action' variant
- Updated Components which were using the 'old' secondary variant to use the 'action' variant
- Added unit tests checking classnames
**Fixed issue**:   CODS-1031
=> Button - Updating secondary button CSS

packages/lib/src/components/internal/Address/Address.tsx
Added `trimOnBlur` property to all fields used within an `Address` component. This strips whitespace from both ends as a field loses focus.
**Fixed issue**:  Alternative fix to [#1556](https://github.com/Adyen/adyen-web/pull/1556)
=> Added trimOnBlur property to all fields used within an Address component

packages/lib/src/core/core.ts
With the current implementation, if a payment method does not match with the any pm's of the `componentsMap`, then we render a `Redirect` component. Although typescript complains about that since the PM wasn't declared in the mapping.
This PR adds function overload to the `create` method which returns `RedirectElement` if the provided payment method does not match with the current dictionary.
- unit test, lint, type-check
- tried to create the component `checkout.create('directEbanking')` and verified that it returns `RedirectElement` 
**Fixed issue**: #1555
=> Fallback to Redirect type when payment method is not recognized during 'create'

packages/lib/src/components/Atome/Atome.test.ts, packages/lib/src/components/Atome/Atome.tsx, packages/lib/src/components/Atome/config.ts, packages/lib/src/components/Atome/index.ts, packages/lib/src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx, packages/lib/src/components/index.ts, packages/lib/src/components/internal/Address/Specifications.ts, packages/lib/src/components/internal/Address/constants.ts, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/OpenInvoice/types.ts, packages/playground/src/pages/Dropin/manual.js, packages/playground/src/pages/Dropin/session.js, packages/playground/src/pages/OpenInvoices/OpenInvoices.html, packages/playground/src/pages/OpenInvoices/OpenInvoices.js, packages/playground/src/services.js
- Added Atome payment method
- Started creating the interface of `OpenInvoiceContainer` as there was no interface defined before. I added the props used by this PR, but the remaining props need to be added afterwards.
- Introduced two new props on `OpenInvoiceContainer`: 
- `billingAddressRequiredFields`: similar to the current `personalDetailsRequiredFields`, but for billing address
- `billingAddressSpecification`: The billing address form needs to be customized in certain way that some of the default fields won't be shown for this payment method. Therefore the UI needs to be adjusted accordingly to not have empty space gaps. This property allows to pass an `specification` which dictates which fields to show and their position in the UI
- Tested manually the whole payment flow using …
=> Atome payment method

package.json, packages/lib/package.json, packages/lib/src/components/UIElement.tsx
- Removed `import type {..` from UIElement. The usage of Type-Only imports forces consumers of the library to have Typescript >= 3.8.0 . Apparently there is no much that can be done as described [here](https://github.com/microsoft/TypeScript/issues/41844) . Quickest win for now is to update the import of the UIElement
- Removed `yarn start:fast` script
**Related issue**:  #1553
=> Removing Type-Only imports and 'yarn start:fast' script

packages/lib/src/components/internal/FormFields/Select/Select.tsx
When clicking outside of a select input the state was not being properly reset.
* Test scenario showed in the ticket
#1497
=> Fixes bug with Select not reseting when clicking outside

packages/lib/src/components/internal/FormFields/Select/Select.tsx
`closeList()` method forces UI to focus on input, blocking the user to interact with other fields in this case
e2e and unit tests
=> Adjusting 'Selector' to not force focus when click outside happens

packages/lib/src/components/BankTransfer/components/BankTransferInput/BankTransferInput.tsx, packages/lib/src/components/BankTransfer/types.ts, packages/lib/src/components/Blik/components/BlikInput.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/validate.test.ts, packages/lib/src/components/Card/components/CardInput/validate.ts, packages/lib/src/components/internal/Address/types.ts, packages/lib/src/components/internal/Address/validate.ts, packages/lib/src/components/internal/IssuerList/IssuerList.test.tsx, packages/lib/src/components/internal/PhoneInput/PhoneInput.tsx, packages/lib/src/components/internal/PhoneInput/types.ts, packages/lib/src/components/internal/SecuredFields/lib/utilities/commonUtils.ts, packages/lib/src/utils/Validator/ValidationRuleResult.ts, packages/lib/src/utils/Validator/Validator.test.ts, packages/lib/src/utils/Validator/Validator.ts, packages/lib/src/utils/Validator/types.ts, packages/lib/src/utils/useForm/reducer.ts, packages/lib/src/utils/useForm/types.ts, packages/lib/src/utils/useForm/useForm.test.tsx, packages/lib/src/utils/useForm/useForm.ts
Improvements to `useForm/Reducer/Validator` functionality.
- can perform 'partial' validations using just a subset of the form schema
- can leave a field empty without triggering an error (aligns with PM-9057)
- stronger types
- ability to merge form data (in the case of nested forms)
- retrieving previous values if keys removed/re-added to the schema
These improvements bring our form validation mechanism into line with KYC & the "shared components" concept
All e2e and unit tests pass
**Fixed issue**:  discussions in PM-9057 (and offline) about consistency in how we validate fields and not treating a field as in error if the user interacts with it & leaves it empty. (Obviously if we validate the whole form and the field is required then it registers as "in error")
=> useForm improvements

packages/lib/src/components/Atome/Atome.tsx, packages/lib/src/components/Atome/config.ts, packages/lib/src/components/internal/Address/constants.ts
- Hiding 'bank details' part
- Adjusted billing address form layout to be the same for all countries
=> Atome layout fix

packages/lib/src/components/internal/Address/Specifications.ts
- Adjusted import to use relative instead of absolute path
**Fixed issue**:  #1592
=> Fix: Importing AddressField type using relative path

packages/lib/src/components/Dropin/components/DropinComponent.tsx, packages/lib/src/components/Dropin/types.ts, packages/lib/src/components/types.ts, packages/lib/src/core/CheckoutSession/CheckoutSession.ts, packages/lib/src/core/Services/sessions/cancel-order.ts, packages/playground/src/pages/Dropin/session.js
This objective of this PR is to add onOrderCancel handling when using the dropin with sessions. 
* Checked if orderCancel is trigged correctly with sessions
* Checked if it handles endpoint failure
* Checked if onOrderCancel is trigger in the manual implementation
* Checked if onOrderCancel is not passed the button is not shown
=> Add onOrderCancel to sessions

packages/lib/src/components/OnlineBankingIN/index.ts, packages/lib/src/components/WalletIN/index.ts, packages/lib/src/components/index.ts
Adds support for the Wallets India (wallet_IN) payment method and browserInfo for Netbanking India (onlinebanking_IN) payment method
**Fixed issue**: COWEB-1066
=> Adds support for the Wallets India (wallet_IN) payment method and browserInfo for Netbanking India (onlinebanking_IN) payment method

packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.tsx, packages/lib/src/components/internal/FormFields/FormFields.scss, packages/lib/src/components/internal/Icon/Icon.tsx, packages/lib/src/style/colors.scss
The objective of this PR is to add some additional quality of life improvements for everyone that use accessible technologies such as screen readers.
* The alt from some non relevant images where remove
* The placeholder color was changed to improve contrast
* Dropin and Card component was tested using 
* VoiceOver on Chrome (MacOS)
* VoiceOver on Safari (iOS)
=> Adds additional a11y fixes

packages/lib/src/components/Card/components/CardInput/components/StoredCardFieldsWrapper.tsx
I added the same behavior that was inside CardFieldsWrapper.tsx into StoredCardFieldsWrapper.tsx to improve accessibility in the latter.
Saved stored payments
**Fixed issue**:  #1608
=> Accessibility: Add ErrorPanel component to StoredCardFieldsWrapper

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/challenge.scss, packages/lib/src/components/ThreeDS2/components/utils.ts, packages/lib/src/components/ThreeDS2/types.ts, packages/lib/src/utils/get-process-message-handler.ts
A scenario exists, described in when it is not possible to retrieve a `transStatus` result for a 3DS2 challenge.
In this scenario an "error" object is sent (with `errorCode` & `errorDescription` properties).
The frontend 3DS2 component should treat this response as a valid outcome and handle it accordingly (show error icon, call merchant defined `onError` callback)
**Fixed issue**:  COWEB-1113
=> 3DS2 handling challenge error

packages/e2e/app/config/webpack.config.js, packages/e2e/app/src/pages/GiftCardsSessions/GiftCardsSessions.html, packages/e2e/app/src/pages/GiftCardsSessions/GiftCardsSessions.js, packages/e2e/tests/_models/GiftCardComponent.page.js, packages/e2e/tests/giftcards/onOrderCreated/onOrderCreated.clientScripts.js, packages/e2e/tests/giftcards/onOrderCreated/onOrderCreated.mocks.js, packages/e2e/tests/giftcards/onOrderCreated/onOrderCreated.test.js, packages/e2e/tests/pages.js, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/core/config.ts, packages/playground/src/pages/GiftCards/GiftCards.html, packages/playground/src/pages/GiftCards/GiftCards.js
This ticket is meant to add onOrderCreated callback. This callback tries to solve the following:
> While trying to make partial payments using gift cards on checkout sessions + web components, there is no way to inform the merchant and the shopper of a successful gift card payment and the remaining amount to be paid, after a part of the payment is successfully paid using a giftcard.
We solve this by creating this new callback, it should only get triggered when an order is created, because there was not enough balance in the giftcard to cover the full amount. If the gifcard can cover the full amount we still use the normal flow of asking for confirmation.
This callback will allow merchants to retrieve the `order` object, this should have the `remainingAmount` as well as informations of the …
=> Adds onOrderCreated callback to support GiftCard component in sessions flow

packages/e2e/app/src/pages/GiftCardsSessions/GiftCardsSessions.js, packages/e2e/tests/giftcards/onOrderCreated/onOrderCreated.test.js, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/playground/src/pages/GiftCards/GiftCards.js
We concluded that we don't need to use a promise for the onOrderCreated callback. This PR changes to normal function callback.
- Ran e2e tests fro onOrderCreated
- Tested playground integration
=> Change onOrderCallback to not return promise

packages/e2e/app/src/pages/Cards/Cards.js, packages/e2e/app/src/pages/CustomCards/CustomCards.js, packages/e2e/tests/_models/BasePage.js, packages/e2e/tests/cards/installments/cards.installments.test.js, packages/e2e/tests/cards/kcp/startWithKCP/startWithKCP.test.js, packages/e2e/tests/cards/kcp/startWithoutKCP/startWithoutKCP.test.js, packages/e2e/tests/cards/utils/constants.js, packages/e2e/tests/customcard/branding/customcard.unsupportedCard.test.js, packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleConfig.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/utils/destroySecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Loading securedFields version (`4.0.0`) that now uses JWE, rather than CSE, to encrypt data.
For Edge <= 18 & IE11 we fall back to a bulkier, "Compat", version of the file with the necessary polyfills.
Tested in (Browserstack):
- Windows 10, Chrome 45
- Windows 10, Firefox 40
- Safari 11.1
- Edge 15
- IE11
Tested on desktop:
-  latest versions of Chrome(102.0.5005), Firefox (90.0.2), Safari (15.5) on Mac OS Monterey
All tests, unit & e2e, pass for both the "regular" and the "compat" version
**Fixed issue**:  COWEB-1062
**Update**: latest version is `4.1.0` which is smaller in size and which also restores the "event logging" i.e. the tracking of the user behaviour within the PAN & cvc fields. All tests still pass.
=> Loading securedFields file that now uses JWE

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/ClickToPayWrapper.tsx, packages/lib/src/components/Card/components/ClickToPay/ClickToPayComponent.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPCards/CtPCards.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPCards/CtPCardsList/CtPCardsList.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPSection/CtPLogoutLink.scss, packages/lib/src/components/Card/components/ClickToPay/components/CtPSection/CtPLogoutLink.tsx, packages/lib/src/components/Card/components/ClickToPay/context/ClickToPayContext.ts, packages/lib/src/components/Card/components/ClickToPay/context/ClickToPayProvider.tsx, packages/lib/src/components/Card/components/ClickToPay/services/ClickToPayService.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/MastercardSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/VisaSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/types.ts, packages/lib/src/components/Card/components/ClickToPay/services/utils.ts, packages/lib/src/components/UIElement.tsx, packages/lib/src/components/types.ts, packages/lib/src/components/utils.ts, packages/lib/src/language/locales/en-US.json, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Dropin/session.js
This PR covers the payment flow doing `/payments` call using a Shopper card from CtP system.
PR highlights:
- Introduced the `setElementStatus` function in the `UIElement` . This function was created in order to allow a Preact component to set the status of the whole UIElement. 
- In this specific scenario of this PR, when the Shopper starts the checkout flow within the `<CtPCards />` component, we need to trigger the 'loading' in the whole UiElement from the Preact component. 
- `Card.tsx` now has two components references: `this.componentRef` and `this.clickToPayRef`
- `this.clickToPayRef` is introduced in order to make the `this.elementRef.setStatus` work for Card and Click to Pay - once the status is set to 'loading' for example (during a `this.submit` call) , the UiElement can …
=> Click to Pay - Checkout flow

packages/lib/src/components/internal/SecuredFields/lib/CSF/initCSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/utils/cardType-tests/cardType-otherFns.test.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/utils/cardType.ts
A small change to be more explicit in how we set a default securedFields type if one has not been defined.
Previously it was being caught because we set a default value for a parameter on a util function - now we are being clearer as to our intentions
All tests pass
=> Be more explicit in how we set a default securedFields type

packages/lib/src/components/internal/SecuredFields/binLookup/triggerBinLookUp.ts
To help with the move to sorting binLookup results on the backend rather than the front end this PR passes the card `'type'` prop to the `/binLookup` API so it can distinguish, for example, between the generic `'card'` version of the credit card and the specific `'bcmc'` version
**Relates to issue**:  DEV-45761
=> Passing type to binLookup

packages/e2e/tests/cards/Bancontact/bancontact.visa.test.js, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleBrandFromBinLookup.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
The Bancontact card component wasn't resetting its internal state when one of the other card numbers this component supports, e.g. maestro, was entered and then deleted.
Although the UI reset, and the BCMC logo was shown again, internally the component stayed as "maestro" - so when _re-entering_ a maestro number nothing was seen to have changed and the UI didn't reflect the  maestro "state" second time round
All tests pass.
New e2e test added for this specific scenario
=> Bancontact card resets internal CSF state when PAN is deleted

packages/lib/src/components/Card/Card.tsx, packages/lib/src/core/CheckoutSession/CheckoutSession.ts, packages/lib/src/core/core.ts, packages/lib/src/types/index.ts
This PR covers the handling of configuration.installmentOptions returned on the internal `/setup` call of `/sessions`. 
- When installmentOptions are provided in the `/sessions` call, they are correctly shown on the card component.
- When installmentOptions are provided both in the config and the `/sessions` call, `/sessions` takes precedence. 
- When installmentOptions are provided only in the config, they are correctly shown on the card component.
**Fixed issue**: COWEB-1122
=> Add support for installmentOptions for Sessions

packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Boost sf version to v4.1.1 - fixes issue whereby you could still enter a 4 digit cvc even when Amex is not a supported brand
All tests pass
**Fixed issue**:  #1634
=> Boost sf version to v4.1.1 (fixes issue #1634)

packages/lib/src/components/UPI/UPI.tsx, packages/playground/src/pages/Components/Components.js, packages/playground/src/pages/Dropin/manual.js, packages/playground/src/pages/Dropin/session.js
`onError` callback wasn't being triggered UPI payment method when used as Component. This happened only for the Collect flow, when the shopper needs to input the VPA.
*Fix:*  Adjusted Await component to use the same error callback as the QRLoader
**Fixed issue**: COWEB-1335
=> UPI - Fix for uncaught exception after timeout

packages/lib/src/components/BankTransfer/BankTransfer.tsx
…false
Fix bug where BankTransfer comp wasn't shown if showPayButton set to false
BankTransfer comp still shows if `showPayButton` set to false
**Fixed issue**:  COWEB-1116
=> Fix bug where BankTransfer comp wasn't shown if showPayButton set to false

packages/e2e/app/src/pages/GiftCardsSessions/GiftCardsSessions.js, packages/e2e/tests/giftcards/onOrderCreated/onOrderCreated.mocks.js, packages/e2e/tests/giftcards/onRequiringConfirmation/onRequiringConfirmation.clientScripts.js, packages/e2e/tests/giftcards/onRequiringConfirmation/onRequiringConfirmation.mocks.js, packages/e2e/tests/giftcards/onRequiringConfirmation/onRequiringConfirmation.test.js, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/playground/src/pages/GiftCards/GiftCards.html, packages/playground/src/pages/GiftCards/GiftCards.js
The motivation for this PR is to enable the session gift card flow when using a custom submit button (`showPayButton: false`). 
The problem with current setup is that merchants don't have feedback and a gift card can fulfil the total amount in the checkout, and since this is usually managed by the submit button present in GC component a new mechanism needs to be implemented.
Introduced a new callback `onRequiringConfirmation` was added this callback is triggered to provide inform that the gif card can be used for the total payment amount, and confirmation should be given.
This confirmation can be done by using `.submit()` method. This will trigger the payment call with the current gift card.
Also it was exposed the `.balanceCheck()` method. The merchant needs to use this to check if a …
=> Adds new callback and method to fix giftcard without submit button

packages/lib/src/components/internal/SecuredFields/lib/CSF/AbstractCSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/handleIframeConfigFeedback.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.ts
We now create the securedFields in sequence rather than trying to create them all at the same time.
This seems to mitigate against the "iframe interruption bug" whereby if _something_ interrupts the loading of an iframe then the listener we have for its `load` event never fires; which means the iframe never configures.
Tested by adding a breakpoint to the line where we declare the `setupSecuredField` function in `createSecuredFields.ts`
With the old, simultaneous creation, solution this re-created the error and some of the iframes never configured.
With the new, sequential creation, solution this no longer happens and everything configures.
Also all unit & e2e test still pass
=> Create securedFields sequentially not simultaneously

packages/lib/src/index.ts
We are in the process of upgrading from `3.23.0` to `5.21.0` and were a bit surprised that there was no more typing when creating the `AdyenCheckout` object. 
Adding the typing to the function makes it easier to see what  options are actually available.
=> Add proper typing for `AdyenCheckout` function

packages/lib/src/components/BankTransfer/components/BankTransferInput/BankTransferInput.tsx, packages/lib/src/components/Boleto/components/BoletoInput/validate.ts
The shopper email fields in the `BankTransfer` & `Boleto` components were not validating.
This PR connects those fields to the same email validation rule as used in the `PersonalDetails` component
Fields now validate using a email regEx
All tests pass
=> Connecting email validation to fields

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/UIElement.tsx, packages/lib/src/components/internal/Button/Button.scss, packages/lib/src/components/internal/Button/Button.tsx, packages/lib/src/components/internal/Button/types.ts, packages/lib/src/components/internal/PayButton/PayButton.test.tsx, packages/lib/src/components/internal/PayButton/PayButton.tsx, packages/lib/src/components/internal/PayButton/components/SecondaryButtonLabel.scss, packages/lib/src/components/internal/PayButton/components/SecondaryButtonLabel.tsx, packages/lib/src/components/types.ts, packages/lib/src/core/config.ts, packages/lib/src/core/types.ts, packages/lib/src/types/index.ts, packages/playground/src/config/getCurrency.js
From the ticket (COWEB-1139): 
> Add secondaryAmount config to Drop-in/Components to allow merchants to display dual prices on the Pay button (HRK to EUR migration) 
TL;DR - since Croatia is converting to the Euro they need to display 2 prices on the Pay button from 05/09/2022 to end 2023
The merchant can now pass in a `secondaryAmount` config object in the form:
```
{ 
currency: 'HRK', 
value: {convertedValue: 1 EUR = 7.53450 kuna}, 
currencyDisplay: 'code' 
}
```
This represents the secondary currency and the value (converted from the original amount).
It is up to the merchant to perform this calculation themselves.
A third property `currencyDisplay` gives the merchant _some_ control over how that converted value is then displayed (e.g. whether a currency symbol is used or whether the …
=> Pay button shows Croatian kuna and converted EUR amount

packages/lib/src/components/Card/components/CardInput/components/CardHolderName.tsx
Added missing autocomplete attribute to the credit card's holder name field
aka added an autocomplete attribute identifying the input purpose
**Fixed issue**:  #1690
=> add autocomplete attr to holdername

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/ClickToPayHolder.tsx, packages/lib/src/components/Card/ClickToPayWrapper.tsx, packages/lib/src/components/Card/components/ClickToPay/context/ClickToPayProvider.tsx
@ribeiroguilherme - this PR is what I was always talking about when I said that I wanted to reduce the footprint of Click-to-Pay in the actual Card component.
The whole CtP is wrapped inside one component `ClickToPayHolder` and it is this component that then unfolds the "complexity" of CtP - the `ClickToPayProvider` & the `ClickToPayWrapper`
I would actually like to rename the new `ClickToPayHolder` to `ClickToPayWrapper` and vice versa
=> Reduce CtP footprint in Card.tsx

packages/lib/src/components/internal/PayButton/PayButton.tsx
Added checks in `PayButton` to stop the `secondaryAmount` being rendered in situations when it shouldn't be present 
i.e if the merchant inadvertently defines and passes a `secondaryAmount` object - it should _not_ be shown when:
- we have a zero auth transaction
- it is a `Redirect` component
- it is a component based around the `Await` component e.g. MBWay
- it is a QR code component
- it is a Voucher
- if there is no primary `amount` passed in (i.e. merchant doesn't want the amount on the button at all)
Tested above scenarios
=> Checks in PayButton to stop the secondaryAmount being rendered unnecessarily

packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProviderHandlers.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/AbstractSecuredField.ts
Extra functionality around detecting if securedField's iframe fails to call its 'load' event or if they fail to configure
In both cases calls the `onError` callback defined by the merchant when they configure the main Checkout instance.(https://docs.adyen.com/online-payments/web-components/optional-configuration#events)
- Manually created scenarios forcing securedFields to fail to load and to fail to configure - saw that these situations were detected and reported as errors to the `onError` callback
- All unit & e2e tests pass
**Relates to issue:** #1369
=> Catching securedFields load and config failures

packages/e2e/tests/customcard/expiryDate/expiryDatePolicies.optional.regular.test.js, packages/e2e/tests/customcard/expiryDate/expiryDatePolicies.optional.separate.test.js, packages/lib/src/components/internal/PayButton/PayButton.test.tsx, packages/playground/src/pages/GiftCards/GiftCards.html
- Ensure side menu shows on Gift card playground page
- Change the names of some e2e tests for clarity
- Use the correct constant instead of a string PayButton unit test
=> Ensure side menu shows on Gift card playground page & other small fixes

packages/lib/src/components/Card/components/ClickToPay/services/sdks/AbstractSrcInitiator.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/MastercardSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/SrcSdkLoader.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/VisaSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/config.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/types.ts, packages/lib/src/components/Card/components/ClickToPay/services/types.ts, packages/lib/src/components/Card/components/ClickToPay/services/utils.ts, packages/lib/src/components/Card/components/ClickToPay/utils.ts, packages/lib/src/components/Card/types.ts, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Dropin/session.js
- Added `srcCorrelationId` property as part of the payload that is submitted in the `/payments` call
- Added new configuration property for Click to Pay named `merchantDisplayName` , which will be used to display the merchant name within the DCF (in case the DCF pops up during the checkout step)
- Manual test verifying the new property is sent
- Manual test verifying the merchant name shows up inside the DCF pop-up
=> Click to Pay - Adding missing property for 'payments' call and 'merchantDisplayName' new config

packages/lib/src/components/Ach/Ach.tsx, packages/lib/src/components/Ach/components/AchInput/AchInput.tsx, packages/lib/src/components/Ach/components/AchInput/types.ts, packages/lib/src/components/Ach/types.ts, packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/filters.ts
This ticket creates the ability to use ACH as a stored payment method. As well it creates a configuration that allows merchants to enable a checkbox for the user to consent storing their payment details to be used as part of the stored payment.
- ACH payment was saved
- Payment was successfully made with ACH stored payment method
=> adds ach as stored payment method

packages/lib/src/components/internal/FormFields/Checkbox/Checkbox.scss
This fixes the bug where the checkbox tick was only showing one of the lines. I was unable to find when this bug started, and what was causing it, besides seems to be a bug in `nanocss`.
Might be useful in the future further investigation on this, because `nanocss` version has not been change for more than a year.
- Check the CSS generated in the inspector
- Checked visually the checkbox 
=> fix checkbox nanocss bug

packages/lib/src/components/Ach/components/AchInput/defaultStyles.ts, packages/lib/src/components/Card/components/CardInput/components/CVCHint.tsx, packages/lib/src/components/Card/components/CardInput/defaultStyles.ts, packages/lib/src/components/Card/components/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.scss, packages/lib/src/components/Card/components/ClickToPay/components/CtPSection/CtPLogoutLink.scss, packages/lib/src/components/internal/PhoneInput/PhoneInput.scss, packages/lib/src/components/internal/PhoneInputNew/PhoneInput.scss, packages/lib/src/style/colors.scss, packages/playground/src/pages/SecuredFields/securedFields.style.scss, packages/playground/src/style/colors.scss
Improving contrast on main colors re. a11y guidelines - namely the red, green & blue colours that we use for borders etc for focus, error & valid states
NOTE: follow up work needs to be done to change the colours in the error & valid icons - but that is a separate issue in a separate repo
**Fixed issue**:  COWEB-1140
=> Improving contrast on main colors

packages/e2e/tests/cards/binLookup/responseAndCallbacks/binLookup.v2.test.js, packages/e2e/tests/cards/binLookup/ui/handlingErrors/unsupportedCardErrors.test.js, packages/e2e/tests/cards/expiryDate/minimumExpiryDate.test.js, packages/lib/src/components/Card/components/CardInput/components/CVC.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFields.tsx, packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx, packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx, packages/lib/src/components/internal/SecuredFields/lib/securedField/utils/processAriaConfig.ts
For the credit card component which uses a generic "Incomplete field" message we are now prefixing the field name to error messages to make them more accessible for the cognitively impaired.
This also aligns the visual error messages with those that are read by the screenreader
All tests pass
=> More specific credit card error messages

packages/lib/src/components/Card/components/CardInput/components/CVC.tsx, packages/lib/src/components/Card/components/CardInput/components/CardHolderName.tsx, packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx, packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/Field/types.ts, packages/lib/src/language/locales/en-US.json, packages/lib/src/language/locales/no-NO.json
For accessibility reasons we are now populating the alt tags for the valid & invalid icons with translatable text
TODO - ensure these translations are available in all languages, for now they are just in Norwegian (with a fallback to English)
All tests pass
**Fixed issue**:  #1622
=> Populating the alt tags for the valid & invalid icons

packages/lib/src/components/Card/components/CardInput/components/CardNumber.tsx
Merging PRs seems to have lost the i18n prop in CardNumber - so re-added it
=> Adding missing prop

packages/lib/src/components/OnlinebankingPL/index.ts, packages/lib/src/components/index.ts, packages/playground/src/pages/IssuerLists/IssuerLists.js
By mapping the name of the onlineBanking_PL component to match the case of its `txVariant` i.e. `onlinebanking_PL` => `onlineBanking_PL` (note the uppercase "B") - it is possible to avoid some unnecessary formatting of props, most notably having to "find" the `issuers` from the  corresponding paymentMethod object
If the `/paymentMethods` response returns an "issuer" type payment method with the `type: "onlineBanking_PL"` - the issuer list is correctly populated by the default `IssuerListContainer` functionality
=> Map Polish OnlineBanking component to match txVariant

packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
A bug was detect where we handle focus in a way that selects the payment method item. This is not the intended behaviour since payment methods should only be triggers on Click/Tap/Space (button pressed). 
- So far only tested on Chrome on macOS
=> Accessibility: fixes bug where focus selects payment method item

packages/lib/.eslintrc.js, packages/lib/src/components/Card/components/ClickToPay/components/CtPLogin/CtPLogin.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPLogin/CtPLoginInput.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPOneTimePassword/CtPOneTimePassword.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.tsx, packages/lib/src/components/UPI/components/UPIComponent/UPIComponent.tsx, packages/lib/src/components/UPI/components/VpaInput/VpaInput.tsx, packages/playground/src/pages/Dropin/session.js
The usage of `preact/compat` library leads to the misbehave of certain UI elements like input fields, event handlers, and focus mechanisms. Further more, [as described here](https://preactjs.com/guide/v10/switching-to-preact/), the library servers as a compatibility layer that allows you to leverage the many libraries of the React ecosystem and use them with Preact, which is not the case of this SDK.
This PR:
- Removes all the code that uses `preact/compat`
- Adds eslint rule to not let it be imported
=> Removing preact/compat imports

packages/e2e/app/src/pages/IssuerLists/IssuerLists.js, packages/e2e/tests/analytics/checkoutAttemptId.clientScripts.js, packages/e2e/tests/analytics/checkoutAttemptId.mocks.js, packages/e2e/tests/analytics/checkoutAttemptId.test.js, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/CheckoutSession/CheckoutSession.ts, packages/lib/src/core/Services/analytics/collect-id.ts, packages/lib/src/core/Services/analytics/types.ts, packages/lib/src/utils/Storage.ts
This PR handles the storage and usage of the `checkoutAttemptId` on the `sessionStorage`. This change aims to improve the calculation of the conversion rates, in scenarios like the shopper reloads the checkout page or comes back from a redirect payment method.
Highlights on how it works:
- If `checkoutAttemptId` is passed during the initialization of `AdyenCheckout`, then we don't handle the storage of the ID - the PBL app or the merchant itself is handling it in this scenario
- In case that there is no `checkoutAttemptId` passed, the SDK will request it and save on the sessionStorage along with a timestamp of 15 minutes - so if a redirect happens, or if the shopper decides to move out from the checkout and add another extra item to the cart, we would still use the same checkoutAttemptId …
=> Storing the checkoutAttemptId on sessionStorage

packages/e2e/app/config/webpack.config.js, packages/e2e/app/src/pages/StoredCards/StoredCards.html, packages/e2e/app/src/pages/StoredCards/StoredCards.js, packages/e2e/tests/_models/CardComponent.page.js, packages/e2e/tests/storedCard/general.test.js, packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.tsx
Fixing bug in 5.25.0 - where errors on the `storedCard` component are not translated & instead show as an error code
New e2e tests added for this scenario
All previous tests, unit & e2e, pass
=> fixing bug in 5.25.0 - storedCard error is not translated

packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.tsx
Motivation:
currently, opening an app - in our case the Swish app - will always trigger an AdyenCheckoutError.
This behavior is described in issue #1712.
This PR aims to solve that by letting the (mobile) browser optimistically open the app (i.e. Swish). I haven't found a way to catch any failures. However, on iOS, it will display a popup (see screenshots) notifying the user about the missing app, and will not trigger any script errors in the browser.
With a iPhone connected to a Desktop Mac OS X:
navigated a web page in the iPhone browser, run scripts from the desktop Safari (web developer tools, connect to device).
```javascript
// the url is grabbed from the Swish developer guide
let url = "swish://paymentrequest?token=c28a4061470f4af48973bd2a4642b4fa&callbackurl=merchant%253A%252F%252F …
```
=> Removing 'onError' call when redirectToApp happens in QRLoader/Await components

packages/lib/src/components/internal/Await/Await.scss, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.scss, packages/lib/src/components/internal/QRLoader/QRLoader.tsx
`QRLoader` and `Await` components were using invalid translation key. 
This PR reuses the `<ContentSeparator />` component which has the proper translation in place for 'qrCodeOrApp' scenario
- Manual testing checking that proper translation shows up
**Fixed issue**: #1769
=> Fix for missing translation for QRLoader/Await

packages/lib/src/components/OpenBankingUK/index.ts, packages/lib/src/components/PayByBank/PayByBank.tsx, packages/lib/src/components/PayByBank/index.ts, packages/lib/src/components/helpers/IssuerListContainer.tsx, packages/lib/src/components/index.ts
The objective of this ticket is to add support for Open Banking / PayByBank payment method.
Architecturally this was solved by adding two new functionalities to IssuerListContainer. One is the ability to handle a scenario where no issuers are returned by `paymentMethods/`. In this first scenario display a single button that works has a redirect payment method.
The second new functionality is the ability to manipulate the issuer list, into creating a brand list to display in the PaymentMethodItem on Dropin.
=> Adds PayByBank support

packages/lib/src/components/UPI/UPI.tsx, packages/lib/src/components/UPI/components/VpaInput/VpaInput.tsx, packages/playground/src/pages/Dropin/manual.js, packages/playground/src/pages/Dropin/session.js
When tweaking the payment modes on UPI, `onChange` callback was being called only when switching to 'VPA' but not when switching to 'QR code'. 
This behavior doesn't work on integrations that rely on the `onChange` callback as a way to get the payment method data (Example: SFCC plugin).
- `onChange` callback is triggered with the expected data on 'advanced flow' and 'sessions' flow
=> UPI - Triggering onChange callback when selecting QR code mode

packages/e2e/package.json, packages/lib/package.json, packages/playground/package.json
- Payment method: PayByBank #1751 
- Adds support for `enableStoreDetails` #1706 
- The mount function now mounts a Component after it has been unmounted. Previously, only remount could remount a Component. #1772 
- For Google Pay, payment submission errors now trigger the `onError` callback instead of throwing an exception. #1774 
- On mobile, redirecting the shopper to another app no longer triggers the `onError` callback with an `AdyenCheckoutError`. #1764 
- For UPI, changing the payment mode to **QR code** now triggers the `onChange` callback. Previously, only changing the payment mode to **VPA** triggered the callback. #1776
=> Release 5.27.0

packages/e2e/tests/customcard/branding/customcard.unsupportedCard.test.js, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/types.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleConfig.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/types.ts
Adding a new property, `forceCompat`, to Card config which will allow the merchant to force the use of the JWE compat version of securedFields.
This allows Checkout to work on older models of Samsung TV's and older versions of Chrome (45 - 53)
(From Chrome version >= 54 no problems were found)
Browserstack testing of Chrome 45 - 53 on Windows 10 & Mac High Sierra
Manual testing on a Samsung SmartTV
All existing tests pass
**Fixed issue**:  #1775
=> Add Card config property to force the use of the JWE compat version

packages/lib/package.json, yarn.lock
Attempts to fix the bug reported in #1794 by restricting which preact version can be used.
=> Locks Preact version to the same as yarn.lock

packages/lib/src/components/Ach/components/AchInput/AchInput.tsx, packages/lib/src/components/Ach/components/AchInput/types.ts, packages/lib/src/components/Card/components/CardInput/CardInput.tsx
Accept a config option for the ACH component, which is also securedFields based, to force it to use the JWE compat version of securedFields
**Related issue**:  In line with #1787, which allowed this config for the other securedField based components: Card & Giftcard
=> ach - also allow forceCompat version of securedFields

packages/e2e/tests/cards/threeDS2/threeDS2.redirect.test.js, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Bumping securedField version to 4.3.2
All tests pass
=> bump sf version to 4.3.2

packages/lib/package.json, packages/lib/src/components/internal/FormFields/Select/components/SelectListItem.tsx, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProviderHandlers.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/processAutoComplete.ts, yarn.lock
Upgrade `Preact` to `v10.11.2` and fix it at this version in `package.json`.
This fixes the Chrome autofill issue caused by `Preact 10.11.1`
Have also included the necessary change for `SelectListItem` (also caused by a change in `Preact 10.11.1`) - so dropdowns and Issuer Lists keep working.
All tests, unit & e2e, pass.
Selecting an item in a dropdown works
Autofilling in Chrome works
=> Upgrade Preact to 10.11.2

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/types.ts
There is an issue with the `3DS2InMDFlow` when the challenge page getting reloaded/refreshed. When this happens the process fails. So now the `3DS2InMDFlow` redirect page adds a `beforeunload` listener to the page. 
So, _for this flow only,_ we need to remove this listener so the redirect back from the challenge page can go unimpeded
Regular and new 3DS2InMDFlow both work as expected
**Relates to issue**:  FOC-66295
=> Remove 3ds2InMDFlow listener

packages/lib/src/components/AmazonPay/defaultProps.ts, packages/lib/src/components/AmazonPay/types.ts, packages/lib/src/components/AmazonPay/utils.ts, packages/lib/src/core/core.component.props.test.ts
There was a bug found where amazon would always load locale `en_GB` even when in the US. This would cause the script to fail when instantiating if no `region: US` prop would be passed.
This property has been deprecated and only `configuration.region` should be used.
Further more a generalised bug was detected where almost none of the components default pros are actually typed.
In this PR was also cleanup an unused property `design`. Since it cannot be found anywhere in amazon documentation.
Tested AmazonPay loading in the US and AmazonPay loading in EU.
=> Fixes AmazonPay settings loading region from wrong defaultProp

packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.scss, packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.tsx
See title. The credit card brands now slide out when the first two numbers of the card are recognised as a brand.
=> FIX: Adjust credit card brand animation in card component

packages/lib/src/components/Blik/Blik.tsx, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/Await/types.ts
Don't make "final state" calls (leading to a call to `onAdditionalDetails`) when `payload` is missing. 
Instead show an error state in the component.
Mocked responses with `resultCode:"authorised"` and an empty &/or missing 'payload' to ensure an error is shown and no `/details` call is made.
Mocked responses with `resultCode:"pending"` to confirm that the regular polling to the `/status` endpoint continues until the timeout (there were some concerns, expressed in the ticket) that it switched off after three attempts
**Relates to issue**:  DEV-54329
=> Blik (Await) Don't call /details endpoint when payload is missing

packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/components/UIElement.tsx, packages/lib/src/core/types.ts, packages/lib/src/types/index.ts, packages/playground/src/pages/GiftCards/GiftCards.html, packages/playground/src/pages/GiftCards/GiftCards.js
In this change we fix a bug where no callback was called when a `payment/` error was received. 
This would happen because of the order object in the response would trigger `handleOrder`, which would just update the component state but not trigger anything.
This change moves the responsibility of handling an order to the payment method. This means, that `Giftcard` is the only payment method capable of triggering `onOrderCreated`. A fallback is created in `UIElement` so handle a response with "order" has `onPaymentCompleted`. This last scenario should only happen when a payment fails since other payment methods always pay full remaining amount. 
  | Dropin | Comp | Custom Button
-- | -- | -- | --
Giftcard -> Authorization | ✅ | ✅ | ✅
Giftcard -> Success | ✅ | ✅ | ✅
Giftcard -> Fail | ✅ | ✅ …
=> fixes payment errors on order flow not triggering any callback

packages/playground/package.json, yarn.lock
Removing 'webpack-bundle-analyzer' dependency from playground . [Dependabot is bumping its version](https://github.com/Adyen/adyen-web/pull/1829), but we are not using it.
=> Removing 'webpack-bundle-analyzer' dependency

packages/e2e/tests/analytics/checkoutAttemptId.test.js, packages/lib/src/components/BaseElement.ts, packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/types.ts, packages/lib/src/core/RiskModule/RiskModule.tsx
Moving `checkoutAttemptId` to `paymentMethod` object in order to increase adoption of telemetry logic.
- e2e test
- manual test
**Fixed issue**:  COWEB-1143
=> [COWEB-1143] Move checkoutAttemptId field to paymentMethod object in state.data

packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/types.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/AbstractCSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleConfig.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/types.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/AbstractSecuredField.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.test.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.ts
It is considered best practice in India to mask the digits in the CVC field and is an industry norm in that country.
This PR allows the use of a config property `maskSecurityCode` in the Card component which will be passed through to the CVC securedField and lead it to set `type="password"` on its input field.
This relies on securedFields version `4.3.2` which has been live since October and was included in adyen-web `v5.28.2`
Have also removed the `bundleType` property passed to securedFields which became unnecessary after sf v4.2.0
(Plus renamed some internal config objects and added comments to some Type definitions)
Setting `maskSecurityCode: true` in the card component config causes the CVC field to be masked.
Setting it to `false`, or omitting the property, causes the CVC field to …
=> Added maskSecurityCode config prop

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx
A situation exists where:
- a card payment leading to 3DS2 occurs
- the 3DS2 component is mounted via `createFromAction` _in it's own separate container_
- after this payment - the card component is unmounted and Checkout is re-initialised (with a new session)
- making a 3DS2 payment _of the same type as the previous one*_ will just hang
re.
> _of the same type as the previous one*_
_The following will all fail:_
- frictionless (fingerprint-only) followed by frictionless (fingerprint-only) - FAIL
- frictionless (fingerprint-only) followed by full (_fingerprint first_ then challenge) - FAIL
- challenge-only followed by challenge-only - FAIL
- full (fingerprint then challenge) followed by challenge-only - FAIL
_On the other hand:_
- frictionless (fingerprint-only) followed by challenge-only …
=> Ensure threeds2 comps clean up after themselves

packages/lib/src/components/Klarna/KlarnaPayments.tsx
Fixes the Klarna widget component's `onAdditionalDetails` call with the Checkout Sessions integration.
- Klarna Widget calls the right details endpoint when no `onAdditionalDetails` event is provided and a Checkout Session is available.
**Fixed issue**:  COWEB-908
=> Fix onAdditionalDetails call for Checkout Sessions on the Klarna Widget component

packages/lib/src/components/Pix/Pix.tsx
Fixes a bug FOC-67919 where Pix wouldn't work unless showPayButton was set to true. There was a bug where the Input component that manages the state was hidden when the property was set to false.
- Successful payment methods with `showPayButton: true/false` and `personalDetailsRequired: true/false`.
FOC-67919
=> Fixes Pix not submiting when showPayButton was false

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/DoChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/types.ts, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/components/utils.ts, packages/lib/src/components/ThreeDS2/config.ts, packages/lib/src/components/ThreeDS2/types.ts, packages/lib/src/utils/get-process-message-handler.ts
Creating more informative errors from the 3DS2 process and stopping the "dead-end" that was possible from an un-parseable postMessage that came from a legitimate source.
- We now have extra checks on the data that is passed in to 3DS2 in order to create a challenge - these lead to more informative errors, presented in the component itself.
- There was also a situation that emerged in the MDFlow where a postMessage came from a legitimate, expected adyen url but with un-parseable data. This was leading to an "unknown error" message & icon, and a "dead-end" within the component itself - past which it was not possible to proceed.
Now we create an informative message about this event that we pass to the `onError` callback but _don't_ block the flow.
- Have also removed the code that dealt with …
=> Creating more informative errors 3DS2 errors

packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.tsx, packages/lib/src/language/locales/en-US.json
Change payment method items to have a radio role, this comes from the a11y audit.
From the accessibility audit:
#1695
=> Changes payment method buttons to have radio role

packages/lib/src/components/internal/SecuredFields/lib/CSF/initCSF.ts
Add warning if trying to initialise securedFields in development mode and a custom http domain is detected.
Under these circumstances window.crypto.subtle cannot work and errors of the type mentioned in #1710 are to be expected.
**Relates to issue**:  #1710
=> Detect custom http environment and show console.warning

packages/lib/src/components/internal/SecuredFields/binLookup/triggerBinLookUp.ts, packages/lib/src/components/internal/SecuredFields/lib/types.ts
Due to the regulations around recurring in India, merchants need to route payments on Indian issued cards via India local acquiring in India platform. 
To do this merchants need to first identify whether the shopper is using a card issued in India.
To this end we now pass the `issuingCountryCode` property to the merchant defined `onBinLookup` handler
All tests pass
**Fixed issue**:  FOC-68174
=> binLookup - pass issuingCountryCode to onBinLookup callback

packages/lib/src/components/Oxxo/Oxxo.spec.ts, packages/lib/src/components/Oxxo/Oxxo.tsx, packages/lib/src/components/Oxxo/types.ts, packages/playground/src/pages/Components/Components.html, packages/playground/src/pages/Components/Components.js
`showPayButton` was being ignored by Oxxo component, therefore merchants would not be able to use custom pay button. 
This PR adjusts Oxxo to properly handle the property. Its value defaults to `false` as stated in our documentation. On Drop-in , it defaults to `true`
- Added unit tests
**Fixed issue**: COWEB-1163
=> Oxxo component ignores showPayButton configuration property

packages/lib/src/components/types.ts, packages/lib/src/components/utils.test.ts, packages/lib/src/components/utils.ts
Added support for sessionResult to be forwarded to the client when using the sessions flow and completing a payment. 
Extend test-case to ensure sessionResult is no longer removed during sanitising.  
**Fixed issue**:  COWEB-1162
=> Add support for sessionResult

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/components/GooglePayButton.tsx, packages/lib/src/components/GooglePay/types.ts
Adding support for [buttonRootNode](https://developers.google.com/pay/api/web/reference/request-objects#ButtonOptions) property for GooglePay.
**Fixed issue**:  COWEB-1167
=> Adding buttonRootNode property to GooglePay

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/defaultProps.ts, packages/lib/src/components/Card/components/CardInput/types.ts
For COWEB-1020, which was an issue about the fact that
> The keyboard arrow buttons on iOS devices do not work for the card component's securedFields 
... we decided that if we couldn't control whether the arrow keys on the "soft" iOS keyboard worked or not then we would instead just disable them.
There's a possibility however that the fix we put in place in #1581 is causing a11y issues by interfering with the navigation within the VoiceOver screenreader
In order to test this, this PR adds a config option `disableIOSArrowKeys:true|false` that allows us to control whether the feature from #1581 is applied or not
Setting `disableIOSArrowKeys` to `true` (which is also the default value) enables the disabling of the iOS arrow keys.
Setting `disableIOSArrowKeys` to `false` turns off the …
=> Added config option "disableIOSArrowKeys"

packages/lib/src/components/internal/PersonalDetails/validate.ts
Adding field specific errors for first & last name fields in the PersonalDetails component now that the translations are available. This brings the errors on these fields into line with a11y guidelines.
Translated field specific errors are used for these fields
**Relates to issue**:  FOC-66770
=> Adding field specific errors for fields in the PersonalDetails component

packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts, packages/lib/src/components/ThreeDS2/components/Challenge/DoChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/DoFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/config.ts, packages/lib/src/components/ThreeDS2/types.ts, packages/lib/src/core/RiskModule/components/DeviceFingerprint/GetDeviceFingerprint.tsx, packages/lib/src/core/RiskModule/constants.ts, packages/lib/src/utils/get-process-message-handler.test.ts, packages/lib/src/utils/get-process-message-handler.ts
A new scenario with  post messages in the 3DS2 flow has become possible whereby a post message from a legitimate (i.e. Adyen) domain is sent but without any data that we need to process.
Previously we had considered all post messages from the Adyen domain, within the 3DS2 flow, to indicate an "end state" - a point at which we stop listening for such messages, settle Promises and proceed with finalising the 3DS2 process.
This new scenario means we need to detect it, ignore it & carry on listening.
As a side note the source of this unexpected post message is in a 3rd party dependency, corejs3, which (for some reason) sends out this message event when it detects an iOS device. More details can be found in the ticket mentioned below.
Vast amount of manual testing both with regular components …
=> Fix/handling unexpected post message in 3DS2

packages/lib/src/components/Ach/components/AchInput/components/AchSecuredFields.tsx, packages/lib/src/components/internal/SecuredFields/utils.ts
Since the ACH bank account number can be 4-17 digits, with no standard format - the placeholder can't be specific enough to imply how many digits can be added there. So we have decided to remove it.
Likewise we have removed the formatting that added a space every 4 digits.
If the merchant _really_ wants a placeholder they can add one through a translations config object - but by default the placeholder has been removed
All tests pass
**Fixed issue**:  COWEB-1166
=> Remove ach placeholder and formatting.

packages/e2e/tests/_models/CardComponent.page.js, packages/e2e/tests/cards/avs/avs.partial.clientScripts.js, packages/e2e/tests/cards/avs/avs.partial.test.js, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/components/internal/Address/constants.ts, packages/lib/src/components/internal/Address/validate.ts
When setting `billingAddressMode` to `partial` , the postal code wasn't being validated as there was no country set.
In this PR, we add support for validating the postal code field for such case. In order to trigger the validation, the country needs to be set in the Component configuration. Example:
```js
const card = checkout.create('card', {
billingAddressRequired: true,
billingAddressMode: 'partial',
data: {
billingAddress: {
country: 'US'
}
}
});
```
- Added e2e tests
**Fixed issue**:  COWEB-1138
=> Validating postal code when billingAddressMode is partial

packages/lib/src/components/BacsDD/components/BacsInput.tsx, packages/lib/src/components/internal/Address/components/CountryField.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.tsx, packages/lib/src/components/internal/Address/components/StateField.tsx, packages/lib/src/components/internal/CompanyDetails/CompanyDetails.tsx, packages/lib/src/components/internal/FormFields/Checkbox/Checkbox.scss, packages/lib/src/components/internal/FormFields/ConsentCheckbox/ConsentCheckbox.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/IbanInput/IbanInput.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx
Following advice from our external a11y assessment the Error icon `alt` tag is always set & reads "Error" (or translated equivalent)
Address component
PersonalDetails component
Credit card with address
Vouchers
- Bacs
- Boleto
- Doku
- EContext
Open Invoices
- Atome
- Affirm
- Facilypay
- Ratepay
- Afterpay (b2b)
=> alt tag on error icon reads "Error"

packages/lib/src/components/Pix/PixInput/PixInput.tsx
The PixInput element controls the logic behind the validation of the Pix element, so we want to keep it instantiated. We should however hide it from the DOM in case there's nothing to render like the other elements (ie: Redirect).
Tested by calling `.submit` on all the variations of `showPayButton` and `personalDetailsRequired`.
=> Fix Pix input element not hidden

packages/e2e/package.json, yarn.lock
- Updating testcafe to latest version
- As we don't use typescript with testcafe, there is no breaking changes ([more here](https://testcafe.io/documentation/404017/recipes/migration/testcafe-2-0-migration-guide)) 
- I ran e2e tests and got the same result as the previous version
=> Testcafe dependency update

packages/lib/src/components/Dropin/components/DropinComponent.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.tsx, packages/lib/src/components/Dropin/types.ts, packages/playground/src/pages/Dropin/session.js, yarn.lock
In the `PaymentMethodItem` component, the `<li>` and `<button>` elements had the `onClick` callback object. If the shopper would click in the `<button>` element, that would eventually also trigger the `onClick` of the `li` element, therefore calling `onSelect` multiple times.
Changes:
- Removed the `onClick` callback of the `button` element
- Renamed `isDisabled` to `isDisablingPaymentMethod` for more clarity of what is happening
- Fixed some typescript Types
- Added unit tests
- Ran e2e tests
**Fixed issue**:  #1832 / COWEB-1169
=> Fix Dropin onSelect callback being triggered multiple times

renovate.json
- Configuring Renovate to create dependency updates only for the `lib`, `server` and root `package.json` files, so it will stop spamming with useless dependency updates (The other packages are going to be deprecated/removed as we move to playwright and to storybook)
=> Adjusting Renovate to check the relevant projects

packages/lib/src/components/PayNow/config.ts
* Adjust PayNow timer from 15 minutes to 3 minutes.
=> Adjust PayNow countdown time to 3 minutes

renovate.json
- Renovate is having issues to update dependencies now (conflicts with package-lock files). Seems like it is depending on the ignored paths somehow.
=> Renovate: Reverting ignorePaths change

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/core/Errors/AdyenCheckoutError.ts, packages/lib/tsconfig.json
The objective of this PR is to standardized the behaviour of popup cancellation between Google Pay and other window cancelations (ie: Paypal). 
- Tested generating error on Chrome, Firefox, Safari 
#1877
=> Fixes errors being thrown for Google Pay cancellation

packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.scss
Fixed the spacing in the credit card brand animations
Tested in playground, changes in the following screen recording:
https://user-images.githubusercontent.com/11157209/214022759-f2043916-3859-44cb-9101-f0349536d29f.mov
=> Fixed credit card brand animation

packages/lib/src/components/internal/IbanInput/IbanInput.test.tsx, packages/lib/src/components/internal/IbanInput/IbanInput.tsx, packages/lib/src/components/internal/IbanInput/validate.test.ts, packages/lib/src/components/internal/IbanInput/validate.ts, packages/lib/src/core/Errors/types.ts, packages/playground/src/pages/OpenInvoices/OpenInvoices.js
The `IbanInput` component wasn't propagating its errors to its parent component - neither when an input value changed nor when `showValidation` was called on the component
`IbanInput` propagates errors to its parent (tested in both `Sepa` & `OpenInvoice` components)
=> IbanInput propagates errors including on showValidation

packages/lib/src/components/Blik/Blik.tsx, packages/lib/src/components/MBWay/MBWay.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/DoChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/types.ts, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/DoFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/types.ts, packages/lib/src/components/UPI/UPI.tsx, packages/lib/src/components/helpers/QRLoaderContainer.tsx, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/Await/types.ts, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/components/internal/QRLoader/types.ts, packages/lib/src/components/types.ts, packages/lib/src/core/ProcessResponse/PaymentAction/actionTypes.ts, packages/lib/src/core/config.ts, packages/playground/src/pages/Components/Components.js, packages/playground/src/pages/Dropin/manual.js, packages/playground/src/pages/QRCodes/QRCodes.js
This PR adds a callback `onActionHandled` which can be listened to to know that an action has proceeded as planned.
For example: 
- for an action that leads to the presentation of a QR code we call this callback when the QR code image has loaded
- similarly for a 3DS2 action we call it when the generated iframe has loaded its content
- and for something that leads to an `Await` action (UPI, Blik, MBWay) we call it once the `/status` polling starts
What is received within this handler is an object describing the component and the action that has been handled,
examples:
- `{componentType: 'wechatpayQR', actionDescription: 'qr-code-loaded'}`
- `{componentType: '3DS2Fingerprint', actionDescription: 'fingerprint-iframe-loaded' }`
- `{componentType: 'mbway', actionDescription: …
=> Added onActionHandled callback

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/ClickToPay/services/create-clicktopay-service.test.ts, packages/lib/src/components/Card/components/ClickToPay/services/create-clicktopay-service.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/types.ts, packages/lib/src/components/Card/components/ClickToPay/services/utils.test.ts, packages/lib/src/components/Card/components/ClickToPay/services/utils.ts, packages/lib/src/components/Card/types.ts, packages/playground/src/pages/Cards/Cards.js, yarn.lock
- Removing the flag `useClickToPay` that explicitly enables ClickToPay for the merchant.  
We don't really need that flag anymore as we can figure out if Click to Pay should be displayed or not according to the configuration available in the card payment method object returned by the /paymentMethods response.
Removing the flag also makes the integration easier as merchants might not even need to change anything in their Card component configuration.
- Added unit tests to make sure that ClickToPay service is not created if the configuration properties are incorrect
- Tested that it still works if merchants pass the `useClickToPay` flag  (the flag will be ignored)
=> Click to Pay - Removing useClickToPay flag

packages/playground/src/config/paymentsConfig.js
- Prepping paymentsConfig so it can work with 3DS2 against API v69. (ref: https://docs.adyen.com/online-payments/migrate-to-checkout-api-v69#3d-secure-authentication-fields)
- Also fixed returnUrl to point to the right playground page
=> Prepping paymentsConfig for use with 3DS2 and API v69. 

packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx
The url for the icon used as an expiryDate hint was hardcoded to the Test environment.
It now uses the dynamic `loadingContext` to set the root for this url
expiryDate hint icon loads based on `loadingContext`
**Fixed issue**:  #1981
=> Removed hardcoded url on expiryDate hint icon

packages/lib/src/core/Analytics/Analytics.ts
A promise, which performs a server call to retrieve a new `checkoutAttemptId` in `Analytics.ts`, is throwing an "uncaught error" when in PayByLInk.
Have added a `catch` statement in which we create a `console.warn`
PayByLInk no longer throws this error
=> Fixing uncaught analytics error

packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/PayPal/types.ts
- Updated the PayPal formatProps logic, so now the Component can get the `intent` from the Component configuration, which has higher priority than the one passed in the `configuration` object which is retrieved from the Backend
**Fixed issue**:  COWEB-1154
=> PayPal - Allowing merchant to pass 'intent' property as Component configuration

packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/ClickToPayWrapper.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPLogin/CtPLogin.tsx, packages/lib/src/components/Card/components/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.tsx, packages/lib/src/components/Card/components/ClickToPay/context/ClickToPayContext.ts, packages/lib/src/components/Card/components/ClickToPay/context/ClickToPayProvider.tsx, packages/lib/src/components/Card/components/ClickToPay/services/ClickToPayService.test.ts, packages/lib/src/components/Card/components/ClickToPay/services/ClickToPayService.ts, packages/lib/src/components/Card/components/ClickToPay/services/create-clicktopay-service.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/AbstractSrcInitiator.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/MastercardSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/VisaSdk.ts, packages/lib/src/components/Card/components/ClickToPay/services/sdks/types.ts, packages/lib/src/components/Card/components/ClickToPay/services/types.ts, packages/lib/src/components/Card/types.ts, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Dropin/session.js
- The shopper should be able to try to authenticate with telephone number AND email. The previous logic took into account that would be allowed only one type of login, which was incorrect. This PR renames the property `shopperIdentityValue` to `shopperEmail`, and also introduced `telephoneNumber` which will be used anytime soon as soon as this feature is enabled for all network schemes.
- Added new property `disableOtpAutoFocus` which disables the autofocus on the OTP field once the Component is displayed, or when the Shopper triggers the 'Resend OTP' flow. By default, the property value is `false` and the autofocus will be enabled
- Added internal property of the Card component named `_disableClickToPay` , which can be used by us to disable the Click to Pay in the Card component, so we …
=> Click to Pay - disabling OTP auto focus and renamed shopper identity parameters

packages/lib/src/components/Blik/Blik.tsx
When access Blik `component.data` before component rendered it throw an error because `state` is undefined during `formatData` call.
It works only if BlikInput is rendered and onChange runs inside useEffect at least once.
```js
const component = checkout.create('blik', {});
component.mount('.blik-field');
console.log(component.data); // throw error
```
=> Optional Chaining for Blik Code

packages/e2e/tests/bacsDD/bacs.clientScripts.js, packages/e2e/tests/cards/Bancontact/bancontact.clientScripts.js, packages/e2e/tests/cards/binLookup/responseAndCallbacks/binLookup.clientScripts.js, packages/e2e/tests/cards/binLookup/ui/handlingErrors/unsupportedCardErrors.clientScripts.js, packages/e2e/tests/cards/dualBranding/binLookup.branding.reset.clientScripts.js, packages/e2e/tests/cards/dualBranding/dualBranding.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.default.size.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.handleAction.clientScripts.js, packages/e2e/tests/cards/utils/threeDS2Utils.js
Fixing existing e2e tests most of which were failing because of the presence of ClickToPay (which was slowing things down &/or adding unexpected elements to the page)
Also the 3DS2 tests were failing because the ACS simulator has added another iframe to the markup.
e2e tests are now passing
=> Fixing failing e2e tests

packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/components/DisclaimerMessage/DisclaimerMessage.scss, packages/lib/src/components/Card/components/CardInput/components/DisclaimerMessage/DisclaimerMessage.test.tsx, packages/lib/src/components/Card/components/CardInput/components/DisclaimerMessage/DisclaimerMessage.tsx, packages/lib/src/components/Card/components/CardInput/components/DisclaimerMessage/index.ts, packages/lib/src/components/Card/components/CardInput/components/StoredCardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts, packages/lib/src/core/core.ts, packages/lib/src/utils/isValidURL.test.ts, packages/lib/src/utils/isValidURL.ts
Due to the introduction of a new Danish regulation, we need to find a way to support the addition of a disclaimer message to the card components.
A new config property can now be added to a `card` or `storedCard`:
```
disclaimerMessage: {
message: 'By continuing you accept the %{linkText} of MyStore',
linkText: 'terms and conditions',
link: 'https://www.adyen.com'
}
```
This allows us to create disclaimer messages both in the form:
>"By continuing you accept the <a href="https://www.adyen.com">terms and conditions</a> of MyStore" 
and, 
>"By continuing you accept the <a href="https://www.adyen.com">terms and conditions</a>"
where "terms and conditions" is a merchant defined link (in this case to a https://www.adyen.com)
**Result:** This will add the disclaimer message as the final element …
=> New DisclaimerMessage comp to allow showing Terms & Conditions in Card

packages/lib/src/core/CheckoutSession/CheckoutSession.ts, packages/lib/src/core/Services/analytics/collect-id.ts, packages/lib/src/utils/Storage.ts
Following the reported issue (#2020) that `window.localStorage` (and `window.sessionStorage`) throw errors when they are accessed within a Dropin/Components instance that is presented in an _iframe, in a Chrome Incognito window_ - this PR provides a fallback to a non persistent form of storage to avoid these errors.
~~**TODO** The ClickToPay, checking for registered cards functionality, also seems to fail in this scenario - which requires further investigation~~
Dropin, in an iframe, in a Chrome Incognito window - doesn't throw errors related to `localStorage` or `sessionStorage`
**Fixed issue**:  #2020
=> When local storage isn't available fall back to a non-persistent storage solution

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/helpers/OpenInvoiceContainer/OpenInvoiceContainer.tsx, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.tsx, packages/lib/src/components/internal/Address/utils.ts, packages/lib/src/components/internal/CompanyDetails/CompanyDetails.tsx, packages/lib/src/components/internal/CompanyDetails/validate.ts, packages/lib/src/components/internal/IbanInput/IbanInput.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/OpenInvoice/types.ts, packages/lib/src/components/internal/OpenInvoice/utils.ts, packages/lib/src/components/internal/PersonalDetails/PersonalDetails.tsx, packages/lib/src/components/internal/PersonalDetails/utils.ts, packages/lib/src/components/internal/PersonalDetails/validate.ts, packages/lib/src/core/Errors/SRPanelContext.ts, packages/lib/src/core/Errors/SRPanelProvider.tsx, packages/playground/src/pages/OpenInvoices/OpenInvoices.html, packages/playground/src/pages/OpenInvoices/OpenInvoices.js
Following PR #2044 - this adds SRPanel functionality to the `OpenInvoices` component.
This component is similar to the `CardInput`, in that it consists of a series of child components presented together, under one parent. Thus the parent has responsibility for collating and presenting the errors from all its children.
In the case of the the `OpenInvoices` component these children can be some, or all, of the following:`CompanyDetails`, `PersonalDetails`, `IbanInput` & `Address` (both Billing and Delivery). 
=> Feature/OpenInvoice uses SRPanel

packages/lib/src/core/core.ts
`core.ts` calls `setOptions` twice during the setup for the `/sessions` flow - which has the side effect of instantiating the modules twice.
This PR prevents this and is a stopgap whilst we re-examine the startup process to investigate how we can call `setOptions` just once
Risk, Analytics & SRPanel modules are only created once
=> Stop creating double modules in /sessions flow

packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss, packages/lib/src/style/colors.scss
Adds a new colour and fixes the contrast ratio of the brand number indicator.
The new colour for the button and UI outline can be seen in this screnshot.
=> Fixes contrast ratio for button outline and brand number indicator

packages/lib/src/components/Ach/components/AchInput/components/AchSFInput.tsx, packages/lib/src/components/Giftcard/components/GiftcardNumberField.tsx, packages/lib/src/components/Giftcard/components/GiftcardPinField.tsx, packages/lib/src/components/MealVoucherFR/components/MealVoucherExpiryField.tsx
Labels for non-credit card securedField elements (ACH, Giftcard) no longer have a _for_ attribute pointing to the securedField input (since it exists in another DOM)
Manually tested ACH and both types of Giftcard comp (with & without expiryDate field)
**Fixed issue**:  #1933
=> Remove labels 'for' attribute for other, not credit card, secured fields

packages/lib/src/components/ApplePay/payment-request.ts, packages/lib/src/components/ApplePay/types.ts, packages/playground/src/pages/Wallets/Wallets.js
- `UIElement` already has `amount` passed by the Core, therefore there is no need to pass it as props
- `configuration` is passed from the paymentMethods call, so it shouldn't be required
- Adjusted `Wallets` to not use the legacy config values
**Fixed issue**:  #2074
=> ApplePay -  Fixing Typescript types and Wallets playground

packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/PaymentMethodsResponse.ts, packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/types.ts, packages/lib/src/core/ProcessResponse/PaymentMethodsResponse/utils.ts, packages/lib/src/core/types.ts, packages/lib/src/types/index.ts
The property name wasn't correct when checking for 'storedPaymentMethods'. It was written as 'storePaymentMethods'.
This PR:
- Fix the typo
- Adds typescript to that part of the code, so we don't have such mistakes again
=> Fixing storedPaymentMethods check typo

packages/lib/src/components/PayPal/defaultProps.ts, packages/lib/src/components/PayPal/types.ts, packages/lib/src/components/PayPal/utils.test.ts, packages/lib/src/components/PayPal/utils.ts
Currently Adyen web lacks the functionality to configure/customise pay-later messages if somebody is trying to integrate paypal's [pay in 4](https://developer.paypal.com/docs/checkout/pay-later/us/)
With the proposed changes the library will expose the Messages component from the paypal's sdk (refer url above)
Highlights:
- Added new configuration property for Paypal, named `enableMessages`  (default value: false) , which based on its value the SDK enables the [PayPal Pay Later Messages](https://developer.paypal.com/docs/checkout/pay-later/us/integrate/)
-NA-
=> Enable messages component for configuring pay later in Paypal

packages/lib/src/components/PayByBank/PayByBank.spec.ts, packages/lib/src/components/PayByBank/PayByBank.tsx, packages/lib/src/components/helpers/IssuerListContainer.tsx, packages/playground/src/pages/IssuerLists/IssuerLists.html, packages/playground/src/pages/IssuerLists/IssuerLists.js
Previously we cannot show/hide the pay button for the payByBank payment when there is no issuer, now it's been fixed.
- On the playground issuerlists page, set `showPayButton: false` to the `AdyenCheckout` config, the pay button hides
- On the playground issuerlists page, set `showPayButton: true` to the `AdyenCheckout` config, the pay button shows
=> Fix: open bank pay button can be toggled for no issuer list

packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleIOSTouchEvents.ts
In one of our handlers, added to deal with touch events in iOS, there was a scenario where the `input` element on which the event was fired could be of the wrong _type_. 
The cause of this seems to be when the merchant has added a custom Pay button (an `input` with `type="button"`).
The code that was then run triggered an error.
This PR wraps a `try/catch` block around the code we try to call.
Manually added `input` element, `type="button" - which re-created the error.
Adding the `try` block stops the error from happening.
**Fixed issue**:  #2046
=> Add try block round setSelectionRange call in touch handler

packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.tsx, packages/lib/src/components/Card/components/CardInput/components/CVC.tsx, packages/lib/src/components/Card/components/CardInput/components/CVCHint.tsx, packages/lib/src/components/Card/components/CardInput/components/types.ts, packages/lib/src/components/helpers/QRLoaderContainer.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/components/internal/QRLoader/types.ts, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
This PR adds the missing alternative text in some images. Mainly the available brands in the card component, the QR code component, and the CVC hint.
Note theres a few limitations with this PR. 
Not all available brands will have alt image, and they are not localised, this is something we should solve by getting this information from the backend.
If the QR code component is loaded from an action, outside of Dropin the alt is not going to be available since the `payment/` call will not retrieve the `displayName`.
=> Adds missing alternative text on some images 

packages/lib/src/components/Blik/components/BlikInput.tsx
We should block the suggested values when Blik's input field is in focus. Blik codes are not reusable and each time shopper is asked to input code generated in their issuer app so suggesting previously used values is harmful and has impact on the conversion rates especially on the web mobile.
=> Fix: turn off Blik code auto suggest

packages/lib/src/components/Boleto/components/BoletoInput/validate.ts, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/SendCopyToEmail/SendCopyToEmail.tsx, packages/lib/src/components/internal/SocialSecurityNumberBrazil/BrazilPersonalDetail.tsx
The `SendCopyToEmail` component inside the  `Boleto` component wasn't validating properly - it was sending the whole error object instead of a boolean or a string.
Recent changes in `Field.tsx` meant that, if it was told to present the error in the DOM, it _always_ expected a string.
So, there was a scenario where if the "Send a copy to my email" checkbox was checked, and the form was then validated, an error was thrown.
In addition, the `Boleto` component generally, wasn't validating properly (by generating visual error messages).
Now, `SendCopyToEmail` passes a string, `Boleto` validates correctly, and `Field.tsx` is more robust (for other scenarios where a component doesn't validate in the expected way)
`Boleto` validates correctly.
Even when it doesn't `Field.tsx` will no longer throw …
=> Ensure Boleto validates properly

packages/e2e-playwright/models/issuer-list.ts, packages/e2e-playwright/tests/issuerList/issue-list.spec.ts, packages/e2e-playwright/tests/utils/constants.ts
Attempt to fix issuer list flaky tests
Current issue: 
When playwright clicks in the select box, it moves to the next task which is to type in the filterable select field, although the field isn't ready for handling the keyboard events (sometimes it is, but sometimes it isn't). Therefore, in some cases, the filter mechanism wasn't working as expected and was taking wrong values instead of the provided ones.
The fix:
- Added a small delay when the select field is clicked, so the options can be fully rendered
- Added a small delay after typing in the field, so the UI can be properly updated with the available options
=> E2E - Fixing issuer list flaky tests

packages/e2e/tests/cards/binLookup/ui/handlingErrors/unsupportedCardErrors.test.js, packages/e2e/tests/cards/expiryDate/minimumExpiryDate.test.js, packages/e2e/tests/cards/general/general.test.js, packages/e2e/tests/storedCard/general.test.js, packages/lib/src/components/internal/Address/components/CountryField.tsx, packages/lib/src/components/internal/Address/components/StateField.tsx, packages/lib/src/components/internal/FormFields/Field/types.ts, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/types.ts, packages/lib/src/components/internal/PhoneInputNew/PhoneInput.tsx, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.test.ts, packages/lib/src/components/internal/SocialSecurityNumberBrazil/SocialSecurityNumberBrazil.tsx, packages/lib/src/core/Context/CoreProvider.tsx
The `isCollatingErrors` prop was part of the `ErrorPanel` functionality.
Now we have moved to using the `SRPanel` it is a redundant property.
(The only reason it wasn't removed in the SRPanel PR was in an attempt to keep down the number of changed files for that PR)
Have also fixed some e2e tests to reflect the new markup that has come with the a11y changes i.e. `aria-describedby` elements are _always_ in the DOM, and `label` elements for securedFields don't have a `for` attribute
All e2e tests pass
=> Removed isCollatingErrors prop since it is never used

packages/lib/src/components/internal/FormFields/Field/Field.scss, packages/lib/src/components/internal/FormFields/Fieldset/Fieldset.scss, packages/lib/src/components/internal/FormFields/FormFields.scss, packages/lib/src/style/index.scss, packages/lib/src/style/media-queries.scss
The aim of this PR is to introduce a set of tools to add responsiveness to the our code. As well as fixing CSS the responsiveness of long forms like Address and Personal Details. 
Not covered by this PR are the "field-wrapper" fields, that should be in the future merged to use the same CSS.
=> Fixes responsiveness in form fields

packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/components/StoredCardFieldsWrapper.tsx, packages/lib/src/components/Donation/components/DonationComponent.tsx, packages/lib/src/components/internal/DisclaimerMessage/DisclaimerMessage.test.tsx, packages/lib/src/components/internal/DisclaimerMessage/DisclaimerMessage.tsx, packages/playground/src/pages/Cards/Cards.js
Refactor the DisclaimerMessage component to only use the InternalDisclaimerMsgObject.
`Card`, `StoredCard`, `Donation` and `OnlineBanking` display the disclaimer message correctly.
=> Refactor(DisclaimerMessage): to use only InternalDisclaimerMsgObject

packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.test.tsx, packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.tsx, packages/playground/src/pages/Cards/Cards.js
- Fix the issue that the preselect value is not working for the Installments component
- Add tests to test brand change effect
- Let's say we have the following configuration:
```javascript
installmentOptions: {
mc: {
values: [1, 2, 3],
preselectedValue: 2
}         
},
```
- During the initial rendering, the `brand` is `card`, as we are setting the initial `installmentAmount` value to `installmentOptions?.preselectedValue || installmentOptions?.values[0]` in the `useState` hook, it sets the initial `installmentAmount` value to `undefined`.
- Then the `useEffect` is called, `newAmount` is still `undefined`
- Change the card number to a master card. As `useState` is stateful, it would NOT get called, hence the `installmentAmount` stays `undefined` at this stage. 
- However the `useEffect` …
=> Fix(installments): preselect value on brand change

packages/lib/src/utils/amount-util.ts, packages/lib/src/utils/constants/currency-minor-units.ts, packages/playground/src/config/commonConfig.js, packages/playground/src/config/getCurrency.js
We are incorrectly rounding the amount for the currency RSD in the pay button. For example the value RSD 10.45 is rendered as RSD 10 in the pay button. This only happens in the chromium-based browsers.
The root cause is the [chromium issue 1381996](https://bugs.chromium.org/p/chromium/issues/detail?id=1381996), some currencies' minimum  number of decimal points are not set correctly according to the [spec](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml).
This is a workaround solution to hard code minimum decimal points for those problematic currencies following the [same spec](https://www.six-group.com/dam/download/financial-information/data-center/iso-currrency/lists/list-one.xml).
[Adyen …
=> Fix: work around solution for some currencies not getting the correct decimal points

.gitignore, env.default, packages/playground/config/webpack.dev.js
The playground can support https conditionally.
Steps:
- create you own certificates
- change your `.env` file to include following variables
```
IS_HTTPS=true
CERT_PATH=/home/vagrant/workspace/cert/localhost.pem
CERT_KEY_PATH=/home/vagrant/workspace/cert/localhost-key.pem
```
- `CERT_PATH` and `CERT_KEY_PATH` are optional. If there is no value, `CERT_PATH` value is concatenation of `__dirname` of the `webpack.dev.js` file and `localhost.pem`.
- same logic applies to the `CERT_KEY_PATH`
The playground can run https conditionally.
=> Refactor: make playground conditionally support https

packages/lib/src/components/Ach/Ach.tsx, packages/lib/src/components/Ach/components/AchInput/AchInput.tsx, packages/lib/src/components/Ach/components/AchInput/types.ts, packages/lib/src/components/SecuredFields/SecuredFieldsInput/SecuredFieldsInput.tsx, packages/lib/src/components/internal/Address/types.ts
The was a bug passing the resource prop to the SecureFields component use in custom card integrations. The prop was not being passed because it uses "extractProps" function to get the correct props.
This also didn't trigger a linting issue because the function where resources was being used is not part of the Class component but instead it's "bound" to it.
Tested the scenario that cause the crash.
Go into custom card integration (`securefields` component) and start typing credit card information. It should crash.
#2135
=> Fix getImage crashing custom card integration

packages/lib/src/components/ApplePay/types.ts
Raised a change to make the `totalPriceLabel` property optional within the `ApplePayElementProps` type.
According to the example in the docs [here](https://docs.adyen.com/payment-methods/apple-pay/web-component?tab=_code_payments_code__2#use-adyens-apple-pay-certificate), when you set up an `applepay` web component you only need to pass the `amount` and `currencyCode` properties. However, within the `ApplePayElementProps` type the `totalPriceLabel` property is required, which causes a typing issue when initialising the component via the `checkout.create()` method as it doesn't correctly identify the `applePayConfiguration` object as an `ApplePayElementProps` type.
The result of this is a typescript error when trying to use the `.isAvailable()` method on the component as defined in Step 3 …
=> make `totalPriceLabel` optional in `ApplePayElementProps` type

packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/requests.ts, packages/lib/src/components/GooglePay/types.ts
Add parameter to request GPay `assuranceDetails`.
=> Add parameter to request GPay `assuranceDetails`

packages/lib/src/components/internal/IbanInput/IbanInput.tsx
The a11y audit pointed out that not all attributes were being correctly set in the Sepa PM.
This PR adds a `name` property to the `ownerName` & `ibanNumber` `Field` component. 
This will ensure that: 
- the `label` gets a `for` attribute, which will point to the `id` on the input
- the `input` will get the expected `id`, and will have an `aria-describedby` by attribute that points to the `id` of the corresponding error element
- the error element gets its `id` set
Seps fields are now correctly marked up
**Fixed issue**:  fixes issues in a11y retest report (instanceID: 2047688059)
=> Added name property to Sepa ownerName & ibanNumber fields

packages/e2e-playwright/app/config/webpack.config.js, packages/e2e-playwright/app/src/pages/CustomCards/CustomCards.html, packages/e2e-playwright/app/src/pages/CustomCards/CustomCards.js, packages/e2e-playwright/app/src/pages/CustomCards/customCards.config.js, packages/e2e-playwright/app/src/pages/CustomCards/customcards.style.scss, packages/e2e-playwright/models/card.ts, packages/e2e-playwright/pages/customCard/customCard.fixture.ts, packages/e2e-playwright/pages/customCard/customCard.page.ts, packages/e2e-playwright/tests/customCard/customCard.spec.ts, packages/lib/src/components/Redirect/Redirect.tsx, packages/lib/src/components/SecuredFields/SecuredFields.tsx, packages/lib/src/components/Sepa/Sepa.tsx, packages/lib/src/components/internal/Icon/Icon.tsx, packages/lib/src/core/Context/CoreProvider.tsx, packages/lib/src/core/Context/useImage.ts
This PR provides fixes instances of `getImage` crashing the application. This is because not all the providers were getting passed resources correctly.
Also the PR adds/moves some of the tests for secure fields to playwright.
- Tested making payments with SEPA, Redirect, and securefields components
- Tested reverting the changes to SEPA and Redirect CoreProvider to see if error was triggered
- Added e2e tests for secure fields component
- Check all the uses of useCoreContext to ensure only, i18n and loadingContext objects were being loaded
=> Fixes resources not being passed to provider

packages/lib/src/components/Card/types.ts, packages/lib/src/components/internal/SecuredFields/binLookup/triggerBinLookUp.ts
This PR adds a `paymentMethodVariants` array to the object sent to the merchant defined, `onBinLookup`, callback.
This is the callback we use to tell the merchant what the results of the call to the `/binLookup` endpoint were.
That means the object sent to this callback now looks something like this:
```
{
"type": "card",
"detectedBrands": ["mc"],
"supportedBrands": ["mc"],
"paymentMethodVariants": ["mcdebit"],
"brands": ["visa", "mc", "amex"],
"issuingCountryCode": "US"
}
```
The `paymentMethodVariant` represents a more granular description of the payment method, e.g. '"mcdebit"` rather than just `"mc"`. See, https://docs.adyen.com/development-resources/paymentmethodvariant.
So now, as well as telling the merchant what brands we detect the entered card number to be, and whether it is one …
=> Add a paymentMethodVariants array to the object sent to the onBinLookup callback

packages/lib/src/components/internal/FormFields/Field/Field.tsx
The a11y audit gives errors about placing `divs` inside `label` elements.
It seems that the HTML spec says that a `div` cannot go inside a `label` (which will only accept ["Phrasing content"](https://developer.mozilla.org/en-US/docs/Web/HTML/Content_categories#phrasing_content)).
Doing so cause automated HTML validators, such as https://validator.w3.org/nu/,  to throw errors.
This PR fixes this, _for most cases*_ by using a `span` element instead of the `div`.
*However components that feature select/dropdown elements e.g. issuerLists, or Address comps with country selectors, will still contain `divs` (since that is how the dropdowns are built). This will need to be addressed in a future PR
Components without dropdowns no longer have a `div` inside their `label` element …
=> Field comp stops using div element inside the label

packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Bumped securedFields version to `4.5.0` (new Webpack 5 build, smaller file size)
Have been using it locally for a couple of weeks.
All tests pass
=> Bumping sf version to 4.5.0

packages/lib/src/core/Errors/SRPanel.tsx
Set `static type` on `SRPanel`, so it doesn't have `"undefined"` in its `_id` prop
`_id` prop is properly filled
=> Set static type on SRPanel comp

packages/lib/src/components/Card/components/CardInput/components/BrandIcon.tsx, packages/lib/src/components/Card/components/CardInput/components/DualBrandingIcon/DualBrandingIcon.tsx
The brand image in the credit card, visible once a brand has been identified, should have an `alt` tag detailing the card brand, and thus making it readable by screenreaders. 
This was the case _except_  we were also adding an `aria-hidden` attribute, which hid this element from screenreaders.
This has now been fixed. 
`aria-hidden` attribute no longer set on brand or dual-brand icons
**Fixed issue**:  #1691
=> Remove aria-hidden attribute on brand icon

.changeset/honest-cherries-wash.md, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx
Because we add filled `alt` tags to the icons for the `paymentMethodItems` in the Dropin - the screenreader was reading both the paymentMethod `name` as well as the `alt` tag, effectively reading the PM name twice.
Now we only fill this `alt` tag if the PM is a `storedPaymentMethod` since this does not get a text description by default
PM names are only read out once
**Fixed issue**:  #1692
=> Prevent double readout of PM names, by a screenreader, in Dropin

.changeset/curly-cats-fold.md, packages/lib/src/components/Giftcard/components/GiftcardPinField.tsx, packages/lib/src/components/Giftcard/components/types.ts, packages/lib/src/components/MealVoucherFR/components/MealVoucherFields.tsx
We need to change the label `PIN` to `Security Code` on the 3 meal voucher Sodexo, Apetiz, Up.
- The pin field label for mealVoucher_FR_groupeup, mealVoucher_FR_natixis and mealVoucher_FR_sodexo is changed to 'Security code', the gift card pin label should NOT be changed.
- All tests passed
**Relates to ticket**:  COWEB-1226
=> fix: change meal voucher label Pin to Security code

.changeset/slimy-dots-sparkle.md, packages/lib/src/components/Dropin/components/PaymentMethod/OrderPaymentMethods.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/useBrandLogoConfiguration.ts, packages/lib/src/types/index.ts
A merchant replaced the icon for Givex in their paymentMethodsConfiguration but when their Sessions Drop-in creates an order to deal with insufficient gift card balance, the deducted balance part of the Drop-in still shows the default logo for Givex.
We need to feed the correct custom brand logo information to the `OrderPaymentMethods.tsx` component.
Hence created `useBrandLogoConfiguration.ts` to gather such information, and use it in the `PaymentMethodList.tsx`
In the playground `session.js`, setting `brandsConfiguration` for `givex` under `paymentMethodsConfiguration` when initiating `AdyenCheckout`: 
```javascript
giftcard: {
brandsConfiguration: {
givex: {
icon: 'https://upload.wikimedia.org/wikipedia/commons/7/70/Example.png',
name: 'givex Giftcard'
} …
```
=> fix(gift-card): inconsistency custom logo display

.changeset/wet-zebras-switch.md, packages/lib/tsconfig.json
We use JSDoc `@internal` annotation in some places to document that certain types are internal types, but we still want to keep those types in the exported type definition files.  This PR tweaks the tsconfig to not strip these types from the final build
**Fixed issue**: #2209
=> Typescript - Disabling stripInternal feature

.changeset/strong-snakes-attack.md, packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/PayPal/defaultProps.ts, packages/lib/src/components/PayPal/types.ts
Adding `isExpress` configuration property to PayPal component. 
If the flag is set, the `subtype` is set to `express`, which will trigger different behavior from the Backend when processing the /payments call.
- Added unit test to ensure subtype is set
- Manual test
**Fixed issue**: COWEB-1241
=> PayPal - Adding isExpress flag

packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx
This PR reverts the changes of [this PR](https://github.com/Adyen/adyen-web/pull/2081/files).
This validation is too strict and causes issues with conversion since sometimes the threeDSServerTransID's might not match due to ACS or other reasons.
=> feat: remove threeDSServerTransID check in challenge component

.changeset/tiny-wombats-count.md, packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/Dropin/components/status/Error.tsx, packages/lib/src/components/Dropin/components/status/Status.test.tsx, packages/lib/src/components/Dropin/components/status/Success.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/core/Errors/SRPanel.tsx, packages/lib/src/core/Errors/useA11yReporter.ts
- Update sr panel on payment status for drop-in and QR code
- Remove the duplicated sr panel which has the same id
Tested in drop-in and wechat payment
=> Fix: update sr panel on payment status

.changeset/forty-geckos-sniff.md, packages/lib/src/core/Errors/SRPanelContext.ts, packages/lib/src/core/Errors/SRPanelProvider.tsx, packages/lib/src/core/Errors/types.ts
Created this separate PR because Storybook throws following errors:
```
4:25:20 AM [vite] Internal server error: Transform failed with 1 error:
/home/vagrant/workspace/adyen-web/packages/lib/src/core/Errors/SRPanelProvider.tsx:17:9: ERROR: Unexpected "="
Plugin: vite:esbuild
File: /home/vagrant/workspace/adyen-web/packages/lib/src/core/Errors/SRPanelProvider.tsx:14:67
Unexpected "="
15 |    errors,
16 |    isValidating,
17 |    layout = null,
|           ^
18 |    countrySpecificLabels = null
19 |  }) => SetSRMessagesReturnObject;
``` 
```
/home/vagrant/workspace/adyen-web/packages/lib/src/core/Errors/SRPanelContext.ts:7:23: ERROR: Unexpected "="
Plugin: vite:esbuild
File: /home/vagrant/workspace/adyen-web/packages/lib/src/core/Errors/SRPanelContext.ts:7:51
Unexpected "="
5  |    srPanel: …
```
=> refactor: sr panel and provider type definitions

packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.tsx, packages/lib/src/components/Card/components/CardInput/components/BrandIcon.tsx, packages/lib/src/components/Card/components/CardInput/components/DualBrandingIcon/DualBrandingIcon.tsx, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodBrands/CompactView.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodBrands/PaymentMethodBrands.tsx, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Fixes brands icons alt text to use hard coded values. Also add bijcard. 
Checked BrandIcon, Dropin Card icons and Card Brand list. 
=> Fixes alt text for card brands

.changeset/kind-flies-know.md, packages/lib/src/core/core.test.ts, packages/lib/src/core/core.ts
It's related to the drop-in advanced flow.
There is a use case that merchants feed `paymentMethodsResponse` via the `update` function instead of passing it  while initiating the `AdyenCheckout`.
Fix the issue so that we are backward compatible.
Tested in the playground drop-in manual flow.
Pass the `paymentMethodsResponse` in the `update` function. The drop-in should render the payment methods list.
```javascript
checkout.update({ paymentMethodsResponse: await getPaymentMethods({ amount, shopperLocale }) });
```
=> fix: Core update function also updates payment methods list

.changeset/spicy-crews-worry.md, packages/lib/src/components/Klarna/KlarnaPayments.test.tsx, packages/lib/src/components/Klarna/KlarnaPayments.tsx, packages/lib/src/components/Klarna/components/KlarnaContainer/KlarnaContainer.tsx, packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx, packages/lib/src/components/Klarna/types.ts, packages/lib/storybook/stories/components/Klarna.stories.tsx
When Klarna widget is loaded inside the drop-in, the drop-in is still in 'loading' status, we need to tell dropin to be 'ready' - clikable.
When we set the following config to the checkout, the Klarna widget renders inside the drop-in and it should not block the drop-in to be clickable after loaded.
```javascript
klarna: { 
useKlarnaWidget: true 
}
};
```
**Internal ticket id**:  COWEB-1251
=> Fix: Klarna widget to make drop-in clickable after loaded

packages/lib/src/components/internal/FormFields/InputBase.tsx
Since the removal on [renderFormField](https://github.com/Adyen/adyen-web/blob/ebb6963e5446c72416200d282fd5e717fb0a3ebb/packages/lib/src/components/internal/FormFields/index.tsx#L9)`FormFields.scss` was not being imported anywhere. This fixes by importing it on InputBase.
- Open any component that has input
- Check if CSS was not missing
=> Fixes missing scss in InputBase

packages/lib/src/components/internal/SecuredFields/lib/CSF/AbstractCSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts, packages/playground/src/pages/Cards/Cards.js
Fixed bug where `cvcPolicy` & `expiryDatePolicy` could be overwritten when there were multiple card components on the same page.
For example - if a page had a `storedCard` (visible cvc) _and_ a `Bancontact card` (hidden cvc) - the "hidden" setting for the Bancontact's cvc field could end up being applied to the stored card and thus hiding its cvc field.
- Page with multiple cards shows/hides expected fields correctly
- All unit tests pass
=> Fixed bug where cvcPolicy & expiryDatePolicy could be overwritten

.changeset/good-camels-join.md, packages/e2e/tests/_models/CardComponent.page.js, packages/e2e/tests/storedCard/general.test.js, packages/e2e/tests/storedCard/storedCard.noExpiry.clientScripts.js, packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.test.tsx, packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.tsx, packages/lib/src/components/Card/components/CardInput/components/StoredCardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/components/types.ts
For some storedCards, in some regions, it is not allowed to store the expiryDate.
So when this info is not present in the `storedCardData`, we hide the readonly `expiryDate` field and send the cvc field to be full width
Manually tested with `storedCardData` that has, and doesn't have, expiryDate info
new e2e tests added
new unit test added
**Fixed issue**:  COWEB-1270
=> Hide expiryDate field on storedCards when this info is not available

.changeset/smart-yaks-behave.md, packages/lib/src/components/internal/SecuredFields/binLookup/extensions.ts
Perform extra checks that a valid value has been passed when a dual branding selection is made
An invalid value (i.e. a txvariant that doesn't match what has been returned in the `/binLookup` call) doesn't cause a fatal error
**Fixed issue**: #2319
=> Extra checks on dual branding selection

.changeset/forty-badgers-bow.md, packages/lib/src/components/Redirect/Redirect.test.tsx, packages/lib/src/components/Redirect/components/RedirectShopper/RedirectShopper.tsx, packages/lib/src/core/config.ts, packages/lib/src/utils/detectInIframe.ts
If the merchant is running their site within an iframe*, they can now specify a `redirectFromTopWhenInIframe ` boolean in the Checkout config. 
Then, if we end up with a `Redirect` action, we check for ourselves if the site is running in an iframe and, if it is, and `redirectFromTopWhenInIframe ` is set to `true`, then we will attempt to perform the redirect on the top level, parent, window rather than the window holding the iframe
**\*Caveat**:  We don't recommend the use of iframes for hosting Checkout. We cannot guarantee that all payment methods will work when inside an iframe (ApplePay, GooglePay etc). Nor can we guarantee that pages outside of our control e.g. Issuer created pages that are part of the 3DS2 process, will perform correctly.
Manually tested that both `form` submits and …
=> Add 'redirectFromTop' config prop to allow top level redirect when Checkout loaded in an iframe

.changeset/smooth-jars-buy.md, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts
SecuredFieldsProvider uses timeouts to check whether SecureFields are loaded properly. Those timeouts are not cleared when the component unmounts which causes issues if the fields have already been unmounted. This triggers the onError handler in cases where it should not.
Mounting and almost immediately unmounting adyen drop-in triggers the onError handler.
=> fix: Clear timeouts on SecuredFieldsProvider when unmounting the component

.changeset/dirty-bugs-rush.md, packages/lib/src/components/internal/IFrame/Iframe.scss, packages/lib/src/components/internal/IFrame/Iframe.tsx, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.scss, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.ts, packages/lib/src/components/internal/SecuredFields/lib/securedField/utils/createIframe.ts
This ticket solves the problem when the nonce attribute is set on the `<style>` tag, some of the inline styles set to the iframe are blocked.
The changes include subtracting those styles in a separate scss file.
How to reproduce the issue:
- Checkout the `main` branch, modify the style-loader config in the `packages/playground/config/webpack.dev.js`. This step is to allow the webpack dev server to add nonce value to style sheets (playground + adyen-web styles) 
```javascript
{
loader: 'style-loader',
options: {
attributes: {
nonce: 'dummy-nonce'
}
}
},
```
- Add the following to the `<head>` section in the `packages/playground/src/pages/Dropin/Dropin.html`
```html
<meta
http-equiv="Content-Security-Policy"
content="
script-src 'unsafe-inline' https://*.adyen.com …
```
=> fix: remove inline style applied to iframe due to CSP

packages/playground/src/services.js
Since API v70 a merchant, using a storedPM, needs to add `recurringProcessingModel: 'CardOnFile'` to the data sent to the backend when a `/payments` request is made.
This PR does this, in the Playground's `services.js` file, so that storedPM payments continue to work in the Playground when the API version is set to `v70`
StoredPM payments work (tested across v69 & v70, in Dropin, with both `sessons` and `advanced flow`. Also with standalone storedCard component)
=> Add 'recurringProcessingModel' prop when making a storedPM payment ing API v70

packages/e2e/tests/cards/errorPanel/errorPanel.avsCard.test.js, packages/e2e/tests/cards/utils/constants.js, packages/e2e/tests/issuerLists/ideal/ideal.test.js, packages/e2e/tests/storedCard/general.test.js
The `/binLookup` and `/paymentMethods` response have changed - so some of the e2e tests needed to be adjusted
(testcafe) e2e test all run
=> fixing e2e tests now /binLookup and /paymentMethods response have change

.changeset/loud-vans-burn.md, packages/lib/src/components/Sepa/Sepa.tsx
Populate data with initial values (empty strings) for `ibanNumber` and `ownerName`
Trying to access `component.data` before the component has been interacted with no longer causes an error
**Fixed issue**:  COWEB-1113
=> Populate Sepa data with initial values

.changeset/tough-fishes-exercise.md, packages/lib/src/components/index.ts
Add `klarna_b2b` tx variant in the `componentsMap`.
Tested `klarna_b2b` for country code DE, use MyStoreDemoCOM merchant account. 
**Fixed issue**:  COWEB-1277
=> feat: add klarna b2b tx_variant

.changeset/chatty-doors-cheer.md, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.test.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/InputBase.tsx, packages/lib/src/components/internal/IbanInput/IbanInput.tsx
Fixes an issue with `CtPOneTimePassword` not getting updates to the `input` element reference it relies upon
=> Click to Pay - OTP 'Resend code' fix

.changeset/good-boxes-taste.md, packages/lib/src/core/types.ts
`paymentMethodConfiguration` typescript definition does not support tx variants that are not mapped internally. If they are set, the linter will complain. This PR fixes this problem.
- Checked that following code does not trigger TS complains:
```js
directEbanking: {
name: 'Sofort Klarna'
},
}
```
**Fixed issue**:  #2320
=> Adjusting paymentMethodConfiguration type to support txVariants not mapped internally

.changeset/cyan-tools-love.md, packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx
Pass both `token` and `authorization_token`  in `KlarnaWidget` `onComplete` callback.
Tested `authorization_token` separately in session and advanced flows. 
Tested both tokens in session and advanced flows.
Tested setting `useKlarnaWidget` to `true` in above scenarios.
**Fixed issue**:  COWEB-1280
=> KlarnaWidget to use authorization token onComplete

.changeset/pink-trains-stare.md, packages/lib/src/core/types.ts
We were using [discriminating union types](https://www.typescriptlang.org/docs/handbook/unions-and-intersections.html#discriminating-unions) for the PaymentMethodsConfiguration object.
That means that, if merchant passes config like:
```ts
const config =  {
card: {
hideCVC: true,
},
directEbanking: {
name: 'Sofort'
}
};
```
The type inference for the 'card' would not work, as it will be considered as `[key: string]: UIElementProps;` according to the  discriminated union type inferred by Typescript.
In this PR, we make a union type instead. And in order to properly map non-mapped TxVariants, we should use the `any` keyword, otherwise all entry-values will fallback to `[key: string]: UIElementProps;` type
**Fixed issue**: 
#2349 
#2320
=> Typescript: Fix type for paymentMethodsConfiguration

.changeset/brown-eels-hear.md, packages/lib/package.json
The `types` field in `package.json` is no longer used if there is an `exports` field. Because of that `tsc` complains that it can not find a declaration file for the module.
=> chore: fix ts config

packages/e2e-playwright/app/src/handlers.js, packages/e2e-playwright/app/src/pages/ANCV/ANCV.html, packages/e2e-playwright/app/src/pages/ANCV/ANCV.js, packages/e2e-playwright/mocks/status/status.mock.ts, packages/e2e-playwright/models/ancv.ts, packages/e2e-playwright/package.json, packages/e2e-playwright/pages/ancv/ancv.fixture.ts, packages/e2e-playwright/pages/ancv/ancv.page.ts, packages/e2e-playwright/tests/ancv/ancv.spec.ts, packages/lib/src/components/ANCV/ANCV.tsx, yarn.lock
Updating playwright to the version supported internally
- Tests passed locally
=> Updating Playwright to 1.39.0

.changeset/old-ears-heal.md, packages/lib/src/components/internal/ClickToPay/components/CtPLoader/CtPLoader.scss, packages/lib/src/components/internal/ClickToPay/components/CtPLoader/CtPLoader.tsx
Replacing the external loading GIF by animated SVG using CSS.
=> Click to Pay - Replacing loading gif by CSS animation

.changeset/fifty-parrots-collect.md, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/components/internal/Address/components/AddressSearch.test.tsx, packages/lib/src/components/internal/Address/components/AddressSearch.tsx, packages/lib/src/components/internal/Address/types.ts, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/types.ts
The objective of this PR is to add `onAddressSelected` callback. This callback works to provide a point of integration with Address completion services that require a second callback to access additional information, such is the case of Google Place Autocomplete API.
=> Feature: Adds onAddressSelected to address lookup functionality

.changeset/light-pianos-join.md, packages/e2e/tests/cards/errorPanel/errorPanel.avsCard.test.js, packages/e2e/tests/utils/commonUtils.js, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Bumping sf version to `4.8.0` which includes a more comprehensive startup log (to help with debugging)
All e2e & unit tests pass
=> Bumping sf version to 4.8.0

.changeset/fair-masks-attend.md, packages/lib/src/components/UIElement.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/components/types.ts
Loading the logo images properly when handling qrCode/await actions. The logo type is being fetched from `paymentMethodType`, which is returned in the action object.
- Manual test
**Fixed issue**:  #2489
=> Fix: Loading logos when handling qrCode/await actions

packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.test.tsx
Increase the test coverage for KlarnaWidget
=> Add tests for KlarnaWidget

packages/lib/src/components/internal/PhoneInputNew/PhoneInput.test.tsx, packages/lib/src/components/internal/PhoneInputNew/usePhonePrefixes.test.tsx
Added tests for the PhoneInput component
=> PhoneInput: added tests

.changeset/mean-glasses-happen.md, packages/lib/src/core/CheckoutSession/CheckoutSession.ts
We weren't updating our internal `sessionData` after a new `sessionData` blob is returned from the `/setup` call.
Although the original blob remains valid, best practice says that we should always use the _latest_ `sessionData` returned by the backend
A `/payments` call made using the `sessionData` returned from the `/setup` call, instead of the one from the original `/session` call, succeeds in making a payment.
=> Update sessionData after /setup call

.changeset/gorgeous-cameras-grab.md, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.test.tsx, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/core/Services/http.ts, packages/lib/src/core/Services/payment-status.ts, packages/lib/src/core/config.ts
**Issue reproduce steps:**
- Simulate a very slow Internet condition upload and download:8kbit/s
- On https://www.mystoredemo.io/#/checkout use Wechat or any other QR payment
- Turn on the very slow internet simulation, open the network tab, notice that a series of status calls are fired without waiting for previous ones to finish
Refactored the polling mechanism using `setTimeout` together with the recursion. With this new changes we can wait for previous call to finish before starting a new one, and are able to collect the response time hence calculate the passed time more accurately.
Unit tests pass.
**Fixed issue**:  #2499
=> Refactor/improve QR payments status check

packages/lib/src/components/internal/ClickToPay/components/CtPLogin/CtpLogin.test.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPSection/CtPLogoutLink.test.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPSection/CtPLogoutLink.tsx, packages/lib/src/components/internal/ClickToPay/services/sdks/MastercardSdk.test.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/SrcSdkLoader.test.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/SrcSdkLoader.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/SrciError.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/VisaSdk.test.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/types.ts, yarn.lock
- Added unit tests for the SDK's abstractions; CtPLogout; CtPLogin; and SrcLoader 
=> Click to Pay - Adding unit tests

packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.test.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleEncryption.test.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleValidation.test.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/types.ts, packages/playground/src/pages/Cards/Cards.js
Fixing unit test after merging v5 into v6
=> Fixing unit tests after merging v5 into v6

.changeset/five-bobcats-admire.md, packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts
Fixed missing bindings for `this` in `CSF.ts` caused by the introduction of a new `partial` function  in `v5.56.0`
Manually testing confirms error no longer occurs
**Fixed issue**:  some versions of iOS had started throwing errors over the missing `this` binding
=> Fix missing bindings for 'this' that had started causing errors in iOS

packages/e2e/app/src/services/index.js, packages/e2e/tests/cards/binLookup/ui/panLength/panLength.focus.kcp.test.js, packages/e2e/tests/vouchers/boleto/boleto.test.js, packages/lib/src/components/Card/components/CardInput/CardInput.tsx
Some issues existed with the current testcafe e2e tests:
- Mock data in Boleto test needed to be updated after the Riverty change
- StoredCard payment tests were failing when the API version was `70`
- An edge case existed with pasting a non KCP card into a card component set up as KCP (i.e. with KCP fields present from start). This has been fixed and a new e2e test written to catch it in the future
All e2e tests pass
=> Small fixes for e2e tests

packages/lib/src/components/Card/components/CardInput/CardInput.scss
Set background to white for 'Save card details' checkbox. 
Because when rendered in the dropin, if selected, the background of the checkbox needs to be white instead of grey (inherited from the selected payment item background)
=> style: set background to white for 'Save card details' checkbox

.changeset/curly-kangaroos-hide.md, packages/lib/src/components/Card/Card.test.tsx, packages/lib/src/components/Card/Card.tsx
There is a bug identified that we are not sending the `storePaymentMethod` to the BE for zero auth payments. Because we removed the store details checkbox for zero-auth payments in #2514, but didn't add the logic to always send the `storePaymentMethod` indicator.
Unit tests added.
=> fix: always save the payment method for zero-auth payments

packages/lib/src/components/ApplePay/ApplePay.test.ts, packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/core/types.ts
Calling `action.reject` without parameters on `onSubmit` was leading to unhandled exception error.
In this PR, we add possibility to pass GooglePay/ApplePay error to `action.reject` , in the same way as the error is passed to the `action.resolve`.
Example:
```js
onSubmit: async (state, element, actions) => {
try {
const { action, order, resultCode, donationToken } = await makePayment(state.data);
if (!resultCode) {
// Now we can pass custom error during the reject
actions.reject({
error: {
googlePayError: 'No result code error'
}
});
return;
}
actions.resolve({
resultCode,
action,
order,
donationToken,
// Error can be passed here if payment was Refused for ex.
error: {
googlePayError: 'Payment failed'
}
});
} catch (error) {
// Or just keep it empty and then we display the default error …
```
=> v6 - Fix for calling onSubmit -> action.reject with empty parameters for GooglePay/ApplePay

packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/types.ts, packages/lib/src/components/helpers/IssuerListContainer/IssuerListContainer.tsx, packages/lib/src/components/internal/UIElement/UIElement.test.ts, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/components/internal/UIElement/types.ts
- Removing `onValid` callback
- Final touch to make `isAvailable` aligned across different payment methods (GooglePay/ApplePay/ClickToPay). `isAvailble` now does not return a boolean flag anymore.
=> v6 - Removing onValid and adjusting isAvailable

packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/Dropin/components/DropinComponent.tsx, packages/lib/src/components/Dropin/defaultProps.ts, packages/lib/src/components/Dropin/types.ts, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/components/internal/UIElement/types.ts, packages/lib/src/components/internal/UIElement/utils.ts, packages/lib/src/core/config.ts, packages/lib/src/core/types.ts, packages/playground/src/handlers.js, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Components/Components.js, packages/playground/src/pages/Dropin/manual.js, packages/playground/src/pages/Dropin/session.js, packages/playground/src/pages/DropinAuto/manual.js, packages/playground/src/pages/DropinAuto/session.js, packages/playground/src/pages/DropinUMD/manual.js, packages/playground/src/pages/DropinUMD/session.js, packages/playground/src/pages/GiftCards/GiftCards.js, packages/playground/src/pages/OpenInvoices/OpenInvoices.js, packages/playground/src/pages/QRCodes/QRCodes.js, packages/playground/src/pages/Wallets/Wallets.js
- Removed `setStatusAutomatically` . That means that the UIElement will always be set to `loading` when the submit/additionalDetails is triggered.
- When the payment is finalized, the UI will be kept in the 'loading' state. The merchant needs to react upon it on the callbacks `onPaymentCompleted` or `onPaymentFailed` to display the desired UI or redirect the shopper to the next page
- The Drop-in has now the property `disableFinalAnimation` which handles if the final GIF animation will be displayed or not. If deactivated, the UI will be kept in 'loading' state , and the merchant needs to react upon that.
- Added unit tests
=> v6 - Removing setStatusAutomatically property

.changeset/moody-boxes-exist.md, packages/lib/src/components/Ach/components/AchInput/AchInput.test.tsx, packages/lib/src/components/Card/Card.test.tsx, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/CardInput/components/CardFieldsWrapper.tsx, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/components/CardInput/utils.ts, packages/lib/src/components/Card/types.ts, packages/playground/src/services.js
The fix in #2571  did not cover all use cases
For regular card, zero auth payments, we should store the payment method _only if the configuration says we should_:
- For sessions, this means if the session has been created with `storePaymentMethodMode: 'askForConsent'` (which will lead to a `configuration: {enableStoreDetails: true}` object in the `/sessions/setup` response)
- For the advanced flow, this means if the merchant has still set `enableStoreDetails: true`
What we are doing is.. if for a normal payment we would show the "Save for my next payment" checkbox, for a zero-auth payment we effectively click the checkbox on behalf of the shopper, _if_ we are allowed to.
To this end, in the `Card` component I have created a new, separate property `showStoreDetailsCheckbox` which is solely …
=> For zero auth payments, only store the payment method if the configuration says we should

.changeset/cool-zebras-whisper.md, packages/e2e-playwright/models/dropinModelUtils/getDropinCardComp.ts, packages/lib/src/components/BaseElement.test.ts, packages/lib/src/components/BaseElement.ts
- Fixed issue introduced by #2532.
- Sanitize `billingAddress` when making a `/payments` call. Remove `firstName` and `lastName` in the `billingAddress` for non Riverty payments.
Added unit test, and manually tested ACH, Card, Boleto and Riverty
=> fix: remove firstName lastName in the billingAddress for non Riverty payments

.github/workflows/e2e.yml
=> ci: use v71 for e2e

packages/lib/src/core/core.ts, packages/lib/src/core/utils.ts, packages/playground/src/pages/Dropin/manual.js
- Adding helper function that validates that there are no unknown properties being passed to Core. It does not validate the object itself, but it validates the keys
- The `createConfigurationKeysValidator` is just a helper to make sure that we are in sync between the `CoreConfiguration` options and the `possibleFields` array. If we add a property to `CoreConfiguration` and we forget to add to the `possibleFields`, TS will complain.  (I got this TS check idea from [here](https://stackoverflow.com/questions/60131681/make-sure-array-has-all-types-from-a-union). I am also fine to ditch it and just use a simple array to validate)
=> v6 - Logging warnings when AdyenCheckout has wrong properties

.changeset/giant-hotels-act.md, packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx
When the Combobox elements are rendered, for example the country selector. Their initial selected item is null, therefore we don't have a value to point in `aria-activedescendant` in these cases we were displaying an id of an element that didn't exist (`listItem-undefined`), now we display empty value `aria-activedescendant=""`. 
Is not clear from the spec what should be done in these scenarios but for now this seems to be the best option: https://stackoverflow.com/questions/76611272/what-should-aria-activedescendant-be-if-there-is-no-appropriate-element
- Inspected the DOM to check if indeed aria-activedescendant has empty value
- Checked Combobox still works as normal 
COWEB-1301
=> fix(a11y): Select/Combobox aria-activedescendant is now empty when list item id is null

.changeset/wise-tigers-sniff.md, packages/lib/src/components/AmazonPay/AmazonPay.tsx, packages/lib/src/components/AmazonPay/defaultProps.ts, packages/lib/src/components/AmazonPay/types.ts, packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/defaultProps.ts, packages/lib/src/components/ApplePay/types.ts, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/types.ts, packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/PayPal/types.ts, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/analyticsPreProcessor.ts, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/Analytics/utils.ts, packages/playground/src/pages/Cards/Cards.js, packages/playground/src/pages/Wallets/Wallets.js
AdyenWeb starts accepting certain config properties, related to analytics, for the Plugins team.
This config relates to expressPMs and will allow the Plugins teams to monitor when certain "wallets" are explicitly used as express payment methods.
More specifically:
- the initial analytics call will now accept an `applicationInfo` object detailing the type of Plugin used. [Reference](https://docs.adyen.com/development-resources/application-information/?tab=integrator_built_2#application-information-fields)
- when a wallet PM renders, the analytics info event it sends will contain `isExpress: boolean` & `expressPage: string` props extracted from the config sent when one of the PMs is created
Enhanced existing unit test in order to test the sanitising of the `analyticsData` object passed in …
=> Add analytics to ascertain when certain "wallets" are explicitly used as express payment methods

.changeset/quiet-teachers-unite.md, packages/lib/src/components/internal/SecuredFields/lib/configuration/constants.ts
Using securedFields v4.8.3 to handle 19 digit Diners
You can enter a 19 digit Diners PAN
=> Using securedFields v4.8.3 to handle 19 digit Diners

.github/workflows/e2e.yml, packages/e2e-playwright/models/dropin.ts, packages/e2e-playwright/models/dropinModelUtils/getDropinCardComp.ts, packages/e2e-playwright/pages/dropin/dropin.page.ts
- increase the timeout of the e2e github action
- add all api versions to test against
- modify the e2e tests to collect api response from the BE and use it to query the card element in the dropin (because BE returns different labels among versions)
- check [here](https://github.com/Adyen/adyen-web/actions/runs/8528345633) for the expected result
=> Ci run e2e against multiple api versions

.changeset/smart-tables-cry.md, packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/Dropin/components/DropinComponent.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/InstantPaymentMethods.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.tsx
Fix the bug that the drop-in is not rendered when there are only instant payments.
To reproduce:
- For the manual flow, pass the following to the checkout config
```javascript
paymentMethodsResponse: {
paymentMethods: [
{
configuration: {
merchantId: '12345678',
gatewayMerchantId: 'testMerchant'
},
name: 'Google Pay',
type: 'paywithgoogle'
}
]
},
```
- Specify the `instantPaymentTypes: ['paywithgoogle']` in the drop-in config
- The drop-in is not rendered
=> fix: show the instant payments when they are the only supported PMs

.changeset/brown-wolves-stare.md, packages/lib/src/components/Dragonpay/components/DragonpayVoucherResult/DragonpayVoucherResult.tsx, packages/lib/src/components/Econtext/components/EcontextVoucherResult/EcontextVoucherResult.tsx, packages/lib/src/language/Language.ts
For some voucher like Econtext and Dragon pay we shuold display expiration time together with the date.
Created a new i18n function to format dateTime. Also make a tittle change to make sure we are not creating a new formatter every time as it's a slow operation (according MDN).
- Tested with the mock data in the playground
- Still needs a test with the 2 payment methods test data
COWEB-1297, COWEB-1359
=> fix: display date and time in some vouchers

packages/lib/src/components/Card/components/CardInput/CardInput.scss, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.scss, packages/lib/src/components/internal/FormFields/Field/Field.scss, packages/lib/src/components/internal/FormFields/FormFields.scss, packages/lib/src/components/internal/FormInstruction/FormInstruction.scss, packages/lib/src/style/design-tokens.scss
- the selected pm border should be: #C9CDD3 outline-secondary
- change font weight for subtitle/form contextual element to 300
- space between card brands should be 4px spacer-020
=> [v6] style: improve some styles

packages/lib/src/components/Card/components/CardInput/components/AvailableBrands/AvailableBrands.scss, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodName.scss, packages/lib/src/components/internal/FormFields/Field/Field.scss, packages/lib/src/components/internal/FormFields/Field/Field.tsx
- Added box-shadow to the card brands, readjusted the margin of brands so that the box-shadow fits
- Transition on the margin for error message
- Set the `min-width` for pm label so that the `text-overflow: ellipsis;` would work
=> [v6]style: adding box-shadow to the brands, transition on margin for error messages

.changeset/long-maps-turn.md, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/constants.ts, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/Analytics/utils.ts, packages/lib/src/core/Services/analytics/collect-id.test.ts, packages/lib/src/core/Services/analytics/collect-id.ts, packages/lib/src/core/Services/analytics/types.ts, yarn.lock
PBL already has a `checkoutAttemptId` which it can use internally for it's own analytics calls.
In order to link events within the Dropin that PBL renders e.g. "payment method selected", or, "Pay button pressed" - it is necessary for PBL to pass the `checkoutAttemptId` to Checkout so it can be used as a shared identifier.
At the same time Checkout still wants to make the analytics "set up" call (the one that normally results in a `checkoutAttemptId` being sent as a response), so that it can pass in other, initial, data (like `platform, channel` etc).
The API endpoint now accepts that a `checkoutAttemptId` can now be passed to it in this "set up" call - and mirrors it back, if it is valid.
This way the Checkout flow can proceed as normal - passing in initial data and always getting a …
=> Checkout analytics can be passed a checkoutAttemptId

.changeset/serious-radios-flash.md, packages/lib/.storybook/main.css, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.test.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/OpenInvoice/useSRPanelForOpenInvoiceErrors.ts, packages/lib/src/core/Errors/utils.ts, packages/playground/src/style.scss
The PR includes:
- Fixed the `Uncaught TypeError: Cannot use 'in' operator to search for 'errorI18n' in true` when checking and unchecking the consent checkbox by setting the correct error in `OpenInvoice`
- Abstracted the logic related to the sr panel into a custom hook, added a `try ... catch` block so that errors related to the sr panel are 'handled', but we let them fail silently. By doing so, we make sure that any exceptions related to the sr panel are not blocking the logic for the `OpenInvoice` component
Added tests and all tests passed
**Fixed issue**:  COWEB-1380 & COWEB-1379
=> Fix OpenInvoice consent checkbox issue

packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/playground/src/pages/Dropin/manual.js
On [v6 - Synchronous submit with order tracking](https://github.com/Adyen/adyen-web/pull/2425) PR, we started setting the `status` to `loading` during the `onAdditionalDetails` step. (We don't do this on v5) 
Taking in consideration the Drop-in scenario, doing the above sets the Drop-in status to `loading` and therefore re-renders it, however when doing the `onAdditionalDetails`  we must not render Drop-in again and we should render the `sucessfull` or `error` state based on the API response.
This problem could be seen after handling the 3DS challenge iframe or when processing the completion of a voucher/qr code payment, where the `onAdditionalDetails` is triggered.
=> v6 - Calling onAdditionalDetails without setting status

.changeset/good-fishes-admire.md, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx
Stopped logging `threeDSCompInd` and `transStatus` i.e. fingerprint and challenge result codes
**Partly relates to issue**:  AUTHN-1922
=> Don't log threeDSCompInd or transStatus from 3DS2 process

.changeset/dry-tomatoes-allow.md, packages/lib/src/components/ANCV/ANCV.tsx, packages/lib/src/components/UIElement.tsx
This PR was original intended to fix a bug in ANCV where it always made new `order` calls. This was an issue if ANCV was not the first partial payment method, ie: Giftcard -> ANCV, or ANCV -> ANCV.
To fix this issue a check was introduce to use an existing order. The problem is that in the process it was notice that passing a different Class instance function to `payButton` was causing it to dereference `this.props` and use the one from `payButton` instead of `UIElement`/`ANCVElement`.
The solution was to use `submit` in the `payButton`. The problem is that `submit` only really gets reimplemented in express payment methods. This also lead to realise that contrary to what we do in gift card, this is probably the most correct way. It was because of this also necessary to change `onSubmit` …
=> Fix: ANCV ignoring existing orders & not working as intended via custom payButton

packages/lib/src/components/CashAppPay/components/CashAppComponent.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPCards/CtPCards.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPLogin/CtPLogin.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePassword.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPResendOtpLink.tsx, packages/lib/src/components/internal/ClickToPay/services/sdks/AbstractSrcInitiator.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/MastercardSdk.ts, packages/lib/src/components/internal/ClickToPay/services/sdks/VisaSdk.ts, packages/lib/src/components/internal/ClickToPay/services/utils.ts, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/core/core.ts, packages/lib/tsconfig.json
- Adjusted `tsconfig.json` to use `strict: true` and fixed some lint issues on try-catch blocks
We can start enforcing the strict rules by tackling the deactivated rules from tsconfig file one by one (Example: we can remove a rule, then fix the lint issues and create a PR for that specific fix)
=> v6 - Enabling typescript strict mode 

packages/e2e-playwright/package.json, packages/e2e/package.json, packages/lib/.storybook/main.ts, packages/lib/package.json, packages/lib/src/components/internal/CompanyDetails/CompanyDetails.tsx, packages/lib/src/components/internal/FormFields/InputBase.tsx, packages/lib/storybook/stories/dropin/Dropin.stories.tsx, packages/lib/storybook/stories/internals/PhoneInput.stories.tsx, packages/lib/vite.config.ts, packages/playground/package.json, yarn.lock
- Bumping lib versions. Most relevant updates are `preact`,  and `storybook` that got migrated to v8
- Bumping alpha version to alpha6
- Storybook 8  requires a `vite.config.ts` defined, so I added it
=> v6 - Updating dependencies and bumping alpha version

packages/lib/src/components/Redirect/Redirect.test.tsx, packages/lib/src/components/internal/IbanInput/IbanInput.test.tsx
Some unit tests were giving false positives i.e. passing _without_ running all their assertions, because of incorrect usage of `setTimeout`
They were using `setTimeout` without also setting and calling Jest's `done` function. In effect this meant that the code within the `setTimeout` block was not being run
Affected unit tests now run _all_ their assertions
=> v5 Fixing unit tests that were giving false positives

.changeset/tricky-impalas-accept.md, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/core/Analytics/analyticsPreProcessor.ts, packages/lib/src/core/Analytics/constants.ts, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/Analytics/utils.ts, packages/playground/src/pages/Cards/Cards.js
3DS2 log events have new, `subType` property, describing the nature of the event e.g. `fingerprintIframeLoaded` or `fingerprintCompleted`
Whilst the `fingerprintCompleted` also comes with a new `result` property describing the type of completion e.g. `success`, `failed`, `timeout` etc
This is a cherry-pick of the functionality from the v6 branch
Manual testing that all expected `subTypes` & `results` are added (v6 version has actual unit tests covering this)
All other unit tests pass
=> v5 Adding subType to 3DS2 analytics events

packages/e2e-playwright/tests/issuerList/issuer-list.spec.ts, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/types.ts, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/types.ts, packages/lib/src/components/ThreeDS2/types.ts, packages/lib/src/core/config.ts
Recent changes in internal data verification within the 3DS2 components mean we don't recognise `http://` domains as valid for the related acs/issuer URLs: `threeDSMethodURL` & `acsURL`.
_However_ the checkoutshopper demo, when run on `localhost:8080` generates `http` protocols for these urls
Not wanting to have to create new config properties for this internal "edge case" - this PR adds an exception to our url validation rule base on the existing `environment`, and new, `environmentUrls` config properties
Manual UMD build, tested in checkoutshopper demo, at localhost:8080,
=> v6 Allowing 3DS2 in checkoutshopper demo to work on localhost

.changeset/grumpy-worms-carry.md, packages/lib/src/components/GooglePay/GooglePay.tsx
Adding `origin` to `state.data` allows Card payments in GooglePay to follow the native 3DS2 checkout flow.
Without this property the ` /payments` request triggers the 3DSInMDFlow (redirect).
NOTE: this issue has already been addressed in v6 
Manually tested: Card payment in GooglePay, leads to native 3DS2 challenge
**Fixed issue**:  COWEB-1222, #2681
=> v5 GooglePay adds origin to state.data

.changeset/eleven-students-hunt.md, packages/lib/src/components/Ach/Ach.tsx, packages/lib/src/components/BankTransfer/BankTransfer.tsx, packages/lib/src/components/Blik/Blik.tsx, packages/lib/src/components/CashAppPay/CashAppPay.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.scss, packages/lib/src/components/Multibanco/Multibanco.tsx, packages/lib/src/components/helpers/IssuerListContainer.tsx, packages/lib/src/components/helpers/QRLoaderContainer.tsx, packages/lib/src/components/internal/RedirectButton/RedirectButton.tsx, packages/lib/src/core/core.misc.test.ts
ACH and some other stored payment methods do not respect `showPayButton` config.
This hopefully fixes that by moving the responsibility to the RedirectButton component.  Together with that there's a small CSS fix to ensure we don't display extra bottom margins if there's no content.
* Set Dropin to `showPayButton` false
#2554
=> Fix: ACH not respecting showPayButton

.changeset/purple-kids-ring.md, packages/lib/src/core/Services/http.ts, packages/lib/src/core/Services/sessions/setup-session.ts, packages/playground/src/pages/Dropin/session.js
- The error message "Invalid ClientKey" is misleading. Now we are returning more meaningful error message containing the actual error in it;
- The full error object is assigned to the  `AdyenCheckoutError` property `cause` and it can be inspected properly;
=> Sessions - Replacing "Invalid ClientKey" error message with more meaningful error

packages/e2e/app/src/pages/IssuerLists/IssuerLists.js, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/useSRPanelForCardInputErrors.ts
Similar to how `OpenInvoice' works, the `CardInput` component now uses a custom hook for setting and clear errors in the `SRPanel`
All tests pass
=> [v6] card input has custom hook for sr panel

packages/lib/src/components/Dropin/components/DropinComponent.tsx
In `handleDisableStoredPaymentMethod ` in the `DropinComponent` we were searching the wrong array of elements when looking for a storedPM that we've been instructed to remove
A storedPM is now found and removed from the UI
=> v6 correctly remove stored pm from the UI

packages/lib/src/components/Dropin/components/DropinComponent.scss
Okay found the issue, comes form the new dropin expanding animations CSS (which is very clever). 
Unfortunately aria-hidden is a bit tricky and doesn't actually hide things in terms of focus, just a11y tree.
Had to experiment with a few fixes to not break the animation but I think adding visibility: none does the trick in the most simple and clean way.
=> [V6] fix pm details not hidden

packages/e2e-playwright/models/redirect.ts, packages/lib/src/components/internal/SecuredFields/lib/constants.ts
Bumped sf version to 5.2.1 - so now Enter key presses in securedFields always force validation/submit
Also fixed playwright redirect.spec.ts after third party change to the markup in the redirect page for iDEAL
=> Bumping sf version to 5.2.1

.changeset/chilly-bikes-begin.md, packages/e2e-playwright/models/redirect.ts, packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.test.tsx, packages/lib/src/components/Card/components/CardInput/components/Installments/Installments.tsx, packages/lib/src/components/internal/Address/components/ReadOnlyAddress.tsx, packages/lib/src/components/internal/FormFields/ConsentCheckbox/ConsentCheckbox.tsx, packages/lib/src/components/internal/FormFields/Field/Field.tsx, packages/lib/src/components/internal/FormFields/Fieldset/Fieldset.tsx, packages/lib/src/components/internal/FormFields/RadioGroup/RadioGroup.tsx, packages/lib/src/components/internal/FormFields/RadioGroup/types.ts, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx, packages/lib/src/components/internal/FormFields/Select/types.ts
The Installments component was incorrectly set up.
It should always show a label with translatable text above it's radio button (or dropdown) elements.
In one case (dropdown) we were retrieving the label but not displaying it. In the other case (radio button group) we were never even creating the labelling element.
This PR fixes that
Manually tested that the label shows up in both cases.
Added new condition to existing unit test
All existing unit tests pass
**Fixed issue**:  #2609
=> Installments component shows a translatable label above its fields

packages/lib/src/components/Card/Card.tsx
- Card component overrides UIElement `payButton` function but it wasn't using the same Typescript types. The Angular setup complains about it and does not let the project build, forcing the dev to use @ts-ignore
=> v6 - Fixing Card 'payButton' typescript type

packages/lib/src/core/config.ts
Fix so `onOrderCancel` can be passed as part of core configs like the rest of the order callbacks. 
=> [V6] Fix onOrderCancel in generic options

packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodsContainer.tsx, packages/lib/src/core/core.misc.test.ts
Changes the payment method list from `ul` > `li` markup to non semantic `div` with `role=radiogroup` and buttons `role=radio`. 
The order payment method list stays the same as there's no interaction.
=> [v6] fixes pm list markup removing ul for div

.changeset/sixty-phones-allow.md, packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/PayPal/Paypal.tsx, packages/lib/src/components/PayPal/components/PaypalComponent.tsx
- `onApprove` was undefined due to the `void` operator
- Added test to cover that callbacks are passed to the Component
=> PayPal onApprove callback fix

.changeset/weak-kings-guess.md, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts
Currently we do not send the initial setup call on the SDK side if merchants disable analytics.
This is reducing our visibility on merchant integrations.
So now we will always make the initial setup call - as this call is really just about the SDK usage and does not track any shopper interactions.
We now only use the merchant setting `analytics.enabled = false` to prevent subsequent `info`, `log` and `error` analytics events
Adjusted unit tests accordingly
Relates to issue: COWEB-1412
=> Always make analytics /setup call

.changeset/dirty-items-unite.md, packages/lib/src/utils/constants/currency-decimals.ts, packages/lib/storybook/utils/get-currency.ts
In v6 we added new locales: Iceland and Bulgaria.
This PR also adds the necessary currency information for these two, non-Euro, countries
Manually tested in Chrome, Firefox  & Safari that currency is identified and formatted
=> Add missing currency information for Iceland and Bulgaria

.changeset/sour-forks-care.md, packages/lib/src/components/Dropin/components/PaymentMethod/OrderPaymentMethods.tsx, packages/lib/src/types/global-types.ts
We need to distinguish multiple ANCV payment in the order. For this we are going to use generic `label` field that comes from the backend.
- Created ANCV partial payment, it shows ANCV ID in Order Item
=> Show ANCV id in order item

.github/workflows/check-release-build.yml, .github/workflows/release-build.yml
- Add `.github/workflows/check-release-build.yml` to check the latest commit message of `main`. If it contains '[ci] release main', trigger release-build.yml
=> ci: trigger the release build automatically

.github/workflows/check-release-build.yml
Use exit 0 to indicate the job finishes successfully even when skipping the build.
=> ci: update check-release-build.yml

.changeset/late-kings-call.md, packages/lib/src/components/internal/Address/validate.test.ts, packages/lib/src/components/internal/Address/validate.ts, packages/lib/storybook/helpers/checkout-handlers.ts, packages/lib/storybook/stories/internals/Address.stories.tsx
Makes postal code validation rules same as description. Also add AddressElement to Storybook.  Adds some test to validate.
As I was writing the test I decided to write some additional tests for some more countries, and quickly found out that are some scenarios that we might not be validating correctly (with the validator alone). 
It's okay because these scenarios get validated correctly at the end but I left the tests in there so we can maybe decide to fix this in the future.
Also for future reference there's [this giant list from the European Central Bank](https://www.ecb.europa.eu/stats/money/aggregates/anacredit/shared/pdf/List_postal_code_formatting_rules_and_regular_expressions.xlsx) that has a pretty comprehensive list of regex and validation rules.
* Added tests
* Tested in …
=> Fixes LT postal code

.changeset/late-kings-call.md, .changeset/yellow-crabs-do.md, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem.tsx, packages/lib/src/components/internal/Address/validate.test.ts, packages/lib/src/components/internal/Address/validate.ts, packages/lib/src/components/internal/Button/Button.scss, packages/lib/src/components/internal/Button/Button.tsx, packages/lib/storybook/helpers/checkout-handlers.ts, packages/lib/storybook/stories/internals/Address.stories.tsx
Cherry-pick for:
Fixes Lithuanian postal code to support 4-5 digits and LT prefix (https://github.com/Adyen/adyen-web/pull/2822)
Improves acessibility removing region on payment method item and button loading state (https://github.com/Adyen/adyen-web/pull/2816)
=> Chore cherry-pick 6.1.1 to v5

packages/e2e/package.json, packages/e2e/tests/bacsDD/bacs.clientScripts.js, packages/e2e/tests/cards/dualBranding/binLookup.branding.reset.clientScripts.js, packages/e2e/tests/cards/dualBranding/dualBranding.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.clientScripts.js, packages/e2e/tests/cards/threeDS2/threeDS2.handleAction.clientScripts.js, packages/lib/src/components/components-name-map.ts, yarn.lock
- Upping testcafe version
- Fixing tests that were failing because `ClickToPay` is returned in the `/paymentMethods` response
- Fixing a component name mapping for `BacsDirectDebit`
All testcafe e2e tests pass
If the merchant supports `BacsDirectDebit` but forgets to import it in the minimal `Dropin`, the correctly worded warning message is given
=> Upping testcafe version

.changeset/stale-toys-smash.md, packages/e2e-playwright/tests/issuerList/issuer-list.spec.ts, packages/lib/src/components/ApplePay/ApplePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/PayPal/Paypal.test.ts, packages/lib/src/components/Pix/Pix.test.ts, packages/lib/src/components/internal/BaseElement/BaseElement.ts, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/constants.ts, packages/lib/src/core/Analytics/utils.ts
This PR restores the changes from the (previously approved PR) #2792:
>Currently we do not send the initial setup call on the SDK side if merchants disable analytics.
>This is reducing our visibility on merchant integrations.
>
>So now we will always make the initial setup call - as this call is really just about the SDK usage and does not track any shopper interactions.
>We now only use the merchant setting `analytics.enabled = false` to prevent subsequent `info`, `log` and `error` analytics events
In addition, since we will always have a `checkoutAttemptId`, `BaseElement` no longer sends `"do-not-track"` when adding the `checkoutAttemptId` to the component's `paymentMethod` data.
In the case that the retrieval of a `checkoutAttemptId` fails - the value `"fetch-checkoutAttemptId-failed"` …
=> Always make call to analytics setup endpoint

.changeset/swift-emus-complain.md, packages/lib/src/components/ApplePay/types.ts
Since it's declared globally we can not expect ApplePaySession to always be available in the Window interface.
=> ApplePaySession is not always available in Window

.changeset/purple-rules-jump.md, packages/lib/src/components/Dropin/elements/createElements.test.ts, packages/lib/src/components/Dropin/elements/createElements.ts, packages/lib/src/components/Dropin/elements/filters.ts
`createElements` function was first creating the payment method element and then filtering out the non-supported ones. That was leading to the creation of the Click to Pay component, which eventually would load the 3rd party SDK's.
This PR makes sure to first filter out the non-supported drop-in payment methods, to then create their payment method elements
- Tested auto e umd bundles. Added unit tests
=> Dropin - Filtering out unsupported payment methods before creating the payment method components

.changeset/polite-timers-sniff.md, packages/lib/src/core/CheckoutSession/CheckoutSession.ts, packages/lib/src/core/CheckoutSession/types.ts, packages/lib/src/core/Services/sessions/setup-session.ts
Forward browserInfo from the SDK onto the internal /setup request, so it can be passed on by the backend to the Checkout.
COWEB-1391
=> Send browser info on setup

.changeset/rotten-flies-bathe.md, .github/workflows/npm-publish.yml, packages/lib/.gitignore, packages/lib/package.json
Webpack 4 does not use the 'exports' field in the 'package.json' for the module resolution. This leads to projects using webpack4  not being able to import the styles from `@adyen/adyen-web/styles/adyen.css` . 
The temporary solution is to import directly using the file path `@adyen/adyen-web/dis/es/adyen.css`.
To solve that, the prepublish pipeline was adjusted to create a folder 'styles' and then push the CSS file there. 
By doing that, Webpack 4 projects can directly import by doing  `@adyen/adyen-web/styles/adyen.css` , as it is a valid file path.
- Added the 'styles' folder to the package.json 'files' entry, so it gets added to the tarball file
- In the prepublish script, the project is build and then the styles folder is created and the file is placed there
=> v6 - Fixing styles import path for Webpack4 projects

.github/workflows/npm-publish.yml
v5 releases are being marked as 'latest' on npm. If the tag is not specified, the fallback is 'latest'.
This PR changes the publish pipeline to tag it as `v5`. 
- More can be [read here](https://www.iliascreates.com/blog/post/npm-distribution-tags/) about distribution tags
- [npm-publish](https://docs.npmjs.com/cli/v8/commands/npm-publish#tag) docs
=> v5 -  Adding tag to npm publish pipeline

.changeset/quiet-masks-agree.md, packages/lib/src/core/Errors/SRPanel.tsx
Small optimisation to only call `document.querySelector` once, rather than three times (in `SRPanel`)
=> SRPanel: small optimisation to only call document.querySelector once

.changeset/curly-balloons-rush.md, packages/lib/src/components/internal/UIElement/UIElement.beforeSubmit.test.tsx, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/core/Errors/CancelError.ts
Calling `actions.reject()` in the `beforeSubmit` callback should leave the UI in the current state.
It should not lead to a call to `handleFailedResult` which ultimately leads to a call to the `onPaymentFailed` callback and sets the UI to an error state.
This PR keeps v6 behaviour consistent with v5
Can call `actions.reject()` from `beforeSubmit` and the UI stays in its current state
Added unit tests for `beforeSubmit` resolving and rejecting
**Fixed issue**:  COWEB-1448
=> Calling actions.reject() in beforeSubmit should not lead to onPaymentFailed

.changeset/lovely-dodos-visit.md, packages/lib/src/components/UPI/UPI.test.tsx, packages/lib/src/components/UPI/components/UPIComponent/UPIComponent.tsx
Fix UPIComponent initial value for `isValid`. It should only be `true` for UPI QR.
- Added unit tests.
- Inspect `onChange` on the playground, it should output correct `isValid` value.
**Fixed issue**:  #2915
=> [v5] fix(UPIComponent): initial value for isValid

.changeset/lovely-dodos-visit.md, packages/lib/src/components/UPI/UPI.test.tsx, packages/lib/src/components/UPI/components/UPIComponent/UPIComponent.tsx
cherry pick from fe369df73c5a0d11801ba68f511b96003de8b65e
=> V6 fix initial state upi intent

.changeset/fluffy-stingrays-invent.md, packages/lib/src/utils/constants/currency-decimals.ts, packages/lib/src/utils/constants/currency-minor-units.ts, packages/playground/src/config/getCurrency.js
Revert Icelandic Krona to be treated as a currency with minor units, in order to align with our documentation
**Fixed issue**:  #2922
**Relates to**:  #2811
=> Re-treat Icelandic Krona as a currency with minor units

.changeset/cold-jeans-yawn.md, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/utils/useForm/reducer.ts, packages/lib/src/utils/useForm/types.ts, packages/lib/src/utils/useForm/useForm.ts
This PR attempts to fix the bug reported in the issue where address or field were not being pre-filled correctly. 
The issue was caused by the logic that applies on the country change hook, that resets the `stateOrProvince` Select, and re-triggers postal code validation.
This hook exists because we want to reset the `stateOrProvince` field when a country changes. This was also triggering when setting country via `setSearchData`, which lead to a race condition where `stateOrProvince` would be reset right after being set by `setSearchData`, because of the country change.
- Created custom playground, passed US address
- Switching between addresses applies the state correctly
- It works when the `billingAddressAllowedCountries` is set to just one country
- Switching to Canada, Brazil manually …
=> Fix address lookup reseting state after country

.changeset/big-geese-complain.md, packages/lib/package.json
'auto.js' code is being tree-shaken by bundlers (ex: webpack, rollup) when creating the prod build.
'auto.js' contains side effects as it manipulates the internal state of `AdyenCheckout` by adding components to it and setting the bundle to 'auto' . Therefore, it should be flagged in the `package.json` as it has `sideEffects`  in order to not be excluded by the bundlers.
Tested that 'auto' works on build bundle:
- open-wc setup (which uses rollup)
- vite 5.1.6 setup (which uses rollup)
- nuxt 3.13.2 setup (which uses vite which uses rollup)
- next 14.2 setup (which uses webpack 5)
- react-scripts 4.x (which uses webpack 4)
**Fixed issue**: #2818
=> Fix 'auto' being tree-shaken in production builds

.changeset/old-fishes-battle.md, packages/lib/config/rollup.dev.js, packages/lib/config/rollup.plugins.js, packages/lib/config/rollup.prod.js, packages/lib/xxxx.browserslistrc
- Lowered the ECMAScript version of the modern bundle from `es2022` to `es2020` in order to support old iOS versions.
Tested on Browserstack:
- iOS 14.1
- iOS 13
- iOS 12 (requires the merchant to polyfill [Promise.allSettled](https://caniuse.com/?search=Promise.allSettled))
- iOS 11 (requires the merchant to parse the bundle to support the [spread in object literals](https://caniuse.com/mdn-javascript_operators_spread_spread_in_object_literals))
=> Compiling modern bundle using es2020

.changeset/cold-jeans-yawn.md, packages/lib/src/components/internal/Address/Address.tsx, packages/lib/src/utils/useForm/reducer.ts, packages/lib/src/utils/useForm/types.ts, packages/lib/src/utils/useForm/useForm.ts
(cherry picked from commit c5eba2a12b3bc0a68c721d6c489e68ad4d8c227f) #2926
This PR attempts to fix the bug reported in the issue where address or field were not being pre-filled correctly.
The issue was caused by the logic that applies on the country change hook, that resets the stateOrProvince Select, and re-triggers postal code validation.
This hook exists because we want to reset the stateOrProvince field when a country changes. This was also triggering when setting country via setSearchData, which lead to a race condition where stateOrProvince would be reset right after being set by setSearchData, because of the country change.
#2832
=> Fix address lookup reseting state after country (#2926)

.changeset/olive-ducks-happen.md, packages/lib/src/components/internal/SecuredFields/lib/constants.ts
Fixed issue where onBlur validation didn't fire if year in expiryDate was just one digit
Manually tested and added new unit test in SF repo
=> Upped SF version to 5.3.1

renovate.json
Re-enabling `renovate` in accordance with guidelines from AOS
The resulting `.json` file is an amalgamation of what we used to have, what AOS now recommend, and what the Android team already have place
=> Re-enable renovate in line with AOS guidelines

packages/e2e-playwright/fixtures/URL_MAP.ts, packages/e2e-playwright/models/address.ts, packages/e2e-playwright/models/base.ts, packages/e2e-playwright/models/bcmc.ts, packages/e2e-playwright/models/card-avs.ts, packages/e2e-playwright/models/card.ts, packages/e2e-playwright/models/dropin.ts, packages/e2e-playwright/models/threeds2Challenge.ts, packages/e2e-playwright/tests/e2e/card/avs.spec.ts, packages/e2e-playwright/tests/e2e/card/bcmc/dualBranding.spec.ts, packages/e2e-playwright/tests/utils/constants.ts
- Improved some models 
- Added the playwright tests
=> Add playwright tests dualBranding and avs

.github/workflows/e2e.yml, packages/e2e-playwright/tests/a11y/card/errorPanel.avs.spec.ts, packages/e2e-playwright/tests/e2e/card/avs.spec.ts, packages/e2e-playwright/tests/ui/card/expiryDate/card.expiryDatePolicies.hidden.spec.ts, packages/e2e-playwright/tests/ui/customCard/branding/customcard.plcc.luhn.spec.ts, packages/e2e-playwright/tsconfig.json
- Fix some e2e tests
- Increase the e2e ci timeout
=> Fix some e2e tests

packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.kcp.spec.ts, packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.regular.spec.ts
Exclude tests for safari that always fail on the CI due to the paste action
=> Exclude tests for safari

packages/e2e-playwright/models/card.ts, packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.kcp.spec.ts, packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.ssn.spec.ts
Using `pressSequentially` instead of `type` in `card` model. 
Stop using `mergeTests` unnecessarily.
Affected test still run
=> Using pressSequentially instead of type

.changeset/strong-boxes-suffer.md, packages/lib/src/components/Card/components/CardInput/CardInput.scss, packages/lib/src/components/Card/components/CardInput/components/BrandIcon.tsx
If an icon in the Credit card PAN field failed to load - an error handler set inline an style `display:none`.
And this inline style was never removed in the event of a subsequent, successful, icon load.
This PR fixes that
New e2e test that was previously flaky or failing due to this - now passes consistently
Manually tested.
=> Add fix to reshow card icon if previously it failed to load

.changeset/clever-pants-cover.md, packages/lib/src/components/Boleto/components/BoletoVoucherResult/BoletoVoucherResult.tsx, packages/lib/src/components/Oxxo/components/OxxoVoucherResult/OxxoVoucherResult.tsx, packages/lib/src/components/Oxxo/types.ts, packages/lib/src/components/internal/QRLoader/QRLoader.tsx, packages/lib/src/core/Analytics/Analytics.utils.test.ts
A new barcode endpoint has been created, which means there is now a new URL that can be used to generate barcodes.
This PR makes use of that new URL.
Also re-enabled 2 test suites that were being skipped due to previous, outdated, limitations on the /checkoutanalytics endpoint
Manually tested all places that we generate a barCode URL:
- `QRLoader`
- `OxxoVoucherResult`
- `BoletoVoucherResult`
**Relates to issue**:  COWEB-1368
=> Generate barCode URLs against the new endpoint

packages/e2e-playwright/tests/e2e/card/kcp/card.kcp.spec.ts
The kcp e2e tests refactor missed a couple of test conditions from the original tests.
This PR adds them back
=> Adding missing conditions from kcp tests

.changeset/new-bags-crash.md, packages/lib/src/components/Card/Card.Analytics.test.tsx, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/Redirect/Redirect.test.tsx, packages/lib/src/components/Redirect/Redirect.tsx, packages/lib/src/components/Redirect/components/RedirectShopper/RedirectShopper.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.test.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2Challenge.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.test.tsx, packages/lib/src/components/ThreeDS2/ThreeDS2DeviceFingerprint.tsx, packages/lib/src/components/ThreeDS2/callSubmit3DS2Fingerprint.ts, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.test.tsx, packages/lib/src/components/ThreeDS2/components/Challenge/PrepareChallenge3DS2.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.test.tsx, packages/lib/src/components/ThreeDS2/components/DeviceFingerprint/PrepareFingerprint3DS2.tsx, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/core/Analytics/Analytics.test.ts, packages/lib/src/core/Analytics/Analytics.ts, packages/lib/src/core/Analytics/EventsQueue.ts, packages/lib/src/core/Analytics/analyticsPreProcessor.test.ts, packages/lib/src/core/Analytics/analyticsPreProcessor.ts, packages/lib/src/core/Analytics/constants.ts, packages/lib/src/core/Analytics/types.ts, packages/lib/src/core/Analytics/utils.ts
- Send the redirect error event to the analytics when `doRedirect` throws an error
- Refine some types
- Fix some lint warnings
- Added unit test
- Tested when manually simulate an error from `doRedirect`
**Fixed issue**:  COWEB-1463
=> Send error events for redirect errors

.changeset/wet-forks-invite.md, packages/lib/src/components/Dropin/components/DropinComponent.tsx, packages/lib/src/components/Klarna/KlarnaPayments.test.tsx, packages/lib/src/components/Klarna/KlarnaPayments.tsx, packages/lib/src/components/Klarna/components/KlarnaContainer/KlarnaContainer.tsx, packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.test.tsx, packages/lib/src/components/Klarna/components/KlarnaWidget/KlarnaWidget.tsx, packages/lib/src/components/Klarna/types.ts, packages/lib/src/components/internal/BaseElement/BaseElement.ts, packages/lib/src/components/internal/BaseElement/types.ts, packages/lib/storybook/stories/components/Klarna.stories.tsx, packages/lib/storybook/stories/dropin/Dropin.stories.tsx
PR to handle the issue with multiple instances of the Klarna widget being present in the PM list
There are 2 issues:
1. When we initialise the `KlarnaWidget` it loads the KlarnaSDK, which in turn calls the callback we create (`window.klarnaAsyncCallback`), which initialises the KlarnaSDK.
- _However_, if there is a second `KlarnaWidget` in the PM list, initialising that _will not_ see the KlarnaSDK calling our callback for a second time, and so the KlarnaSDK is not re-initialised with the right `sdkData.client_token` to make the correct payment.
- This means that if you pay with the second widget, the payment from the first widget gets authorised.
2. Having solved the first problem there is now the (edge) use case that, if the shopper opens the first widget, opens the second widget, and …
=> Klarna - Fix for handling multiple instances of the widget

.changeset/dirty-lizards-thank.md, packages/lib/src/components/internal/Address/components/CountryField.tsx, packages/lib/src/components/internal/Address/components/FieldContainer.tsx, packages/lib/src/components/internal/Address/components/StateField.tsx, packages/lib/src/components/internal/Address/types.ts, packages/lib/src/components/internal/FormFields/Select/Select.tsx, packages/lib/src/components/internal/FormFields/Select/components/SelectButton.tsx, packages/lib/src/components/internal/FormFields/Select/types.ts
Fix bug where Country field and State field where not showing the correct `required` attribute.
The bug was due to never actually passing the required attribute to these fields.
=> Fix: required attribute not passed to select element

.changeset/thirty-boats-applaud.md, examples/angular/src/utils/getCurrency.ts, examples/nextjs/app/_utils/amount-utils.ts, examples/nextjs/app/_utils/getCurrency.ts, examples/nuxt/utils/getCurrency.ts, packages/lib/src/components/OnlineBankingCZ/index.ts, packages/lib/src/components/OnlineBankingSK/index.ts, packages/lib/storybook/stories/issuer-lists/OnlineBankingCZ.stories.tsx, packages/lib/storybook/stories/issuer-lists/OnlineBankingSK.stories.tsx, packages/lib/storybook/utils/get-currency.ts, packages/playground/src/config/getCurrency.js
Set `showImage: true` for both CZ and SK online banking. Images should be already available.
Also remove `SKK` support from the playground in favour of `EUR`. 
CZ component.
SK component tested, but missing the full response in Test env, should be correct in Live according to LPM.
=> Feat: enable logos for SK and CZ online banking

packages/e2e-playwright/fixtures/card.fixture.ts, packages/e2e-playwright/models/bcmc.ts, packages/e2e-playwright/tests/a11y/bcmc/bancontact.visa.a11y.spec.ts, packages/e2e-playwright/tests/e2e/card/bcmc/dualBranding.spec.ts, packages/e2e-playwright/tests/e2e/card/threeDS2/card.threeDS2.spec.ts, packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.regular.spec.ts
All bcmc tests first make call to go to a URL. This is consistent with how other tests work
Plus: added fix so 3DS2 test checks correct endpoint before assessing final result
=> All bcmc tests first make call to go to a URL

packages/lib/storybook/helpers/create-advanced-checkout.ts, packages/lib/storybook/helpers/create-sessions-checkout.ts
As agreed, stories no longer set the `onChange` callback, which was cluttering the console
=> Stop stories setting the onChange callback

packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/types.ts
The CardInput comp stores the brand detected by the internal regEx.
(This happens prior to the/binLookup call which becomes the source-of-truth for the detected brand)
This early detection will be of use in Fastlane
=> CardInput stores the brand detected by the internal regEx

packages/lib/src/components/internal/Toggle/Toggle.scss, packages/lib/src/components/internal/Toggle/Toggle.test.tsx, packages/lib/src/components/internal/Toggle/Toggle.tsx, packages/lib/src/components/internal/Toggle/index.ts, packages/lib/src/styles/mixins.scss, packages/lib/src/styles/variable-generator.scss, packages/lib/storybook/stories/internals/Toggle.stories.tsx
- Creating Toggle component based on the Bento component
- Imported`toggle` css variables from Bento to properly provide the correct colors/values to the Toggle SCSS file
(This component will be used in the fastlane branch)
- unit tests; storybook manual test
=> Toggle component

packages/e2e-playwright/models/base.ts, packages/e2e-playwright/models/card-kcp.ts, packages/e2e-playwright/tests/e2e/card/avs.spec.ts, packages/e2e-playwright/tests/e2e/card/kcpAuthentication.spec.ts, packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-amex.spec.ts, packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-mc.spec.ts, packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-visa.spec.ts
- Add e2e tests for kcpAuthentication, stored-card-amex, stored-card-mc and stored-card-visa
=> Add e2e tests for kcpAuthentication, stored-card-amex, stored-card-mc and stored-card-visa

.changeset/empty-files-cough.md, packages/lib/src/components/GooglePay/components/GooglePayButton.tsx, packages/lib/storybook/stories/wallets/GooglePayExpress.stories.tsx
Resolve the issue where `GooglePayButton` fails to pass `buttonRadius` to the `createButton` function when the value is 0.
Tested in storybook
**Fixed issue**:  #3022
=> Fix `GooglePayButton` `buttonRadius` being 0 issue

.changeset/polite-ladybugs-count.md, packages/lib/src/components/Dropin/components/PaymentMethod/DisableOneClickConfirmation.scss, packages/lib/src/styles/variable-generator.scss
- Removed `max-height` as it overflows on smaller screen, causing bad visual effect.
- Because the `max-height` is removed, we need to rewrite how we do animation. Used `display: grid` together with transition  on `grid-template-rows` instead.
- Added `animation` tokens from Bento
Tested on device mode and real devices on BrowserStack.
**Fixed issue**:  #3028
=> Fix remove stored card confirmation not responsive

.changeset/nice-bats-exist.md, packages/lib/src/components/internal/Button/types.ts, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.scss, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.test.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPOneTimePasswordInput.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPOneTimePassword/CtPOneTimePasswordInput/CtPResendOtpLink.tsx, packages/lib/src/components/internal/ClickToPay/components/CtPSection/CtPLogoutLink.scss, packages/lib/src/components/internal/ClickToPay/components/CtPSection/CtPLogoutLink.tsx
We had some elements that should have been buttons but weren't. This prevented behind activated with the keyboard. 
This PR makes them proper buttons, but also adds the `variant` link to the button types. 
To keep things consistent with the rest of the SDK the style of this buttons has also been changed from primary color (black) with underline to link color (blue) with no underline.
We also changed some markup so this might be a breaking change (UI wise), since both CSS classes and the overall markup.
All tests pass and it was manually tested with my CTP both buttons work and also the states of the OTP request message.
#3009
=> Fixes Click to Pay link looking buttons into proper buttons

.changeset/fresh-terms-love.md, packages/lib/src/components/Klarna/KlarnaPayments.test.tsx, packages/lib/src/components/Klarna/KlarnaPayments.tsx
Before v6.6.0, Klarna component was handling the action through 2 different ways:
- When using it inside Drop-in, the  Drop-in `handleAction` [was directly calling Klarna `updateWithAction`](https://github.com/Adyen/adyen-web/blob/v6.6.0/packages/lib/src/components/Dropin/Dropin.tsx#L149)  passing the action and therefore triggering the **re-render** of the Component. 
- When using it as standalone component, the UIElement `handleAction` was creating a **new**  Klarna component and passing the action as props  (as it can [be seen here](https://github.com/Adyen/adyen-web/blob/v6.5.1/packages/lib/src/components/Klarna/components/KlarnaContainer/KlarnaContainer.tsx#L7))
With the changes introduced by v6.6.0,  the `KlarnaContainer`  stopped receiving the `action` as `props`  (which caused the …
=> Klarna fix - Handling SDK action as standalone component

.changeset/sharp-worms-rescue.md, packages/lib/src/components/Card/Card.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/Card/components/CardInput/handlers.ts, packages/lib/src/components/Card/components/CardInput/types.ts, packages/lib/src/components/Card/types.ts, packages/lib/src/components/CustomCard/CustomCard.tsx, packages/lib/src/components/CustomCard/CustomCardInput/CustomCardInput.tsx, packages/lib/src/components/CustomCard/types.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProviderHandlers.ts, packages/lib/src/components/internal/SecuredFields/binLookup/triggerBinLookUp.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/CSF.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/createSecuredFields.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleEncryption.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/extensions/handleValidation.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/handleBinValue.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/handleFocus.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/handleIframeConfigFeedback.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/isConfigured.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/processAutoComplete.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/processBrand.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/validateForm.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/utils/callbackUtils.ts, packages/lib/src/components/internal/SecuredFields/lib/CSF/utils/processErrors.ts, packages/lib/src/components/internal/SecuredFields/lib/types.ts, packages/lib/src/types.ts, packages/lib/src/types/global-types.ts
More explicitly declare the types for the configuration options on the CustomCard
**Fixed issue**:  #2968
=> Improve types for CustomCard

packages/lib/.size-limit.cjs, packages/lib/.storybook/main.ts, packages/lib/.storybook/preview.tsx, packages/lib/package.json, packages/lib/src/components/PayTo/PayTo.test.ts, packages/lib/src/components/PayTo/PayTo.tsx, packages/lib/src/components/PayTo/components/MandateSummary.scss, packages/lib/src/components/PayTo/components/MandateSummary.tsx, packages/lib/src/components/PayTo/components/PayToInstructions.tsx, packages/lib/src/components/PayTo/types.ts, packages/lib/src/components/index.ts, packages/lib/src/components/internal/Await/Await.scss, packages/lib/src/components/internal/Await/Await.tsx, packages/lib/src/components/internal/Await/types.ts, packages/lib/src/components/internal/DetailsTable/DetailsTable.scss, packages/lib/src/components/internal/DetailsTable/DetailsTable.tsx, packages/lib/src/components/internal/DetailsTable/index.ts, packages/lib/src/components/internal/QRLoader/QRLoader.scss, packages/lib/src/components/internal/Voucher/Voucher.scss, packages/lib/src/components/internal/Voucher/Voucher.tsx, packages/lib/src/components/types.ts, packages/lib/storybook/public/mockServiceWorker.js, packages/lib/storybook/stories/components/PayTo.stories.tsx, packages/server/translations/en-US.json, yarn.lock
A few changes for this part of the component.
* Await can now display the amount via `showAmount` flag
* Await now has instructions like QRLoader
* Await has one final element, I just called it endSlot so it could be generic, this open to discussion.
* Moved the voucher details / list / table into a new component
* The new component DetailsTable uses a `dl` element (definition list), see docs: https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl#metadata
* Mandate Summary handles all the i18n logic to display the table, this could have been a function but seems more clean in separate component
* There's a discussion point on the length of the Mandate Summary logic block as it seems quite big, however I want to retain all the logic in one place for ease of editing, feel free to …
=> Partial feature: Payto Await

packages/e2e-playwright/tests/e2e/card/fastlane.signup.spec.ts, packages/lib/src/components/Card/components/Fastlane/FastlaneSignup.test.tsx, packages/lib/src/components/Card/components/Fastlane/FastlaneSignup.tsx, packages/lib/src/components/Card/components/Fastlane/utils/validate-configuration.ts, packages/lib/src/components/Dropin/Dropin.test.ts, packages/lib/src/components/PayPalFastlane/Fastlane.test.ts, packages/lib/src/components/PayPalFastlane/Fastlane.tsx, packages/lib/src/components/PayPalFastlane/FastlaneSDK.test.ts, packages/lib/src/components/PayPalFastlane/FastlaneSDK.ts, packages/lib/src/components/PayPalFastlane/types.ts, packages/lib/storybook/stories/wallets/Fastlane/Fastlane.stories.tsx, packages/lib/storybook/stories/wallets/Fastlane/components/CollectEmail.tsx, packages/lib/storybook/stories/wallets/Fastlane/components/GuestShopperForm.tsx
- Added the functionality to retrieve the consent UI details using Fastlane SDK (The consent UI details is used to display the sign-up component within Card)
- Added the functionality to retrieve the Fastlane session ID once the SDK is initialized (The session ID is used to PayPal internal analytics)
- Added the functionality to force the consent details to be returned (They are not returned if PayPal detects that you are not in US): `forceConsentDetails` property
- Added code comments for the majority of interfaces/configurations
- Added/fixed tests
=> Fastlane - Retrieving consent details and fastlane session id

.github/workflows/e2e.yml
Increases the timeout for the e2e pipeline from 60 to 120 mins. I could have increase more but I think we should discuss again if we need to increase this number further.
=> chore: increase timeout for e2e job

packages/e2e-playwright/tests/e2e/dropin/storedCard/stored-card-ach.spec.ts
Skip the `e2e/dropin/storedCard/stored-card-ach.spec.ts` test for api version 69.
=> test(stored-card-ach.spec): skip on api v69

.changeset/many-clouds-try.md, packages/lib/src/components/Ach/components/AchInput/AchInput.scss, packages/lib/src/components/Ach/components/AchInput/AchInput.tsx, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.scss, packages/lib/src/components/internal/OpenInvoice/OpenInvoice.tsx, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/src/styles/mixins.scss
Apply the built-in mechanism initiated via the `UIElement.setElementStatus` method to disable an `OpenInvoice` when the "Pay' button is pressed.
***Open questions:***
- Do we agree this mechanism is the best way to do this?
- If we do, then should the component specific `.scss` file (`OpenInvoice.scss`), which always needs to set a new class anyway, use a mixin the way we have done here:
```
.adyen-checkout__open-invoice{
&--loading{
@include index.adyen-checkout__component--loading;
}
}
```
_or_
each time just set it's own component specific class, and not use a mixin at all:
```
.adyen-checkout__open-invoice.adyen-checkout__open-invoice--loading {
pointer-events: none;
}
```
An `OpenInvoice` component is now disbaled when "pay" is pressed
=> Use built-in mechanism to disable OpenInvoice when Pay pressed

.changeset/small-otters-rule.md, packages/lib/src/components/CustomCard/types.ts
Added missing type (`onAutoComplete`) in `CustomCardConfiguration`
**Fixed issue**:  #3137
=> Add missing type (onAutoComplete) in CustomCardConfiguration

.changeset/afraid-clocks-drop.md, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/types.ts, yarn.lock
Calling reject() inside 'onClick' throwns an unhandled exception. This PR fixes the issue.
Fixes #3140
=> GooglePay - Fixing 'onClick' reject

.changeset/afraid-roses-cheer.md, packages/lib/src/components/Dropin/components/PaymentMethod/InstantPaymentMethods.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.tsx, packages/lib/storybook/stories/dropin/Dropin.stories.tsx
Instant payment methods were never set as 'active payment method' within Drop-in.
When handling actions inside Drop-in (E.g. 3DS2 for GooglePay), its code relies on the 'activePaymentMethod' , and in this case the active payment method was being another payment method instead of the one being clicked.
In this PR, an event listener is added to the markup wrapping the payment method ([same approach as we have here](https://github.com/Adyen/adyen-web/blob/main/packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.tsx#L88)). Once the payment method is clicked, it is set as the active payment method. 
There is a UI effect though: If there is one payment method active and open (e.g. card) , and shopper clicks in an instant payment method button, the …
=> GooglePay - Handling challengeWindowSize when using GooglePay as Drop-in Instant payment method

.changeset/stale-days-count.md, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.tsx
- Throwing an error if merchant does not setup the Component configuration correctly
- This helps with troubleshooting in case the required config is missing
=> Google Pay - Throwing error when required config is missing

packages/lib/src/components/GooglePay/GooglePay.tsx
This change fixes a typo for the error message when the Google Pay merchantId is missing in the configuration:
Before: `Please ensure the it is correctly configured in your customer area.`
After: `Please ensure that it is correctly configured in your customer area.`
N/A
**Fixed issue**:  N/A
=> fixing typo in error message for the Google Pay merchantId check

.changeset/cool-teachers-tease.md, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/isConfigured.ts
When a Card component is instantiated to be single branded (most commonly as a stored card), the error message, for when this setup is configured incorrectly, still reflected how it used to be done in v5, not how it should be done in v6
**Fixed issue**:  This confusion around the error message was raised recently in a Q&A thread
=> Update error message for single branded card

packages/lib/src/components/ApplePay/ApplePay.test.ts, packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/internal/SecuredFields/lib/CSF/partials/isConfigured.test.ts
- Adding a check for HTTPS before calling ApplePaySession.supportsVersion. (If we avoid this check, the browser console gets a warning message from Apple Pay SDK which is not needed)
=> Apple Pay - Https check before calling  ApplePaySession.supportsVersion API

.changeset/funny-tables-film.md, packages/e2e-playwright/tests/ui/card/binLookup/panLength/panLength.focus.regular.spec.ts, packages/lib/src/components/internal/SecuredFields/lib/constants.ts
Allow the shopper to input more digits into the `cardNumber` field even after the `/binLookup` call returns a `panLength`.
Previously we were freezing the field based on the `panLength` result - but a recent case where the BIN table contained an incorrect `panLength` value means we will now allow the shopper to add more digits if they want to.
**Note:** relies on update to securedFields `5.5.1`
Existing e2e test corrected to allow for new scenario
All other e2e tests pass
**Fixed issue**:  COWEB-1485
=> Allow typing to continue in cardNumber field after panLength result

.changeset/quiet-berries-wonder.md, packages/lib/src/components/Card/components/CardInput/components/CVC.tsx, packages/lib/src/components/Card/components/CardInput/components/CVCHint.tsx, packages/lib/src/components/Card/components/CardInput/components/ExpirationDate.tsx, packages/lib/src/components/Card/components/CardInput/components/StoredCardFields.test.tsx, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodItem/PaymentMethodItem.scss, packages/lib/src/components/Giftcard/components/GiftcardResult.scss, packages/lib/src/components/internal/Await/Await.scss, packages/lib/src/components/internal/ExpandButton/ExpandButton.tsx, packages/lib/src/styles/variable-generator.scss
Small fixes long description to document this changes for the future.
These are documented in COWEB-1484. However to summarise the issue is that the `color-label-tertiary` never has enough contrast, even against a white background, so here I just override it via our scss token loader. The same happens for the red color used for the error messages. 
Basically this change keeps being requested by merchants who have automated tools. Currently `aria-expands` on radio elements is still not part of the official aria spec. See the proposal here: https://github.com/w3c/aria/issues/1404
So for now we are going to disable this feature. The objective is to enable it soon as the proposal get's approved.
This is a 2 in 1, we remove `aria-describedby` from the SVG and also add additional information to …
=> Fixes small a11y problems

.changeset/famous-kiwis-report.md, packages/lib/src/components/ApplePay/ApplePay.tsx, packages/lib/src/components/ApplePay/defaultProps.ts, packages/lib/src/utils/detectInIframe.ts, packages/lib/src/utils/inIframe.ts
Executing iframe detection inside `defaultProps` caused an issue within SSR apps.
In this PR:
- Code was moved to `formatProps`
- Also wrapped the function inside a try-catch just in case
Tested build file in a NextJS app
Fixes #3202
=> Apple Pay - Fix for server-side rendered apps

.changeset/pretty-apricots-fetch.md, packages/lib/src/utils/browserInfo.ts
`browserInfo.ts` no longer calls deprecated `navigator.javaEnabled` function
As described in the docs, this function is now deprecated and will always return `false`
(ref: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/javaEnabled)
So we keep the property for backward compatibility but always directly set it to equal `false`
=> BrowserInfo no longer calls obsolete navigator.javaEnabled function

.changeset/young-cougars-knock.md, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/internal/UIElement/UIElement.tsx, packages/lib/storybook/stories/components/Klarna.stories.tsx
Fixed issue where Google Pay standalone component wasn't recognizing 'paywithgoogle' payment method.
To fix that, Google Pay had to override the new method 'getPaymentMethodFromPaymentMethodsResponse()' and also inspect the payment methods response for its varirant 'paywithgoogle'
- Added tests
- Tested Google Pay component with 'paywithgoogle' tx type
**Fixed issue**:  #3191
=> Google Pay - Adding support for 'paywithgoogle' when using standalone component  

.changeset/new-lies-doubt.md, packages/e2e-playwright/mocks/binLookup/binLookup.data.ts, packages/e2e-playwright/tests/ui/card/binLookup/plcc/plcc.luhn.paste.spec.ts, packages/e2e-playwright/tests/ui/card/binLookup/plcc/plcc.noluhn.nodate.spec.ts, packages/e2e-playwright/tests/ui/card/expiryDate/card.expiryDatePolicies.hidden.spec.ts, packages/e2e-playwright/tests/utils/constants.ts, packages/lib/src/components/internal/SecuredFields/lib/constants.ts
Upped SF version (to `v5.5.2`) to fix issue with LastPass & autofilling
There was an issue with LastPass password manager when it came to auto-filling the `expiryDate` in the Card component.
Their autofill process was bypassing any handlers we had for the autofill situation (because it wasn't firing the expected events on the input fields in securedFields) - and was managing to directly inject a 4 digit expiry year. This then got truncated into 2 digits (but unfortunately it was the first 2 digits, not the last 2 --> so **2030** was ending up set as **20** - which is an "expired" year)
This was not a situation we had prepared for (since our handlers were expected to be engaged, and would have caught this 4 digit year scenario).
A fix with securedFields detects a 4 digits expiry year and …
=> Upped SF version to fix issue with LastPass auto-filling expiryDate

.changeset/calm-foxes-chew.md, packages/lib/src/components/internal/SecuredFields/lib/securedField/SecuredField.scss
Fixed issue where card inputs weren't respecting background color styles if the merchant set a meta tag to describe the color scheme e.g. `<meta name="color-scheme" content="dark">`
Because the color scheme of the iframe was seen as different to that of the parent, embedding, document - the iframe was getting an opaque background (a fuller explanation can be found in [the issue](https://github.com/Adyen/adyen-web/issues/3259) and the links contained within)
Manually tested with both Card and Custom Card components
**Fixed issue**:  #3259
=> Fixed issue where card inputs weren't respecting background color styles

.changeset/orange-lights-occur.md, packages/lib/src/components/ApplePay/types.ts, packages/lib/src/components/ApplePay/utils/payment-request.test.ts, packages/lib/src/components/ApplePay/utils/payment-request.ts
This PR adds support for the `shippingContactEditingMode` Apple Pay configuration value which can be used to prevent a user from editing the shipping address. This is useful for store pickup checkout options. Relevant documentation:
https://developer.apple.com/documentation/applepayontheweb/applepaypaymentrequest/shippingcontacteditingmode
A test has been added to `payment-request-test.ts` for `shippingContactEditingMode`.
N/A
=> feat(applepay): add support for `shippingContactEditingMode`

.changeset/six-jeans-teach.md, packages/lib/src/components/Dropin/Dropin.tsx, packages/lib/src/components/Dropin/types.ts, packages/lib/storybook/stories/dropin/Dropin.stories.tsx
- Added `filterStoredPaymentMethods` callback to the Drop-in. This callback lets you choose which saved payment methods appear in the Drop-in.
- It will be first used by hosted checkout for pay by bank pix to present only one stored pm in the drop-in
It's difficult to unit test, i created a story to show only ach save pms https://localhost:3020/?path=/story/dropin-default--only-saved-ach
=> feat(dropin): added `filterStoredPaymentMethods` callback

package.json, yarn.lock
Attempts to fix https://github.com/Adyen/adyen-web/security/dependabot/188 by pinning the vulnerable dependency as there's no upgrade path available.
=> Chore: Update tar-fs to 3.0.8

.changeset/rude-lizards-buy.md, packages/e2e-playwright/models/card.ts, packages/e2e-playwright/models/giftcard.ts, packages/lib/src/components/Card/components/CardInput/CardInput.test.tsx, packages/lib/src/components/Card/components/CardInput/CardInput.tsx, packages/lib/src/components/internal/SecuredFields/SFP/SecuredFieldsProvider.ts, packages/lib/src/components/internal/SecuredFields/SFP/types.ts, packages/lib/src/core/core.misc.test.ts
I have rewritten this PR. The objective is to achieve the same behaviour as LoadingWrapper, but at CardInput level, without changing any of the DOM, or the the existing callbacks.
I believe this is the best way of achieving this, however it has to introduce a new callback that passes the full state up from SecureFieldsProvider to CardInput.
Other possibilities would be to use onConfigSuccess callback but this would not copy `status` and would in the end require additional steps and logic. For example, there's no clean way to handle the 'failed' to load status.
Another way could have been to listen to `onChange` and catch this changes in `handleSecuredFieldsChange` since the state is available here. Problem is that we don't call `onChange` when secure fields gets configure, so it doesn't …
=> Card: Fix SF loading state not hiding pay button

packages/lib/package.json, yarn.lock
- Patch security issue [#172](https://github.com/Adyen/adyen-web/security/dependabot/172)
- Upgrade Vite to the latest version will upgrade esbuild to 0.25.0 or higher, which can solve the security issue.    
- Storybook runs and builds correctly
- Verified esbuild 0.25.0 or higher is install:
```
vagrant@vagrant:~/workspace/forked-adyen-web$ npm ls esbuild
@adyen/adyen-web-main@ /home/vagrant/workspace/forked-adyen-web
└─┬ @adyen/adyen-web@6.14.0 -> ./packages/lib
├─┬ storybook@8.6.12
│ └─┬ @storybook/core@8.6.12
│   ├─┬ esbuild-register@3.5.0
│   │ └── esbuild@0.25.0 deduped
│   └── esbuild@0.25.0
└─┬ vite@6.3.5
└── esbuild@0.25.4
```
=> chore: update vite to solve security issue(#172) for esbuild <= 0.24.2

.changeset/loose-ducks-appear.md, packages/lib/src/components/Dropin/components/PaymentMethod/PaymentMethodList.test.tsx, packages/lib/src/components/Giftcard/Giftcard.test.tsx, packages/lib/src/components/Giftcard/Giftcard.tsx, packages/lib/src/components/Giftcard/components/GiftcardComponent.tsx, packages/lib/src/components/Giftcard/components/GiftcardResult.tsx, packages/lib/src/components/Giftcard/components/useSRPanelForGiftcardErrors.ts, packages/lib/src/components/MealVoucherFR/MealVoucherFR.test.tsx, packages/lib/src/core/Errors/utils.ts, packages/lib/storybook/stories/giftcards/Gifcards.stories.tsx, packages/lib/storybook/stories/giftcards/GiftcardExample.tsx, packages/lib/storybook/stories/types.ts
Adds error panel to Giftcard.
There's a few tricks however, the `useSRPanelForGiftcardErrors` hook is passed to render function because Giftcard component is a Class component. 
Also we had to use `mapErrorsToValidationRuleResult` to conver SF errors into `useForm` like errors. 
=> Feature: Add srpanel for gift card

.changeset/social-banks-pay.md, packages/lib/src/components/Ach/Ach.test.ts, packages/lib/src/components/Ach/components/AchComponent.tsx
Component pay button now displays "Pay {value}" instead of "Continue purchase"
=> ACH - Fixing pay button label

.changeset/fine-hoops-talk.md, packages/lib/src/components/Card/types.ts
=> fix: adds missing onAddressSelected callback type to CardConfiguration

.changeset/brown-papers-cross.md, packages/lib/src/components/internal/ClickToPay/components/CtPCards/CtPSingleCard/CtPSingleCard.test.tsx, packages/lib/src/components/internal/ClickToPay/models/ShopperCard.ts
We need to treat cards with Status Active and Pending as active (non expired).
**Fixed issue**:  DSP-2728
=> fix(click-to-pay-ShopperCard): treat 'ACTIVE' and 'PENDING' cards as active

.changeset/silver-ideas-care.md, packages/lib/src/types/global-types.ts
Add missing properties to the `PaymentData` interface to align with the data structure expected in payment submission flows.
This aligns with what is right now on `BeforeSubmitActions`.
#3419
=> fix missing props in PaymentData

.github/workflows/.size-limit.yml
Reverts the modifications of sizelimit job back to be only on Pull request as size-limit action does not support push flow.
=> revert size limit triggers

.changeset/slimy-waves-smoke.md, packages/lib/src/components/PayTo/components/BSBInput.tsx, packages/lib/src/components/PayTo/components/PayIDInput.tsx, packages/lib/src/components/PayTo/components/PayToComponent.tsx, packages/lib/src/components/internal/FormFields/Fieldset/Fieldset.tsx
There was an error caught by our a11y tool that PayTo SegmentedController wasn't using IDs that were pointing properly to the Fieldset. 
This PR makes that change. 
Fieldset now supports optional IDs.
=> fix(PayTo): SegmentedController aria-controls IDs

.changeset/tall-groups-speak.md, packages/lib/src/components/UPI/components/UPIIntentAppList/UPIIntentAppItem/UPIIntentAppItem.scss, packages/lib/src/components/UPI/components/UPIIntentAppList/UPIIntentAppItem/UPIIntentAppItem.tsx
As part of the [changes](https://github.com/Adyen/adyen-web/pull/3509/files#diff-56d114899088d200a29b44f490114d7e5fd66f84f3f769ed063baa76819c3b31) for improving the Pix UI, we removed the checkmark from the segmented control component. This however broke the styles for the checkmark on the UPI app selector component as it was depending on styles from the segmented control component. This change add specific styles for the checkmark on the `UPIIntentAppItem`
=> UPI: Fix checkmark styles for upi app selector

.changeset/smooth-cloths-relax.md, packages/lib/.size-limit.cjs, packages/lib/src/components/GooglePay/GooglePay.test.ts, packages/lib/src/components/GooglePay/GooglePay.tsx, packages/lib/src/components/GooglePay/defaultProps.ts, packages/lib/src/components/GooglePay/types.ts, packages/lib/src/components/GooglePay/utils/map-adyen-brands-to-googlepay-brands.test.ts, packages/lib/src/components/GooglePay/utils/map-adyen-brands-to-googlepay-brands.ts
This PR adds capability for Google Pay to parse `brands` returned from `paymentMethods` response:
- Merchant can still override this on the frontend by setting `allowedCardNetworks` config. By doing that, the `brands` returned by backend are ignored
- For legacy integrations (e.g. using `paywithgoogle` tx variant) , `brands` are not returned in the API. There is a fallback value that is set in case nor `brands` nor `allowedCardNetworks` are set
- Added tests
**Fixed issue**:  #3506
=> Google Pay -  Parsing brands from paymentMethods API

.github/workflows/release.yml, .yarnrc.yml
This set default for immutable installs to be false except the `--immutable` flag is used explicitly
=> Yarn: set default for immutable installs
